### ISSUE TITLE
[plugin] group invites and passes

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#114]
* users leaving a group will be issued a one-use pass to re-add themselves into the group
* admins can generate limited-use invites to users to add themselves into a specific group e.g. `/bot invite to <conv_id> [allusers|users <list>] [from <conv_id>] [expiry <seconds>]`
* implemented as ~~part of convtools plugin or~~ separate plugin ~~(haven't decided yet)~~
* uses `memory.json` to remember invites, structure:
```python
memory.invites = {}
memory.invites["<id>"] = {
    "id": "<randomly generated id>",
    "user_id": "<wildcard|user_id>",
    "group_id": "<wildcard|group_id>",
    "uses": <integer, decremented on each use>,
    "expiry": 2592000 //1 month
}
// searching would be inefficient, but optimisation is 
// not particularly warranted since these are one-off 
// uses and will not significantly impact other running 
// operations
```

**Comment by endofline** [comment]
suggested bot commands (subject to change):
```
invite
  to <conv_id> // bot must be member, must be group chat
  from <conv_id> // bot must be member, must be group chat
  allusers // issue wildcard invitation
  users // if from specified, filter members in from; if not specified, add blindly  
    <space-separated user_ids>

rsvp list
  show all applicable invites (including wildcards)
rsvp <id>
  claim invite
```

**Comment by nylonee** [comment]
I also considered a `/bot joinhangout` command which will work with a simple numbered interface as follows:

`/bot joinhangout`
*Hangouts that you can join:*
1. *All chat*
2. *Antarctica chat*
3. *Tech support*
*To join a hangout, type* **/bot joinhangout [number]**

`/bot joinhangout 2`
*Added to Antarctica Chat*

This could potentially work alongside an invite functionality, or an admin defining which hangouts will make it to the list.

**Comment by endofline** [comment]
@nylonee sounds like an alias for `rsvp`

**Comment by endofline** [comment]
on the subject of numbering invites instead of the invite code, the ordering may change due to the botmin and user operating on the bot simultaneously. the invite codes might be replaced eventually with numbers if we can fix the order of invites as they are displayed to the user, but this will require some extra metadata to be stored as part of `memory.json`
