### ISSUE TITLE
[plugin] plugin manager/management

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#122]
the amount of available plugins requires a chat-configurable plugin manager - perhaps a simple one can be created first that can list available and loaded plugins

some considerations:
- enabling/disabling plugins would probably require a bot restart
- a migration script will need to be added for botmins running empty config.plugins

**Comment by endofline** [comment]
with the glut of plugins available (or will soon be available) we really need to improve plugin management

**Comment by 00svbeon** [comment]
@endofline we really need to, question is if it should be client side or server side manageable? And how the bot should reload/unload plugins, by having a function inside that unloads them without restart of bot (harder to implement maybe?) or a restart command. 

That way it might be able to have a `/bot pman` command (plugin manager) that lists active (and disabled) plugins and `/bot pman - [plugin]` (- or disable) to disable one and `/bot pman + [plugin]` (or activate) to activate one (this makes changes in the plugins part in config.json) maybe use `/bot pman reload` to reload commands?

**Comment by endofline** [comment]
This is partially implemented in 2.7 via #300 - as in the case of [Plugin Control Commands](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Control-Commands). If they prove popular, we can make the functions modify the actual `plugins` key in `config.json`

**Comment by nylonee** [comment]
A plugin has been made for managing plugins [here](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/pluginmanager.py)

**Comment by nylonee** [comment]
Note that this remains blocked for various reasons
- [ ] Pluginloader won't detect hidden plugins prepended by a `_` (eg. `_example_plugin.py`)
- [ ] Currently implementing 3 redundant commands, should be refactored into current existing commands (with backward compatibility maintained)
