### ISSUE TITLE
"move to top" plugin = CLI command to rename/set topic on a hangout

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#141]
When having lots of Hangout conversations, some are more important, and admins might want these hangout to remain on top even if there are no message over last 24 hours/xx days.
(announcement / alert hangouts for example).
In order to "move to top" a hangout without triggering a notification to users, a solution is to rename hangout name, it updates hangout, and as a result move hangout to top, but no message, so no notification.

Plugin should for example add an extra space or non-visible character at the end of hangout name, and then remove it.

Plugin should run in CLI only, so server admin can add it to a cronjob to run every xx hours/days.

**Comment by endofline** [comment]
this is actually a fairly novel idea, will have a look at it once some of the more outstanding issues are resolved. for the adventurous, modifying one of the [sinks](https://github.com/nylonee/hangupsbot/wiki/Sinks) to "touch" a conversation instead of [sending a message](https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/sinks/generic/simpledemo.py#L21) (effectively moving it to the top) on a (cron) web request is possible - the command to directly rename the target conversation will be a variant of `asyncio.async( bot._client.setchatname(conv_id, "the title") )`

**Comment by PaulTimmins** [comment]
https://github.com/PaulTimmins/hangupsbot/commit/d1a9eba5b9c455a6bb43252320db0b34cd6689c8

This will expose the command to the sink.

This is a plugin that will call those functions:
https://github.com/PaulTimmins/hangupsbot/commit/2c22712f161141af7f9efd511fd379cb2ceeef8b

This is a sink that will call them:
https://github.com/PaulTimmins/hangupsbot/commit/ea2818fe90cc1079aa1664485826fc08103d944a

**Comment by nylonee** [comment]
You can use the [api plugin](https://github.com/nylonee/hangupsbot/wiki/API-Plugin#example-commands) to issue commands remotely. From command line you can easily do GET requests, the url that you'll have to request to send a chat to the top would be:
https://[ADDRESS]/[APIKEY]/[chat_id]/%2Fbot%20rename%20[CHATNAME]

This will 'touch' a chat, renaming it to the same name and bringing it back to the top.

**Comment by endofline** [comment]
A note about @nylonee's API call, the newer API plugin now comes with a test script you can adapt to call the API in a more secure and consistent way:
```
python3 hangupsbot/tests/api-send.py https://<address>:<port> <convid> <apikey> "/bot rename <chatname>"
```

You could configure a cron job to do this automaticaly.

**Comment by FrNico** [comment]
Just tested that, it's working great!

Now to silently "touch" a chat, to move it to top without notifying members, we should add add "conv_id" to rename command, so we can do it from another bot chat.

/bot rename <conv_id> <chatname>

**Comment by endofline** [comment]
Bit late updating this: [`/bot convrename`](https://github.com/hangoutsbot/hangoutsbot/wiki/Default-Commands-Plugin) serves as the resolution for this issue

**Comment by endofline** [comment]
I'm not quite sure whether this has been resolved or not yet, so I'll leave it open, just in case. Please feedback whether it's done :)

**Comment by FrNico** [comment]
/bot convrename works perfectly
only issue, but not related to hangoutsbot... is that we can no longer
"move to top" an hangout by simply renaming it on Hangouts v4.x... renaming
an hangout where you have notification on, will generate a notification
(same for adding people into that hangout).

2015-08-16 10:28 GMT+02:00 Innocent Bystander <notifications@github.com>:

**Comment by endofline** [comment]
Ah, that is annoying, I will close this issue then since it seems to have become a platform limitation due to HO4 :( Feel free to re-open it if we find any new way to shift a conversation up without a flurry of notications.
