### ISSUE TITLE
localisation maintenance

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#155]
pot file need to be re-extracted and localised strings added/updated

**Comment by endofline** [comment]
will be updated post-2.4

**Comment by 00svbeon** [comment]
Move to new locales branch

**Comment by 00svbeon** [comment]
Refer to #192

**Comment by endofline** [comment]
This is related (and resolves) to a very old issue raised awhile ago: #57 - with the release of 2.5, I'm closing this in favor of the [separate translation project](https://github.com/hangoutsbot/hangoutsbot-locales)
