### ISSUE TITLE
Replace websink with aiohttp

### ISSUE THREAD

**Issue by j16sdiz** [hangoutsbot/hangoutsbot#163]
The current thread-based http server have the following downside:

 1. One server port / cert per websink => Redundant config for each websink. More Admin works
 2. Thread does not mix well with asyncio coroutine. Waiting results from other coroutines in base bot is painful.

aiohttp 0.15.1 include a build-in http router / command dispatcher, and it is fully compatible with asyncio. This version is depended by new hangups, so it is not an extra dependency .

The only problem is, the interface cannot be compatible with old websinks. May cause extra works when migrating

**Comment by endofline** [comment]
Accepting proposals for a new more responsive sink framework based on this.

**Comment by endofline** [comment]
Work has begun on implementing aiohttp-based listeners, one of the bigger questions that has occurred to me is how to migrate older sinks which use different ports - I'm thinking of some combination of old port number + module name could be used as secondary alternate route to cut down on administrator guesswork during a migration.

**Comment by endofline** [comment]
On a technical note, the implementation in #163 retains the older one port per sink to make it easier for existing botmins - the old sinks configuration and initialisation remains as part of the framework. In the case of the API and Slack plugins, their original configuration are fully-compatible with the new aiohttp-based sinks.
