### ISSUE TITLE
enhanced monitoradds plugin watch_new_adds options

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#168]
monitoradds could alert moderators when somebody is added to a hangout by a non-admin/non-mod, we can suggest to have more flexibility in "watch_new_adds" parameter like that:

 - "watch_new_adds": false,
don't monitor adds, same as today, no change

 - "watch_new_adds": quiet,
NEW: monitor adds, don't warn in hangout, but notify "mods_list" in 1-to-1 hangout
Example: "WARN: NameX (link to G+ profile) invited NameY (link to G+ profile) into Conv_ID (Conv_topic)"

 - "watch_new_adds": true,
monitor adds, and warn in hangout, same as today, no change

 - "watch_new_adds": both,
NEW: monitor adds, warn in hangout AND notify "mods_list" in 1-to-1 hangout

**Comment by Riptides** [comment]
I've written something similar to this with the difference being the alert goes to a "mod chat" instead of a bunch of 1-to-1s. Once I get a chance to do some testing I'll submit a PR.

**Comment by nylonee** [comment]
This has been implemented in #519
