### ISSUE TITLE
[plugin request] policy enforcement: history on|off

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#169]
Similar to /bot topic allowing to enforce an Hangout topic, a command like:
   /bot history [on|off]
allowing to force history on/off status, changing it back if a user is trying to change it by mistake
Additional parameters could allow a temp on/off change for xxx secondes or for a single message
  /bot history [on|off] [timer_in_seconds|once]
Example:
/bot history off 600
On a "history-on" hangout, it will disable history for next 10min and bot will enable it back after that.
/bot history on once
On a "history-off" hangout, it will enable history, then wait for a single message to be posted, and immediately disable history after that

**Comment by mxxcon** [comment]
:+1:

**Comment by endofline** [comment]
Unfortunately at this point, the hangups library cannot enforce the history flag for a group chat. It can only set the history flag on and off for its own messages. Since this may change for future versions of the library, we will keep this this issue open for tracking and updates.

**Comment by Terrance** [comment]
Implemented in v3 via the `offtherecord` plugin.
