### ISSUE TITLE
/bot users and user can be one command, as well as hangouts and hangout

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#186]
/bot users lists all users, /bot user lists only the user that you specify.
They can be merged such that if no parameter is given, list all users. If a keyword is given, list only users that satisfy that keyword.

Same goes for hangouts and hangout.

**Comment by endofline** [comment]
This use to be for backward compatibility to xmikosbot - if the repo de-fork is about to proceed, guess it wont be important anymore ;P

**Comment by endofline** [comment]
the `user`/`users` change has been reverted, as it resulted in a bug - further comments welcome
