### ISSUE TITLE
Bot freezes when cleverbot is running

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#187]
The bot should not be pausing to wait for a response from the Cleverbot API

**Comment by endofline** [comment]
This would probably be useful: https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/plugins/image_memegenerator.py#L20 - aiohttp and a `yield from`

**Comment by endofline** [comment]
Borrowed [BaseEventLoop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.run_in_executor) instead

**Comment by endofline** [comment]
Tested and added to #300
