### ISSUE TITLE
[framework] Plugin submodules to load recursively instead

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#190]
In fixing #189, it was noted that the same family of plugins should be in the same subfolder. For example syncrooms:
```
plugins
    --> syncrooms
        --> __init__.py
        --> syncrooms_config
            --> __init__.py
        --> syncrooms_autotranslate
            --> __init__.py
``` 

However, the current framework does not support submodules with a depth > 1, so this current structure is not possible.

**Comment by endofline** [comment]
interestingly enough, this was already supported for manual configurations:
```
plugins: ["example", "example.example_subplugin1", "example.example_subplugin2]
```

The above would load the following plugins:
```
+ plugins
  + example
    + __init__.py  # loaded by "example"
    + example_subplugin1.py  # loaded by "example_subplugin1"
    + example_subplugin2.py  # loaded by "example_subplugin2"
```

82ee165 simply extends this facility if `config.plugins` is blank/unset

**Comment by endofline** [comment]
Wiki entry on [plugin subfolders and sub-plugins](https://github.com/hangoutsbot/hangoutsbot/wiki/Configuration#plugins-in-sub-folders)

**Comment by endofline** [comment]
all links accounted for and added to #248
