### ISSUE TITLE
erratic behaviour of /bot invite list and /bot invite purge

### ISSUE THREAD

**Issue by 00svbeon** [hangoutsbot/hangoutsbot#193]
/bot invite list and /bot invite purge both returns:
invite: missing "to" or "from"
No more info right now as iIcan't check logs while building phantomjs...

**Comment by FrNico** [comment]
/bot invite list seems to be working for me
I haven't tested purge :)

**Comment by 00svbeon** [comment]
Yes, they are working now

**Comment by nylonee** [comment]
Just had a case where both list and purge is not working. Reopening this issue.

**Comment by endofline** [comment]
Interestingly another way of triggering the bug was to simply issue a `/bot invite random_text list` - this would cause the bot to create a new junk conversation due to changes introduced in 01224e36822968f3506ba9137afa0b99bf335b3b

**Comment by endofline** [comment]
Plugin modified to only create conversation once it has a valid invitee list (0efc8e5c9b3aa75a41a1d3ddfe0ee07787d8a385) instead of before. This should prevent junk group creation in most scenarios. For existing conversations it will verify that it exists in convmem or error out.
