### ISSUE TITLE
Locales folder as a git submodule+translation discussion

### ISSUE THREAD

**Issue by 00svbeon** [hangoutsbot/hangoutsbot#194]
Locales can be made a git submodule, this way you can give translators access to that git and not the whole project. 

Another point to look at is wherever it should use a translation management platform such as weblate.org, oneskyapp.com, crowdin.net, pootle, 
Poeditor.com etc.

and about that I'm willing to help translate to Swedish.

**Comment by 00svbeon** [comment]
Also I'm worried that there is no origin English file available...

**Comment by nylonee** [comment]
@00svbeon This is a great idea, it would be beneficial to build on the locales, which were cherrypicked from xmikos' original hangupsbot. I don't have much experience with locales, would you be willing to issue a PR on this?

**Comment by endofline** [comment]
#197 has been closed - we will split off the localisation files into individual submodules as needed

**Comment by 00svbeon** [comment]
I'm not yet sure how or when these locales is used currently, but iIthink it's better if you start create the submodule and give me access to it and I'll start there by creating an en file and yeah...

**Comment by 00svbeon** [comment]
@endofline i don't think every lang needs it's own submodule, it's enough with a locales submodule i think...

**Comment by nylonee** [comment]
@Deuteu FYI

**Comment by endofline** [comment]
@00svbeon noted, locales will be turned into a git submodule :+1:

**Comment by 00svbeon** [comment]
Super

**Comment by 00svbeon** [comment]
Just noting, while waiting for a translations branch to be created that weblate.org provides free hosted service for open source projects, we might be able to use this for the translation process

**Comment by 00svbeon** [comment]
Also noting that there might be a need to check how it's used in xmikos original code and optimise our code to use it, as well as adding strings we added to the blank file that's soon to be created... (shortly after the branch)

**Comment by endofline** [comment]
hello @hangoutsbot/translators - locale has been split off into its own submodule, here is the repo: https://github.com/hangoutsbot/hangoutsbot-locales

**Comment by 00svbeon** [comment]
Refer to #155

**Comment by Deuteu** [comment]
Seems good idea to me.
But can someone explain me how submodule works quickly? For example, if I push some thing to locale submodule, does it automatically push it to main module? Ty.

**Comment by 00svbeon** [comment]
It's pretty much a link to a repo inside a repo @Deuteu

**Comment by endofline** [comment]
Manual close of this issue since locales has been split and the [translation project](https://github.com/hangoutsbot/hangoutsbot-locales) is available.
