### ISSUE TITLE
[plugin request] shared administrative events log

### ISSUE THREAD

**Issue by NeoEGY** [hangoutsbot/hangoutsbot#196]
Can the bot keeper include a msg to admins/keepers when someone not authorized tries to add the bot to a new hangout for example it would pm admin " User xyz, g+ link, added me to hangout xyz no bot keeper found and hangout abandoned"

**Comment by nylonee** [comment]
Spoke to @NeoEGY, having a single plugin give a log output to admins will introduce plugin inconsistencies.

What I proposed instead is the ability for the bot to optionally output a log to a list of admins/hangouts. This could be done using a plugin, or it could be implemented into the framework (probably better to do it as a plugin to gauge interest in such a feature).

Plugins can then send log messages where needed in such a format:
```
self._bot.call_shared("logger.send_to_admins", "User 1 tried to add User 2 to Hangout 1")
```
And the logger plugin will handle the message, choosing either to suppress it or send it to a hangout depending on configuration.

**Comment by endofline** [comment]
Call it "adminlogger" :stuck_out_tongue: - make it optional; catch the KeyError if it doesn't exist; also implement it in blocks of 2-3 plugins, or better yet, 1-by-1

**Comment by endofline** [comment]
You also need a classification strategy (or several) for the messages if you intend to have filtering, such as tagging ("critical", "normal", etc), source identification ("internal", "external", "plugin", etc), scoring perhaps?

**Comment by endofline** [comment]
The above commit leverages the internal Python logging facilities - you can set the logger to direct any messages of an arbitrary log level to any other conversation that is tagged `receive-logs`. The log-level is set on a per-plugin/module basis via `/bot logconfig <module name> <log level>` where `<module name>` can be acquired from `/bot plugininfo` and `<log level>` either the numerical value or label name from the [Python logging values](https://docs.python.org/3/library/logging.html#logging-levels).

Experience with the plugin is previously recommended as different plugins has wildly varying levels of verbosity associated with their events. However, it will be mostly safe if you set a plugin's log level at `WARNING` / **30** - and either adjust it lower or higher depending on the verbosity.

**Comment by endofline** [comment]
Wiki updated:
* https://github.com/hangoutsbot/hangoutsbot/wiki/Logger-to-Chat-Message
* https://github.com/hangoutsbot/hangoutsbot/wiki/Core-Commands

**Comment by endofline** [comment]
Documentation link and summary added to #300
