### ISSUE TITLE
[plugins] "What's new" Changelog

### ISSUE THREAD

**Issue by 00svbeon** [hangoutsbot/hangoutsbot#204]
Storing version number in memory.json (and version.py) once version.pu changes (i.e.Doesnt match number in memory.json) there is a changelog file like:
    2.3
    -Added...
    -Deleted... 
    2.4.1
    -Added...
    -Deleted... 
    2.4.2
    -Added... 
    -Deleted... 
And after update (on bot start) it notifies admins "bot updated this is what changed: {}" where {} is content of updated s for version "old" to "new" in example I updated from 2.3 to 2.4.1 {} is
    2.4.1
    -Added... 
    -Deleted... 
And if I Iupdate from 2.3 to 2.4.1 it's
    2.4.1
    -Added... 
    -Deleted... 
    2.4.2
    -Added
    -Deleted
And so on. gives a nice overview and gets up dators started sooner

**Comment by nylonee** [comment]
I like this idea. Where would the changelog be displayed? Would admins be able to request it through a command or would it automatically be sent to all admins when updated?

**Comment by 00svbeon** [comment]
My though was sent to admins when updated automatically. But maybe something like
/bot changelog [v1] [v2] could be used

**Comment by endofline** [comment]
I'm open to an implementation strategy for this. I must point out though that the framework and different plugins have separate histories that may not necessarily correspond to the version number so tracking records might be difficult.

**Comment by pleasantone** [comment]
Sounds like a spawn, not a plugin, if this ever gets implemented.
