### ISSUE TITLE
Add optout option for "Be more specific" message when mention user

### ISSUE THREAD

**Issue by nimbusparis** [hangoutsbot/hangoutsbot#207]
When you mention a user in a group HO and that user had the same nick than another, the bot send me a message like:

4 users would be mentioned with "@Laurent"! Be more specific. List of matching users:
Laurent D
Laurent C
Laurent R

Is it possible to add an optout to avoid this message which is useless most of the time?

**Comment by Deuteu** [comment]
If you want a by user optout it's not easy but a global option for all user can be added quickly I think.

Note for dev :
In my opinion adding a test on a new option in config (be_more_specific [true/false] for example) near
https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/mentions.py#L220

**Comment by nimbusparis** [comment]
This would be for the user that try to mention someone, not by users mentionned. 
Since longpress of the avatar create a mention on the first name on HO on mobile, it's really enoying to correct the mention to add more characters constantly to avoid the message from the bot, especially when you mention someone on flood HO...

**Comment by endofline** [comment]
@nimbusparis, in the latest version of the bot, you will be able to toggle the "be more specific" messaging by using `/bot bemorespecific` - please note that the bot will no longer give any visible indication that the user is alerted or not
