### ISSUE TITLE
"Be more specific" message is too sensitive

### ISSUE THREAD

**Issue by nimbusparis** [hangoutsbot/hangoutsbot#208]
When I mention a user like "@Eu", the bot will send me the standard message "Be More specific" for all user which nick had the 2 chars:
"France Resistance
7 users would be mentioned with "@Eu"! Be more specific. List of matching users:
Matthieu W
Eu J
Matthieu A
G Bleue
Matthieu J
S Deux"

That is ridiculous...

**Comment by endofline** [comment]
In the event that the message continues to be intrusive, `/bot bemorespecific` on framework 2.5 can be used to turn off this specific notification indefinitely. Please reopen this issue for any additional comments/suggestions on the matching algorithm implemented.

**Comment by endofline** [comment]
Manually closing this issue - please reopen if any further issues arise on this matter
