### ISSUE TITLE
[framework][new bots] base config.json

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#216]
Currently the config.json file has some plugin configs, some deprecated configs and some are missing completely. While it'll be easy to update the config.json file, I'm not sure which path to take:

1. Remove all plugin-based configs and leave it up to the admin to add them in where necessary (very succinct config.json file, bottom-up approach to building the bot)
2. Add all plugin-based configs and leave it up to the admin to remove what's not necessary (long and bulky config.json file, but allows us to by default load all plugins and let the admin play with everything upon first start of the bot, and choose what to keep)
3. Add in what we perceive to be the most commonly used plugin configs. (Medium-sized config.json, manageable for admins, but we would have to decide what the default plugins should be)

Personally I'm for 1 (or 3 if we're smart about it), but that's just my style to start from the basics and add features one by one so that I understand how each works and by the time I'm done the bot is exactly what I wanted. It'd also be more secure (if a plugin is found to have a vulnerability, it wouldn't be loading by default for everybody).

Thoughts? I'll leave this open for a few days

**Comment by endofline** [comment]
Personally for me, either a baseline plugin configuration consisting of: default, starter, eastereggs, chance; or ALL plugins - either is fine. We also need to review the wiki and ensure that the whatever missing/incomplete config examples are added/updated.

**Comment by 00svbeon** [comment]
Maybe a config page at the wiki, what you can add  to your config file

**Comment by nylonee** [comment]
I like the idea of the config page on the wiki. That way we can slim down the config.json to it's essential baseline configuration.

**Comment by endofline** [comment]
Removing this from 2.5 blockers since it can be completed independently - the individual plugin pages should contain config example fragments. If any examples are missing, please update them.

**Comment by nylonee** [comment]
config.json has been slimmed down. Closing this
