### ISSUE TITLE
/bot echo will crash if memory.json doesn't have 'conv_data'

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#221]
Just pushed a fix for this issue at 126c2a475def2928771d827417131a31dcf2fbbe, raising this for documentation purposes

**Comment by nylonee** [comment]
Also `/bot echo` and `/bot echoparsed` will now check for "convmem" too. It will still check "conv_data" for legacy purposes, not sure if it's safe to remove that.

**Comment by endofline** [comment]
This code is going to change again due to #222

**Comment by endofline** [comment]
The default plugin in 2.4.3 is expected to be not backward-compatible with any version of the bot older than 2.4.3 - this is due to #218 and the subsequent #235 PR
