### ISSUE TITLE
reprocessor duplicates messages in syncrooms

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#226]
Using the slack plugin or API plugin to send messages to a syncroom will cause them to be duplicated.

Here's a breakdown from logs of how the bot's doing this:
1. Receive POST, sending message to one conversation
2. Syncroom plugin forwards that message to all attached conversations
3. Bot reads own message from conversation, is_self is suppressed so bot handles message
4. Bot sends message to all syncrooms (appending the bot's name as per syncroom style)

I can't think of an easy solution to this without lifting reprocessor support for the API plugin and the slack plugin. Maybe syncrooms can strip the context when forwarding between rooms?

**Comment by endofline** [comment]
the fix (hopefully) also prevents slack from repeating its own messages, derived from here: https://github.com/hangoutsbot/hangoutsbot/commit/29906c4513309614db9b73612373239edf33dbdf#diff-09d3d9453cd9f07a6a46095450b3d6b3R231
