### ISSUE TITLE
convtools: refresh sent "obsolete" notification to wrong conversation

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#227]
when you do /bot refresh conversation xxxxx code
You get a valid notification in new Hangout:
bot.send_html_to_conversation(new_conversation_id, _("<i>group refreshed</i><br />"))

but you get a "obsolete" notification in hangout you issued command, instead of getting it in hangout you just refreshed:
bot.send_html_to_conversation(event.conv_id, _("<b>group obsoleted</b>"))

**Comment by endofline** [comment]
While we're at it, do you actually need a notification? I can think of situations where a manual notice that the hangout is obsolete is probably better ;P especially when you're trying to exclude certain... kinds of people ;)

**Comment by FrNico** [comment]
maybe add an arg "quiet" for no notification? :)
but yeah... no notification is fine also!

**Comment by gurumadmat** [comment]
Argument would be best. 
And a more descriptive message.

**Comment by nylonee** [comment]
I decided to keep "group obsoleted" in the hangout where the command was issued (for confirmation of success), as well as include a "group obsoleted" message in the hangout that's getting obsoleted. The latter can be toggled using the 'quietly' parameter.
