### ISSUE TITLE
Deprecate hooks, remove from bot

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#231]
It might be time to remove the hooks functionality from the bot (after having moved all hooks to plugins maybe?)

Hook functionality was superseded by plugins in early May, we can print an error to log if somebody's config.json still has hook functionality (My guess though is that it would trigger for a lot of people, since the default config.json had a hook).

**Comment by endofline** [comment]
Already deprecated in docs, but devs will be devs ;p 

Warnings are good for escalation. Removal will take more time and a few more versions.
