### ISSUE TITLE
/bot convecho formatting issues

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#236]
When you put this link in convecho:
https://www.details.php?id=1033

it will echo to:
https://www.details.php?id = 1033

putting a space in the equals sign

**Comment by endofline** [comment]
A workaround for other special characters is to escape the character with a backslash `\` as per the posix-style lexer.

**Comment by endofline** [comment]
[Wiki section updated on POSIX-compliance](https://github.com/hangoutsbot/hangoutsbot/wiki/Default-Commands-Plugin#convid-family)
