### ISSUE TITLE
[bug] errorneous "pem file possibly missing or broken" on sink when address is in use

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#238]
When deploying a sink, the bot will attempt to use a port as specified. If the port is already in use the error handling involves trying to close the socket. However the socket doesn't exist to begin with, and the bot throws an error.

**Comment by endofline** [comment]
Can you indicate which part of the code does this? And is this old sink (pre-2.4) or new sink (post-2.4)?

**Comment by nylonee** [comment]
Error using slack.py:
```
listener: slack : pem file possibly missing or broken (== '~/server.pem')
Exception in thread Thread-7:
Traceback (most recent call last):
  File "~/hangupsbot/plugins/slack.py", line 91, in start_listening
    httpd = HTTPServer((name, port), webhook)
  File "/usr/lib/python3.4/socketserver.py", line 429, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/http/server.py", line 133, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.4/socketserver.py", line 440, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "~/hangupsbot/plugins/slack.py", line 105, in start_listening
    httpd.socket.close()
UnboundLocalError: local variable 'httpd' referenced before assignment
```

Error using api.py
```
listener: api : pem file possibly missing or broken (== '/root/server.pem')
Exception in thread Thread-6:
Traceback (most recent call last):
  File "~/hangupsbot/plugins/api.py", line 87, in start_listening
    httpd = HTTPServer((name, port), webhook)
  File "/usr/lib/python3.4/socketserver.py", line 429, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/http/server.py", line 133, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.4/socketserver.py", line 440, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "~/hangupsbot/plugins/api.py", line 101, in start_listening
    httpd.socket.close()
UnboundLocalError: local variable 'httpd' referenced before assignment
```

The error is pretty easy to replicate, by running two instances of a bot that's using a sink on the same server.

**Comment by endofline** [comment]
These are old sinks, they don't use the newer pattern which actually does handle port conflicts: https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/sinks/__init__.py#L97 - it would be better to rewrite these sinks following the [new pattern](https://github.com/hangoutsbot/hangoutsbot/wiki/Sinks-(2.4-and-above)).

**Comment by endofline** [comment]
Oh wait I stand corrected on the handler, the error occurs in the try block before the in-use address. OSError. In your logs it indicates the pem file is broken, not that the port is in use. Can you clarify whether the actual error is a missing pem or an in-use port?

**Comment by nylonee** [comment]
I'm not sure what's causing the missing pem error, as the pem file is there and my bot's using it... I'm guessing if one instance of the bot is using the pem file, then the other instance can't access it?

**Comment by endofline** [comment]
Probably not, will investigate further

**Comment by endofline** [comment]
Looks like a Python 3 gotcha: there is [very little difference between IOError and OSError](http://stackoverflow.com/q/29347790) - this may require reworking the exception handlers.

**Comment by endofline** [comment]
A lot of plugins need to be rewritten for this bugfix. Use the API plugin as an example of the rewrite (https://github.com/hangoutsbot/hangoutsbot/commit/c3ea1fc6f0b707d534ee3c3e2ff56277e539590e)

Since the older patterns continue to work (albeit with inaccurate errors), this will not block release 2.5.

**Comment by endofline** [comment]
Change tested and confirmed in #300
