### ISSUE TITLE
[plugin] autoreply: choose reply randomly if list

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#239]
Could the autoreply plugin choose from a list of potential replies which reply to send (randomly) if more than one is specified? The config file is already set up in such a format that it could easily be extended:

Config snippet removed by @endofline: `---8<--- snip! ---8<---` (see below for actual format)

**Comment by endofline** [comment]
It would be easier in this format:
```
"autoreplies": [
  [
    [
      "hi bot", "hello bot"
    ], 
    ["hello world!", "hi world!"]
  ]
]
```

**Comment by endofline** [comment]
wiki updated: https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin#configuration

will edit issue body to prevent confusion over configuration method

**Comment by endofline** [comment]
Accounted for in #217

**Comment by endofline** [comment]
Manually closing after #217
