### ISSUE TITLE
List users in a chat by last message sent, and frequency of messages

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#24]
Useful for finding inactive members in a chat

**Comment by endofline** [comment]
The chatlogger would probably be a good reference to start, just make another optional sink that can be loaded as needed by various users: https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/hooks/chatlogger/writer.py

**Comment by nylonee** [comment]
Since hooks are now obsolete, I think my approach will be to append a 'last spoken' to memory for each user. The frequency of messages is a bit more complex though. Should we sort by message/day or week? Or total messages? Can an admin reset the counter?

I will think through this a bit more

**Comment by endofline** [comment]
You can use `config.py` to generate a secondary `memory.json`-like file if you wish to separate the functionality away from memory. This would be recommended if you are storing long-term statistics, especially on a week-by-week tally.

**Comment by nylonee** [comment]
I'll be taking another look at this over the next few days, as now memory.json is storing large amounts of data, I don't feel as guilty writing a plugin to make memory.json heavier.

**Comment by endofline** [comment]
As mentioned earlier, you really ought to store non-essential statistics in a separate file. The current memory.json storage is essential to the bot's functionality. I would still recommend using a third statistic file for this purpose that is initialised independently by a plugin.
