### ISSUE TITLE
[first install] doesn't recognize admin / unable to configure first admin

### ISSUE THREAD

**Issue by DigitalOSH** [hangoutsbot/hangoutsbot#246]
I've changed the first line of config.json to "admins": ["UgyTpJXXXXXXXXAaABAQ", "USER2_ID"], with my chat GUID but it still doesn't recognize me as admin.

**Comment by NeoEGY** [comment]
try clearing config.json of admins and /bot iamspartacus

**Comment by endofline** [comment]
@digitalosh that example you provided looks like a group id, it should be
your userid

**Comment by DigitalOSH** [comment]
You're right. Changed that. However when I do /bot users it still says can't do that. When I do iamspartacus he returns No! I am spartacus!

**Comment by endofline** [comment]
`/bot iamspartacus` will only work if there are no admins configured - it's intended to jumpstart new bots which has blank configs. So try clearing the admins key and leave an empty list, restart the bot and execute the command again

**Comment by DigitalOSH** [comment]
Just did that, same result. To confirm, it should look like this?

{
  "admins": [
],

**Comment by endofline** [comment]
Yes that is correct. I will test this out on my localbot.

**Comment by endofline** [comment]
Works fine on the testbot - are you modifying the correct copy of config.json? The file that comes with the repository is only a sample file that is automatically copied by the bot on first run. The actual file is located around ` /<system user name>/.local/share/hangupsbot/config.json`

**Comment by DigitalOSH** [comment]
I was editing the sample. Thanks. Could we consider commenting the sample to show as just that?

**Comment by endofline** [comment]
[Not sure whether the python 3 json library will accept comments](http://stackoverflow.com/a/4183018) inside the reference file since it follows a strict interpretation of json. It will be investigated. We may make the [notice in the INSTALL](https://github.com/hangoutsbot/hangoutsbot/blob/master/INSTALL.md#additional-configuration) file more prominent though.
