### ISSUE TITLE
what to do with (old) hubot integration?

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#249]
Either:
* Re-implement as a plugin
* Remove entirely from bot

Related to #231

**Comment by nylonee** [comment]
I vote a plugin re-implementation

**Comment by endofline** [comment]
Turns out the chat_framework (#201) , chatbridge (#209), and then webbridge (#240) had its use after all - hubot integration reimplemented as a straightforward plugin.

Wiki updated:
* https://github.com/hangoutsbot/hangoutsbot/wiki/Authoring-Bot-Extensions
* https://github.com/hangoutsbot/hangoutsbot/wiki/Hubot-Integration

**Comment by endofline** [comment]
Accounted for in staging for #248

**Comment by endofline** [comment]
Transferred my forked copy of hubot-web to https://github.com/hangoutsbot/hubot-web
