### ISSUE TITLE
[regression] /bot echo is missing support to send to other convid

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#253]
During the implementation of convid-functions, I apparently [missed re-implementing](https://github.com/hangoutsbot/hangoutsbot/commit/7ea2deeda1032b0ba3bba9468f332c9b9afd1c97#diff-991ef933fa0e3a66c869ba45f18e9cf3L53) the *send to arbitrary convid* functionality of `/bot echo`

[Wiki has been updated](https://github.com/hangoutsbot/hangoutsbot/wiki/Default-Commands-Plugin#user-commands) ~~to reflect the lack of this feature.~~ (fixed that, see below)

**Comment by FrNico** [comment]
We currently have "convecho" working fine. Do we need to keep both echo and convecho then?

**Comment by endofline** [comment]
Hmmm. I'm just fixing it since some devs might be using it already. I'll
add the feature back (since I really did miss it) but add a recommendation
to use convfilter instead.

**Comment by endofline** [comment]
An additional security fix has been added to the implementation, only admins can send messages to *other* conversations
