### ISSUE TITLE
convecho disregard history on/off status of a conversation

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#254]
When using convecho on a conversation without history, bot still publish message with history on

**Comment by endofline** [comment]
This might be the result of forgotten conversations, as the history check still relies on the hangups conversation list, and not the permanent conversation memory - there isn't any way to tell now, as the exception handling in that portion of the framework simply `pass`-es the exception without logging it. I will research adding the flag into convmem

**Comment by endofline** [comment]
The fix adds a history flag into conversation memory and will be refreshed/created on bot startup - you may need to refresh the conversation memory with an event before the history flag correctly reflects the state of a conversation, especially if the conversation is not very active. A toggle of the history settings appears to suffice for this purpose.
