### ISSUE TITLE
[support] how to automatically post every x hours

### ISSUE THREAD

**Issue by Galtwise** [hangoutsbot/hangoutsbot#260]
Not sure if this counts as an issue. I'm trying to find a way to automatically post a 'Message of the Day' in a specific chat every few hours. I have a monitor script that checks if it's time to repost already, but I don't know how to automatically post. Any ideas?

**Comment by endofline** [comment]
If the monitor script is external, you can use the [API plugin](https://github.com/hangoutsbot/hangoutsbot/wiki/API-Plugin) or a [sink](https://github.com/hangoutsbot/hangoutsbot/wiki/Sinks) to receive external POSTs. 

Alternatively you can use the new 2.5 [thread manager](https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/threadmanager.py) to start a thread inside a custom plugin that calls `bot.send_html_to_conversation`.

**Comment by DigitalOSH** [comment]
Is there any further documentation on thread manager? It might be the
solution but I don't know where to start

**Comment by endofline** [comment]
Some guidance can be derived from the new [botalive plugin] (https://github.com/hangoutsbot/hangoutsbot/commit/e95ce0c6173951469ed2f349994b30a8b9f2b901) - take note of the `threadmanager` used in the `_initialise()` function, and the infinite loop in the target function `_periodic_watermark_update` - in this case, the `threadmanager` executes the function (which runs continuously in an infinite loop) which in turns executes the task of updating the read "watermark" of a specific conversation. In your scenario, you would be [sending messages](https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Sending-Messages) instead,

Note: The `watermark_updater` class is simply a helper object to facilitate sequential watermark update. In the plugin source code referenced above, you could replace lines 38, 39, 46 and 47 with `bot.send_html_to_conversation(conv_id, "test")` and the bot will send the message "test" to the designated conversations, instead of updating the watermarks as before.

**Comment by DigitalOSH** [comment]
I decided to try the sinks method. I correctly configured config.json with:
  {
      "certfile": "<server name>/server.pem",
      "module": "sinks.generic.SimpleMessagePoster",
      "name": "127.0.0.1",
      "port": 9002
    }

server.pem is set up and shows a private key as well as a certificate

when I run:
python3 tests/base-send.py https://127.0.0.1:9002/<target conversation id> "Hello World!"

I get: 

```Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/base-send.py", line 29, in <module>
    r = requests.post(args.url, data = json.dumps(payload), headers = headers, verify=False)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
```

What am I missing here?

**Comment by endofline** [comment]
You are missing the [conversation id](https://github.com/hangoutsbot/hangoutsbot/wiki/Sinks-(2.4-and-above)#base-sendpy) at the end of your URL. 

On the other hand, I'm not sure about the rest of your provided error log, which is indicating that there is no open network socket at all. This is likely not a bot issue, you will have to check whether the designated port number 9002 (as per your example config) is indeed open and receiving connections.

The usual suspects apply in this scenario: Re-check your server pem, and pay close attention to the console output on bot startup - if there are any errors, they should be displayed when the bot runs. Also determine if anything else is running on that port number and conflicting with the bot.

**Comment by DigitalOSH** [comment]
Sorry, I deleted the convid for privacy but forgot to put in a placeholder. I have no firewall rules set up on this server and am running the command on the local machine so I don't think the port is blocked... however I did get an error on startup as you said which reads

```_start_sinks(): ['sinks', 'generic', 'SimpleMessagePoster']
SINK: sinks.generic : 127.0.0.1:9002 : [Errno 2] No such file or directory```

so I changed json.rpc module to ```"module": "sinks.generic.simpledemo",```

which gave

```Cannot identify sink: sinks.generic simpledemo```

Not sure what I'm doing wrong here. Also, is this the best place to troubleshoot?

**Comment by endofline** [comment]
It would be good if you can specify the version that you are running: the log you provided indicates your version is possibly outdated (retrieved around mid-July). I would certainly recommend upgrading to latest master at the very least - no data loss will result from an upgrade. Note that we update fairly often: 2-4 weeks for every new master release, and anywhere from daily to weekly in the staging branch.

 There are two possible values, either `sinks.generic.SimpleMessagePoster` or the deprecated `sinks.generic.simpledemo.webhookReceiver` - the latter setting will probably work with your current version although it is considered legacy code and will probably be removed in a future release.

The other issue that might be causing your "No such file or directory" error is a missing or inaccessible .pem file - if your previous config example is indeed your actual configuration, then the .pem file should be in the root of your file system. You must provide the full absolute path to the file. If its the .pem file that is missing/inacessible - then the deprecated module will also fail to start with a similar error.

**Comment by DigitalOSH** [comment]
I am running version 2.5 according to the /bot version command however I assume this is not accurate enough. I'll update

**Comment by endofline** [comment]
You need to `git clone` the repo, presumably you just downloaded the zip file and extracted it. You can simply repeat the process of downloading the latest release zip and overwriting the older files in the process if you are reluctant to use git.

**Comment by endofline** [comment]
On the other hand, you can try and check what's wrong with the .pem file first before messing about with git and the new version - as the problem seems to be associated with that file (or lack thereof) based on my local testing ;P

**Comment by DigitalOSH** [comment]
Is there a place I can send you my server.pem file to view? I'd rather not post the contents here

**Comment by endofline** [comment]
No need to send it. A properly-generated .pem file - see [instructions for generating a self-signed certificate](https://github.com/hangoutsbot/hangoutsbot/wiki/Sinks-(2.4-and-above)#configuring-sinks) - resembles the following:

```
-----BEGIN PRIVATE KEY-----
<lines and lines of random-looking chars>
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
<lines and lines of random-looking chars>
-----END CERTIFICATE-----
```

If you are still receiving `[Errno 2] No such file or directory` with your bot, I'm pretty sure that that the path specified in the `certfile` key is incorrect - please ensure that your `.pem` file does indeed exist at the location `/server.pem`

**Comment by endofline** [comment]
The latest [staging branch](https://github.com/hangoutsbot/hangoutsbot/tree/staging) contains a number of enhancements that may be applicable for troubleshooting your issue - the zip package can be extracted into a separate directory and executed independently of your current master copy. This branch will output more informative errors based on the nature of your problem, up to detecting corrupt/unloadable .pem files based on recent work committed in #305 and #306
