### ISSUE TITLE
forwarding plugin is missing documentation

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#261]
#230 reimplements the forwarding plugin and moves it from a legacy plugin to a standard plugin, but is presently missing documentation in the [plugin list](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-List)

**Comment by nylonee** [comment]
Added [documentation](https://github.com/hangoutsbot/hangoutsbot/wiki/Forwarding-Plugin). Closing #261
