### ISSUE TITLE
inactive botkeepers check/purge

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#266]
On large setup, we might face a situation where people got botkeeper rights, but are not longer really active in conversation, left project, etc...
I would see a use to have a plugin to verify that botkeepers are still active.
Example:
 - /bot checkbotadd [init | status]
"init" should ask confirmation, and will send a private message in 1-to-1 hangouts to all botkeepers asking something like that: "Howdy, you are one of my botkeepers, please let me know if you still need my services by replying any message in that conversation".
"status" should remind when last "init" command was issued, and give list of all botkeepers who have not yet replying any message in 1-to-1 bot hangout

Also, /bot removebotadd should check if a botkeeper is the only botkeeper in a conversation, and warn admin that bot will leave blablabla conversation, and then ask confirmation for removebotadd command in case removing botkeeper status is making bot leave a conversation.

**Comment by endofline** [comment]
This seems like very specific high-level use-cases. Will look at it again after the #256 is merged into staging. I'm still not clear about `checkbotadd` command - presently we don't have mechanism for tracking questions and responses yet, so its probably something that has to be added for this to work properly as well.
