### ISSUE TITLE
lookup plugin: per conversation spreadsheet config

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#267]
on large bot setup, might be useful to set up a spreadsheet per conversation, overiding default spreadsheet set in global config (or even sometimes, you don't set one in global config, but just one in a specific conversation for security reason).

one dev helped me some time ago to set up that, and I have a modified version of lookup.py but he was not familiar with github use (me neither) to push it...
if somebody wants to do a PR for that, here is the version I'm using:
http://frnico.free.fr/bot/lookup.py

It adds:
/bot setsheet <URL>
 => to set spreadsheet URL
/bot getsheet
 => to get current spreadsheet URL

It also add use of super cookie to login, limiting then search into first 100 rows... cf. : 
https://github.com/hangoutsbot/hangoutsbot/issues/104

So I guess a better use will be to have that as a parameter:
/bot setsheet <URL> [auth|no-auth]
for example, toggling use of super-cookie or not, as a workaround for now.

**Comment by nylonee** [comment]
Spreadsheets can now be set in the config on a conversation level, I will consider the other commands suggested above too.
