### ISSUE TITLE
whereami improvement

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#277]
Allow a user to get list of all conversations he has where bot is present, reply in 1-to-1 conv only.

Example:
/bot whereami [all]
You are in:
blablabla, conv_id = xxxxxx
bla1234, conv_id = yyyyyy

**Comment by FrNico** [comment]
can be used for some plugins, for example:
https://github.com/hangoutsbot/hangoutsbot/issues/278

**Comment by endofline** [comment]
Staging currently has an extra parameter for `convfilter` - the `chat_id:` filter, although its a bit unwieldy to use at the moment:
```
/bot convfilter chat_id:<your chat id>
```

The above command will list all conversations your user is participating in. It can also be used 
  to locate any user that is known to the bot.
