### ISSUE TITLE
[support] spaces when convecho'ing non-latin characters

### ISSUE THREAD

**Issue by topcu** [hangoutsbot/hangoutsbot#279]
Normal Case:
Command:
/bot echo çağrı test
Result:
 çağrı test

When Using convecho:
Command:
/bot convecho CONV_ID çağrı test
Result:
 ça ğ r ı test
(notice the white spaces)

**Comment by endofline** [comment]
You will need to enclose the string with double-quotes when using `convecho`, since its a low-level command with minimal pre-processing e.g.

```
/bot convecho <CONV_ID> "çağrı test"
```

It is noted in the [docs](https://github.com/hangoutsbot/hangoutsbot/wiki/Default-Commands-Plugin#convid-family)

**Comment by endofline** [comment]
Manually closing this - please reopen if there are any further issues arising from the above usage
