### ISSUE TITLE
[support] config.json + multiple bots on a single user

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#283]
Hi,

I have 3 questions that I have not been able to figure out for myself.
1) How do I configure the bot with certain functions per conversation? I want to turn off commands in one conversation and cannot figure out how to do it. The only instructions I have found stop the bot from running when I reload. 
2) How can I run multiple bots? I cannot seem to get multiple running due to only having 1 config file for my user. 
3) How can I make it so only certain users can send any commands to the bot and it ignores all users?

Any help is greatly appreciated.

**Comment by endofline** [comment]
Q1 and Q3 might be related to the config key [commands_enabled]
  (https://github.com/hangoutsbot/hangoutsbot/wiki/Configuration#commands_enabled)

Q2: you need to manually set multiple memory, config and cookie paths as indicated in the 
  [usage instruction](https://github.com/hangoutsbot/hangoutsbot#running-the-bot)

The bot will generally output an error message if it crashes - in the case of bad `config.json` it would actually output the line number and character where it broke with the message "malformed json" -  Python3 has fairly strict json parsing so you need to make sure you use double-quotes and commas in the right places.

**Comment by bmbermn** [comment]
endofline, I appreciate the quick response. In my config.json I have specified   
"conversations": {
    "Ugx3mw755X3BoBk_siB4AaABAQ": {
      "commands_enabled": false
    }
  },
however I can still run commands in that chat ( I have tried bot chat and ping ). Any thoughts as to why?

I am still working on checking out the other part.

**Comment by endofline** [comment]
If you are an admin, you will always bypass [`"commands_enabled": false`]
  (https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/handlers.py#L127)

**Comment by bmbermn** [comment]
Awesome help, now I understand
