### ISSUE TITLE
[plugin] per-user blocking of auto-replies

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#284]
I would like the bot to recognize any time a certain user says anything and provide an auto reply if possible. Additionally I would also like to find the ability for the bot to ignore certain users. Are either of these possible?  Thanks in advance

**Comment by endofline** [comment]
Unfortunately, per-user autoreplies are not available at the moment, although it might be possible once #256 and #121 is implemented. You can still do a customised [per-conversation](https://github.com/hangoutsbot/hangoutsbot/wiki/Configuration#conversations) autoreplies though.

**Comment by endofline** [comment]
Wiki updated: 
* https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin#tag-support
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Tags-List#autoreplies-disable
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Tags-List#autoreplies-enable

**Comment by bmbermn** [comment]
I dont think I follow, do I tell the bot "/bot autoreplies-disable
[userid]"?

**Comment by endofline** [comment]
This feature has not been added into the main framework yet, you will have to wait until #256 is merged into staging, and #248 is merged into master for the next release.

**Comment by endofline** [comment]
The latest version of the bot has been merged to master. In the latest version, you should now be able to use the following commands to selectively toggle autoreplies on/off for a specific `<user id>`:
```
/oto tagset user <user id> autoreplies-enable
/oto tagset user <user id> autoreplies-disable
```
These settings will override whatever global or per-conversation settings are set.

To remove the tags, you can use:
```
/oto tagdel user <user id> autoreplies-enable
/oto tagdel user <user id> autoreplies-disable
```

Further information can be found on the wiki entry for the [**autoreply** plugin]
(https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin#tag-support) 

To search for a user id, use: `/bot user <name fragment>`

The tagging mechanism is a new feature and is still relatively primitive, we expect it to become more flexible and user-friendly as its use grows.

**Comment by bmbermn** [comment]
Can you advise the best way to update the bot? I am still fairly new in
linux and using CentOS.

**Comment by endofline** [comment]
If you have `git clone` the bot, then the simplest way would be to issue the command `git pull origin master` to get the latest code, otherwise you would have to manually download the zip file and overwrite the files that you have. Since the bot stores its `config.json` and `memory.json` elsewhere, this should not affect your configuration.
