### ISSUE TITLE
[dev] subscribe erroneously grabs global keywords from memory

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#286]
https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/plugins/subscribe.py#L48 - if global memory `keywords` is set (`bot.memory["keywords"]`), any user who doesn't have keywords defined will use this key instead, leading to odd behaviour of the subscribe plugin, such as users receiving notifications of words they haven't subscribed to; in conversations that they aren't participating in

**Comment by Riptides** [comment]
It also occurs when a user does have keywords defined under user memory, but the only alerts they got from conversations they weren't in where from words stored in the global bot.memory['keywords']

**Comment by endofline** [comment]
Added to staging for next release in #248
