### ISSUE TITLE
[plugin][idea][humor] tell me a joke, "yo mama"

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#292]
It would be hilarious if we could have a plugin for yo mama jokes or other types of jokes, kinda like siri "tell me a joke"

**Comment by endofline** [comment]
We invite other developers to contribute to the plugin base and/or post download links to their own plugins. Also, if you are interested and like to try out programming in python3, there is plentiful documentation to get started with [plugin authoring](https://github.com/hangoutsbot/hangoutsbot/wiki/Authoring-Bot-Extensions) for the bot :smile:

**Comment by j16sdiz** [comment]
YoMa: http://api.yomomma.info/
