### ISSUE TITLE
API.py plugin no longer working

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#295]
Pulling the latest master, the api plugin is no longer working when I attempt to send a POST JSON (trying both the test python script api-send.py and using cURL). I can't seem to identify the error.

This is all that shows in logs:
```
APIRequestHandler: receiving POST...
22:11:14 INFO root: APIRequestHandler - 220.240.202.127 "POST / HTTP/1.1" 200 -
APIRequestHandler: connection closed
APIRequestHandler: incoming: / {} 95 bytes
```

~~Reverting to 40e1ac9 fixes the problem~~ misleading, see below -- @endofline

**Comment by endofline** [comment]
Fixed and accounted for in #291 

Wiki updated: 
https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Sending-Messages#message-user-via-1-to-1

Also take note of regression in #297 for compatibility purposes
