### ISSUE TITLE
[dev] manually toggle otr per message when sending

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#299]
It looks like there isn't an easy way for plugin devs to manually toggle the otr status for plugins (Granted, it's rare enough a case). However it's worth raising this issue to discuss whether we should reintroduce a parameter into the bot's message sending function.

**Comment by Riptides** [comment]
I would definitely like to see this implemented. Going to try changing the bot's memory before sending a message and then changing it back after; however, that seems a bit janky.

**Comment by endofline** [comment]
I'm considering using the `context` parameter:
```python
context["history"] = True # or False

bot.send_message_parsed(conv_id, "message", context)
```

**Comment by endofline** [comment]
Incidentally, I don't think there has ever been a way to actually send OTR chat - so "reintroduce" is kind of a misnomer ;P If there are no further comments, I will merge this change to staging shortly.

**Comment by endofline** [comment]
Wiki updated:
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Sending-Messages#the-context-parameter

**Comment by endofline** [comment]
Confirmed in #300
