### ISSUE TITLE
[bug][plugin] bot will consider itself a botkeeper

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#303]
If the bot is an admin as defined by the config.json file (eg. for running its own commands through the api.py plugin), then the bot will consider itself a botkeeper in [restrictedadd.py](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/restrictedadd.py#L72), thus won't remove itself from conversations that don't have any botkeepers.

**Comment by j16sdiz** [comment]
Why would a bot be admin of itself?

**Comment by endofline** [comment]
@j16sdiz the API plugin runs at whatever level the bot is set, so bot accounts get added as am admin. 

The long-term fix for this would probably be a way to raise bot commands without needing an actual event object

**Comment by endofline** [comment]
Confirmed added to PR body in #300
