### ISSUE TITLE
[bug][plugins] namelock.topic / convid.convrename interaction

### ISSUE THREAD

**Issue by gurumadmat** [hangoutsbot/hangoutsbot#304]
Topic locks the hangout title but when you rename the ho afterwards with convrename the lock with previous title is still remembered. 

So when a user tries to change it again the old ho title is used by bot.

**Comment by endofline** [comment]
The bot will now automatically updated the locked topic if a configured admin or the bot itself changes the title of a conversation

**Comment by endofline** [comment]
Summary verified and added to #300
