### ISSUE TITLE
plugin tldr: improv, selective clearing

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#310]
improvement idea for tldr plugin: be able to clear just one entry.

/bot tldr clear [<id>]

if <id> not specified, clear all, if <id> specified only clear entry #<id>

**Comment by endofline** [comment]
Wiki updated: https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-List

**Comment by endofline** [comment]
Confirmed and added to next minor version (re: #328)
