### ISSUE TITLE
autoreplies do not work inside "conversations" tag

### ISSUE THREAD

**Issue by neutron666** [hangoutsbot/hangoutsbot#312]
Whatever i try, i got a valid json file, bot starts, but autoreplies do not work inside configured conversation's. Also a "/bot autoreply" only lists all autoreplies OUTSIDE the conversation-tags, but not those configured inside the conversation tags.

Example:

```
"conversations": {
  "aaaaaaaaaaaaaaaaaaaaaaaaaa": {
    "autoreplies_enabled": true,
    "autoreplies": [
      [["ichbinderbatman", "ich bin der batman"], "NEIN! ICH bin der Batman!" ],
      [["kt", "kilothomas", "kilo thomas"], "0,1 kT = 100 XMP." ]
    ]
  }
},
```

Edit - code formatted, and removed convid (it looks good though - correct amount of letters) - @endofline

**Comment by endofline** [comment]
Doesn't seem to be be anything wrong with your configuration as far as I can tell. I actually copied/pasted that into my own conversation configuration to test and got the correct autoreplies.

Are you editing the correct `config.json` file? You can get the bot to tell you where the actual file is by using the command: `/bot files`

Also which `/bot version` are you running?

On version 2.6 and higher, you should also check whether you have tagged a user with [`autoreplies-disable`](https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin#tag-support) as this will globally switch off auto-replies everywhere for a user. If you have not done any tagging before then this probably won't be the issue, as users need to be explicitly tagged.

Also, we are aware of the limited administrator command function for autoreplies, and will probably add per-conversation configuration in the near future.

**Comment by neutron666** [comment]
Hi there. Strange..first of all, i'm using version 2.6.1 of the bot. I'm pretty sure i use the right config because every other change i make to this config is reflected and working perfectly after a restart from the bot. I did not do any tagging, so i think this is not the problem. I'm really a bit confused right now why this works out of the box for you and doesn't do anything for me. Anything else i could try ?

**Comment by endofline** [comment]
Hmm, that's very odd. In any event, I checked out an entirely fresh new copy of the bot locally and made it generate a new config file, then added the simplest per-conversation configuration for autoreplies I could think of:
```
  ...,
  "conversations": {
    "UgXXXXXXXXXXXXXXXXXXXXABAQ": {
      "autoreplies_enabled": true,
      "autoreplies": [
        [["*"], "It works!"]
      ]
    }
  },
 ...
```

I can verify this works on a freshly-configured bot - it should auto-reply to everything you say to the bot in that specific conversation. The only thing else I can think of is that the conversation id is somehow wrong - perhaps you better double-check/triple-check that you are chatting in the correct conversation with `/bot whereami`

**Comment by neutron666** [comment]
Nope :( checked everything again, globally works, per conversation, no-go. I just took your snippet, changed the conv_id to the one i got from "/bot whereami" and nothing..

Also sending a "/bot autoreply" say "Autoreply config: None". *sigh*

I don't get it...

**Comment by endofline** [comment]
Use the following command substituting XXXXXX with your conversation id from `/bot whereami`:
```
/bot config set conversations XXXXXX { "autoreplies_enabled":true, "autoreplies": [[["*"], "Meh"]] }
```

Then issue the following command:
```
/bot reload
```

**Comment by neutron666** [comment]
That did it and i now see where i had an error. I had another "conversations" directive in my config for the spreadsheet stuff (lookup) and that doesn't seem to work, but does not give any errors. After i issued your command the bot wrote the config itself and combined those two into one "conversations" directive.

Thank you very much!

**Comment by endofline** [comment]
Good to hear :) That would be a constraint of the json parser - it won't know what to do if multiple identical keys exist - most likely overwrite each other actually.

**Comment by endofline** [comment]
I'm closing this, since this issue appears to be resolved already :)
