### ISSUE TITLE
tagsetuser is not very intuitive

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#316]
I want to allow all users of a particular hangout to use a particular set of tagged (admin) commands.

The proper way to do this seems to be

/bot tagset convuser <convid>|\* <tag>

This is rather counter-intuitive, given that we also have

/bot tagset conv <convid> <tag>

What is the later supposed to do? Why would I tag a conversation but not all the users inside?

The difference is:

```
    "Ugzmp1WmtFhhKpT5uZV4AaABAQ": {
      "tags": [
          "intel-user"
      ]
    }
```

vs

```
    "Ugzmp1WmtFhhKpT5uZV4AaABAQ": {
      "tags": [
        "*": [
          "intel-user"
        ]
      ]
    }
```

**Comment by endofline** [comment]
I agree these basic commands are confusing, but the actual distinction between a **conversation tag** and a **per-conversation user-override** is required for the scenarios identified in #121 and in other discussions:
* some developers want to tag an entire conversation regardless of users composition - so a conversation tag would be useful for `/bot convfilter tag:xyz` would filter all conversations that have the tag `xyz`
* on the other hand, some developers want to tag certain users globally or tag them only when they are in a specific conversation - hence the `convuser` type implementation

I've tried to clarify this in the [Tag Scopes](https://github.com/hangoutsbot/hangoutsbot/wiki/Users-and-Conversations-Tagging#tag-scopes) part of the documentation

One way of making this more intuitive is to add simplified tagging commands on top of the current base set for botmins to use. I'm open to suggestions or code request for this.
