### ISSUE TITLE
logging, moving forward

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#321]
Currently hangupsbot writes to a log file and to stdout.  This should be configurable on a per-installation
basis.

For example, I'd like it to either write directly to systemd's journal (optimal) or write non-timestamped
entries to stdout (systemd takes the stdout and stuffs it into the journal), and not write the .log file at all.

This is something pretty trivial to change in python logging by using the logging dictconfig method:

https://docs.python.org/3/library/logging.config.html

Given that we need to get logging up before we get access to memory, my thoughts are to look
for a separate config file, logconf.json.  If it doesn't exist, configure things exactly as they are done
now.  If it does exist, load that file and configure logging from there.

Thoughts/dislikes/likes before I write the code?

**Comment by endofline** [comment]
The only issue that will occur with a separate logging configuration file would possibly break backward-compatibility for [command-line usage](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/hangupsbot.py#L863) for botmins who are customising the placement of their `config.json`. 

Also, is a separate config file really necessary? The logging config dictionary can be stored as part of the current `config.json`

Regardless of the above implementation strategies, it seems like both this issue and #318 seem to require a refactor of the bot startup/init code. I will raise a new issue for this.

**Comment by pleasantone** [comment]
Excellent points all. I will have sample code tomorrow.

**Comment by endofline** [comment]
Will auto-close on merge of #300
