### ISSUE TITLE
IPv6 support for webhooks

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#325]
I just came across an issue with GitHub pushes. My server has both a v6 and a v4 address.

GitHub attempted to connect to server:<webhook port>, and preferred v6 to v4.

Since we only listen on v4, the connection was refused.  The trivial (for me) workaround was to remove the v6 address from DNS, however, at some point, we're going to want to be able to configure HTTPServer -> TCPSocketServer with different AFs and start both v4 and v6 daemons. Should be fairly trivial.

This is very low priority, but did want to log the issue.

**Comment by endofline** [comment]
I preferred the original title ;P In a future version, we can upgrade the github/gitlab listeners to the aiohttp.web model, which seems to support ipv6 out of the box - the current implementation is getting positively ancient with the new sinks.

**Comment by pleasantone** [comment]
Github hook verified to work perfectly, great job!
Other hooks verified to be listening on both v4 and v6.
