### ISSUE TITLE
pluginreload command (aesthetics)

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#327]
The following was received when running the pluginreload command in v2.7, when I failed to include any arguments to the command, ex. plugin name, and the error received it the HO was the index error shown below, I would assume a more human readable error could be passed, ex. stupid idiot, you didnt include a pugin name ....  :) 

23:49:53 ERROR commands: RUN: pluginreload
Traceback (most recent call last):
  File "/home/pi/hangoutsbot/hangupsbot/commands/__init__.py", line 177, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/home/pi/hangoutsbot/hangupsbot/commands/plugincontrol.py", line 119, in pluginreload
    module_path = args[0]
IndexError: tuple index out of range

**Comment by endofline** [comment]
This would be expected behaviour for this experimental low-level command ;P A cosmetic issue nonetheless, as the error is caught correctly by the internal handler and output as a bot message - will be fixed in a future tweak

**Comment by endofline** [comment]
Confirmed and added to next minor version (re: #328)
