### ISSUE TITLE
[convtools] set topic of old chat to new chat

### ISSUE THREAD

**Issue by nhulsch** [hangoutsbot/hangoutsbot#333]
would be awesome to have the old kick-plugin behavior back that the the old topic will be the new topic and the old hangout will be renamed to DEAD or similar.

**Comment by gurumadmat** [comment]
Yes this would be better!

**Comment by endofline** [comment]
The conversation rename has been implemented into [`/bot refresh`](https://github.com/hangoutsbot/hangoutsbot/wiki/Conversation-Tools-Plugin#refreshing-a-conversation) and the re-introduced [`/bot kick`](https://github.com/hangoutsbot/hangoutsbot/wiki/Conversation-Tools-Plugin#kicking-users)

Verified in #331
