### ISSUE TITLE
[feature request] ignore user

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#355]
Troll users are the worst and will cause a whole HO to hate the bot.  
I think we need a way to ignore user imput

/bot ignore [add|remove] user <UID>

this would add them to or remove them from  a global ignore list in perm memory that is checked before acting on a command in any HO with the bot, incuding 1 on 1 conversations.  the global ignore would take priority on any other list or tag the user may be on/have

**Comment by endofline** [comment]
Although it doesn't have an elegant method of calling it yet, you can now make the bot ignore users by using the following command:
```
/bot tagset user <user id> ignore
```

And to un-ignore a user:
```
/bot tagdel user <user id> ignore
```

**Comment by endofline** [comment]
[Tags List](https://github.com/hangoutsbot/hangoutsbot/wiki/Tags-List#ignore) on wiki updated
