### ISSUE TITLE
[aesthetics] IndexError: tuple index out of range

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#357]
ie.: mention IndexError: tuple index out of range

this is the response if someone trys to use /bot mention     (not sure why they would use it this way and not @ user) but in this instance they forgot to enter the user name.  However I have seen this error popup often, usually when not correctly formatting the command or leaving off part of the required arguments .  I would like to request we better define the arguments and catch the errors and respond with a better user error message in most of these cases, like you did with https://github.com/hangoutsbot/hangoutsbot/issues/327

**Comment by endofline** [comment]
Rather than implement error-handling for what is basically misuse of a test function, `/bot mention` is now admin-only. Wiki updated: https://github.com/hangoutsbot/hangoutsbot/wiki/Mentions-Plugin#admin-commands
