### ISSUE TITLE
problem with git+https://github.com/tdryer/hangups.git 

### ISSUE THREAD

**Issue by nosybore** [hangoutsbot/hangoutsbot#364]
using pip3 to install hangups from requirements.txt produces this error when trying to run hangupsbot.py:

Traceback (most recent call last):
  File "./hangupsbot.py", line 6, in <module>
    from hangups.schemas import OffTheRecordStatus
ImportError: No module named 'hangups.schemas'

if, however, I install this release (https://github.com/tdryer/hangups/releases/tag/v0.2.10) hangupsbot runs correctly.

**Comment by endofline** [comment]
Thanks, it appears that the hangups dev recently introduced backward-incompatible changes - will review the commits and patch the bot for compatibility. In the meantime, we will change the `requirements.txt` file so it continues to use a compatible version instead of latest

**Comment by endofline** [comment]
The last known working commit for hangups with current bot is https://github.com/tdryer/hangups/tree/84c6a20a24bede2fa41ffd54fda510e453f080dc

**Comment by endofline** [comment]
A workaround has been committed to fix the broken `requirements.txt` file - only close this issue once the bot is fully compatible with new hangups

**Comment by endofline** [comment]
The workaround is available as of [Release 2.7.3](https://github.com/hangoutsbot/hangoutsbot/releases/tag/2.7.3)

**Comment by tdryer** [comment]
Hey @endofline! Sorry for breaking backwards compatibility. I'd recommend depending on a specific hangups revision because I'm not planning on maintaining backwards compatibility until v1.0 is reached.

This change is pretty large, it replaces the old `schemas` module with Protocol Buffers. I'd be happy to help if you have any questions or suggestions when you're updating hangoutsbot.

**Comment by endofline** [comment]
Noted @tdryer - we will probably end up using [this bit in `hangouts_pb2`](https://github.com/tdryer/hangups/blob/4a08bc4f6b6c3aeb0c60fb5dff46304e3edc7cc5/hangups/hangouts_pb2.py#L1298)

For those who are building hangups, these commands in the hangups working copy root will suffice: 
```
git checkout 84c6a20a24bede2fa41ffd54fda510e453f080dc
python3 setup.py install
```
