### ISSUE TITLE
Need ability to accept invites for bot

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#369]
I am an admin of the bot but the bot needs to accept the chat invite before it will work in the hangout it was added to. Rather than logging into the account manually it would help to have the ability to accept invites though another hangout with the bot.

**Comment by endofline** [comment]
You need to [Change your Hangouts invite settings](https://support.google.com/hangouts/answer/3118240?hl=en&rd=1). Also, it's been observed that sending a message to a conversation will auto-accept pending invites as well, and you can use [`convecho`](https://github.com/hangoutsbot/hangoutsbot/wiki/CONVID-Commands) for that

**Comment by j16sdiz** [comment]
This is the call for accepting an invite, just in case if sb want to implement this:

API Endpoint: `conversations/replytoinvite` 
Payload:
```
[
	[[44,1,"chat_web_connection_server_20150821.05_p2",1440526689], ["lcsw_hangoutsC277C2B8","EA5CF5604AC67D73"],null, "en" ],
	["UgwSK0zUMRcWKyzmhVR4AaABAQ"],       // conv id
	1,        // 1=accept, 2=reject
	null,
	[]
]
```

**Comment by endofline** [comment]
I get the impression this payload is automatically inferred when a message is sent to a conversation with a pending invite (per the `convecho` description above), but this behaviour may have changed - further input or a plugin PR is welcome :)

**Comment by endofline** [comment]
To add, you may also have to respond to this: https://github.com/tdryer/hangups/blob/master/docs/proto.rst#replytoinvitenotification
