### ISSUE TITLE
team/cluster hangouts (enhancement)

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#379]
One request I hear, periodically, is "I wish I could arbitrarily join/leave" hangouts.

Bot admins can do that, and using tagging, we could create a class of people who could do that, but what would really make sense, is to support team clusters.  Currently, I think most people do it via the RSVP mechanism, but that requires that they have been a member of a HO in the last n days.

One possible design, which I wanted to get down for discussion, is to designate a particular hangout as the "Team Master Hangout."  Hang a list of "authorized to join" HOs off of that team master HO.  If I am a member of that HO, the bot will authorize/add me to any of the other hangouts in the list.

**Comment by nvrrvn** [comment]
Something like this https://gist.github.com/endofline/900fa605636b87b56894 with a bit of access control is what I'm using.

**Comment by endofline** [comment]
Adding tag support to this so we can filter which links are available to specific conversation would be nice, but I have not figured out how the internal config representation for this yet. Suggestions welcome!
