### ISSUE TITLE
[Plugin][Mentions] Mention options with multiple bots

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#383]
I have 3 bots currently with different purposes and "owners", we all add them to conversations for our own reasons and sometimes we end up with more than 1 per conversation. I would like to do one of two things. 
1) Have the mention plugin off by default on hangouts the bot is in, but be able to easily enable them as needed/wanted.
2) Have something hard coded to look for other bot id's and if found do not do mentions for that chat (in this scenario I would have a 4th bot just to do mentions or something like that) 

I cannot figure out how to pull a user list and compare it before doing a mention. Any advise you may have would be great. You probably even have an easier way built in to accomplish what I want and I just was unable to find it.

**Comment by thannemann** [comment]
Mentions are supprted as perconversation settings, see if this helps you  https://github.com/hangoutsbot/hangoutsbot/wiki/Mentions-Plugin#configuration
each owner would need to configure the bot for each conversation.

**Comment by bmbermn** [comment]
That is the opposite of what I want in this case. The bots move in and out
of conversations and it's annoying to have to config each one like that

**Comment by thannemann** [comment]
unless I am reading it wrong, I think you could, set mentions.enabled as false from the global state, and then turn it on per conversation in the config file

**Comment by j16sdiz** [comment]
1. There are multiple bots in the same sets of rooms.
2. They generate duplicated @mention (as expected)
3. Too many rooms, bots go in and out, no easy way to config all bots

The issue author want an automated way to detect other bots (?) and disable/enable @mention.

**Comment by j16sdiz** [comment]
Possible way to do this:

1. Keep a list of known bot, associated with a priority value
2. When @mention is triggered, check if other bots are present in same conv. 
3. If there are other bots, check if any of them have higher priority then itself.
4. Send @mention only if it is the highest priority bot in the conv.

**Comment by j16sdiz** [comment]
Another way to do this:
- Channels for bot-2-bot communication
- Election

**Comment by bmbermn** [comment]
@j16sdiz I was just circling back to this, how can I set a priority? I cannot find any documentation on that functionality but I think it would work perfectly. If I can check what the highest priority is in a room and see if that = mybots priority level then send. Just need some guidance on how to implement.

**Comment by bmbermn** [comment]
I fixed this with my own solution. Thanks
