### ISSUE TITLE
Slack -> Hangouts -> Slack does not work

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#384]
I just tried bridging two Slack channels (in different Slack teams) together with a hangout.

SlackA <-> Hangout works
SlackB <-> Hangout works
SlackA <- Hangout -> SlackB works

However, messages from SlackA -> Hangout never make it to SlackB (and likewise).

We currently set event._slack_no_repeat on an incoming message that we receive, in order to stop bouncing stuff back and forth between Slack and HO, but it's just a boolean, so it stops all rebroadcasts.

Inbound messages from Slack include a "channel_name" and "team_domain" which we can record using the reprocessor.  We then change the tests to match against that info outbound and allow rebroadcasting to all directions -except- the team/channel that we just received that message.

That said, we have a problem. The outbound code doesn't know anything about teams, so the configuration is going to need to be changed.

**Comment by jumoog** [comment]
it does
https://github.com/hangoutsbot/hangoutsbot/pull/404
