### ISSUE TITLE
[feature-request] Nicknames for users. 

### ISSUE THREAD

**Issue by Reddog176** [hangoutsbot/hangoutsbot#386]
Unless I missed it somewhere, I think it would be helpful to be able to give users nicknames. 
We use hangouts for alot of web based games, and use the bot to forward chats to other chats, but people get confused by not knowing who's talking. Being able to override the person's name with their in game name would be very helpful.

**Comment by endofline** [comment]
This is already available as `/bot setnickname`, a [user command](https://github.com/hangoutsbot/hangoutsbot/wiki/Mentions-Plugin#user-commands) exposed by the mentions plugin

**Comment by Reddog176** [comment]
setnickname doesn't appear to get picked up by the forwarder plugin though.

**Comment by gurumadmat** [comment]
It would be useful for admins to use this command on user-ids and set nicknames for them.
also multiple nickname support would be nice.

**Comment by nylonee** [comment]
@Reddog176 It's worth reading up how to [contribute to an open source project](https://guides.github.com/activities/contributing-to-open-source/). The part that would be relevant to you is at the bottom, about Pull Requests.

**Comment by endofline** [comment]
If a PR is issued, please re-open this issue :)
