### ISSUE TITLE
Updating a list

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#391]
I am using the watchmember example plugin that i have customized to re-add users back users that leave in certain conversations. I would like to be able to update the list of conversations using the bot but have no idea how to do so.  Here is my python code to help. Would love any input you can give me on that or an alternate way to handle that part.  Thanks

"""
example plugin which watches join and leave events
"""

import asyncio, logging

import hangups

import plugins

logger = logging.getLogger(__name__)

def _initialise(bot):
    plugins.register_handler(_watch_membership_change, type="membership")

@asyncio.coroutine
def _watch_membership_change(bot, event, command):
    # Generate list of added or removed users
    event_users = [event.conv.get_user(user_id) for user_id
                   in event.conv_event.participant_ids]
    names = ', '.join([user.full_name for user in event_users])

    #SetUsername
    #leavingid=event.user.user_id
    leavingid= event.user.id_.chat_id

    # JOIN
    if event.conv_event.type_ == hangups.MembershipChangeType.JOIN:
        logger.info('{} has added {}'.format(event.user.full_name, names))
    # LEAVE
    else:
        #logger.info('{} has left'.format(names))
        logger.info('{} has left'.format(leavingid))
    lockedchats=('Ugxg7OTfqByfb2O3Rdd4AaABAQ','UgwOIMQ2fK__y88CBAt4AaABAQ','UgwtyZ2XOUNdS8be72V4AaABAQ')
    bots = ('113897661101977313159','104456840723699280056','113266520998174200815')
    logger.info(event.conv.id_)                            
    if event.conv.id_ in lockedchats:
        if event.user.id_.chat_id not in bots:
           yield from bot._client.adduser(event.conv_id, [event.user.id_.chat_id])

**Comment by endofline** [comment]
Please use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks); a [gist](https://gist.github.com/) or similar services when sharing code in an issue. Readability is important when seeking coding help.

As to your question, I'm not sure what you mean by "update the list of conversations using the bot" - try:
* [Accessing and Writing `config.json`](https://github.com/hangoutsbot/hangoutsbot/wiki/Accessing-and-Writing-config.json) if you intend to store a list of conversations in `config.json`
* [Accessing and Writing `memory.json`](https://github.com/hangoutsbot/hangoutsbot/wiki/Accessing-and-Writing-memory.json) if you intend to store a list of conversation in `memory.json`
* [User and Conversations Tagging](https://github.com/hangoutsbot/hangoutsbot/wiki/Users-and-Conversations-Tagging) if you intend to use a conversation tag (`tag:<conv tag>`) combined with the `tag:` prefix in [`bot.conversations.get()`](https://github.com/hangoutsbot/hangoutsbot/wiki/Permanent-Memory#accessing-conversations-list) to retrieve a list of tagged conversations

**Comment by bmbermn** [comment]
Hi this is good information but i have a followup question. I have figured out my initial issue and am using memory per conversation to store things which is awesome. Now however I want to store something globally and am unsure how to do it. Any time I try and add a section to the config.json the bot will no longer load. I am looking to store an event name and datetime that I can use for a reminder plugin I am working on. Can you advise?

**Comment by endofline** [comment]
There are [many working examples](https://github.com/hangoutsbot/hangoutsbot/search?utf8=%E2%9C%93&q=bot.config.get&type=Code) that [access and write `config.json`](https://github.com/hangoutsbot/hangoutsbot/wiki/Accessing-and-Writing-config.json).

As for your `config.json` issue, the error/exception messages will generally inform you of the line in `config.json` that is causing the error - which is generally an invalid syntax. Familiarity with [JSON](https://en.wikipedia.org/wiki/JSON) and particularly, [the quasi-strict json syntax processing](https://docs.python.org/3/library/json.html#standard-compliance-and-interoperability) of Python is highly recommended.

**Comment by endofline** [comment]
To add to the above: youb can derive guidance from [existing code](https://github.com/hangoutsbot/hangoutsbot/search?utf8=%E2%9C%93&q=strict_botkeeper_check)
