### ISSUE TITLE
Question about updates

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#394]
Hi,

I had a ton of pages open earlier today and I found one that was a change log that listed recent updates and improvements to the bot. My issue is I lost it, I went through everywhere I could think of and I cannot find it. Can someone point me to where that is? 

Thanks

**Comment by nylonee** [comment]
You may be referring to the [Bot Releases](https://github.com/hangoutsbot/hangoutsbot/releases) which lists changes as we update the bot through the different releases.

The still experimental 2.7.4 release is not ready yet, but you can view progress on the Pull Request [here](https://github.com/hangoutsbot/hangoutsbot/pull/368)
