### ISSUE TITLE
Error when leaving conversation

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#395]
I get this error when the bot attempts to leave a conversation via restrictedadd.py:

```
14:28:40 ERROR root: CONVLEAVE: error leaving UgyXXXXXXXXXX4AaABAQ Test Hangout
Traceback (most recent call last):
  File "/root/hangupsbot/hangupsbot/commands/convid.py", line 165, in convleave
    yield from bot._client.removeuser(convid)
  File "/root/hangupsbot/hangupsbot/monkeypatch/otr_support.py", line 64, in otr_monkeypatch_removeuser
    .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_UNEXPECTED
```

I'm using v2.7.4-Alpha

**Comment by nvrrvn** [comment]
The same happens on v2.7.3.

**Comment by vaindil** [comment]
I'm getting the same error on 2.7.4. The bot tells the Hangout it's going to leave when someone unauthorized adds it, but it doesn't actually leave. The error given in the OP is thrown. It happens both with the `restrictedadd` plugin and when I try to manually remove it using `/bot leave convid`.

**Comment by nylonee** [comment]
Is this still an error that people are seeing? I haven't seen it in a while on my side

**Comment by gurumadmat** [comment]
Haven't seen it either for some time now.

**Comment by TimWolla** [comment]
I can confirm this issue using `2.7.8-2-g95e4127`(i.e. commit 95e4127).

When requesting the leave for a second time it works just fine.

**Comment by TimWolla** [comment]
> When requesting the leave for a second time it works just fine.

This fact got me wondering, whether it may be some kind of race condition on Google's servers:

I ramped up [the sleep](https://github.com/hangoutsbot/hangoutsbot/blob/95e412741ebac5ae2666b1acbb2dd61c59491186/hangupsbot/plugins/restrictedadd.py#L115) to 10 seconds and it worked fine afterwards.
