### ISSUE TITLE
Memory Question

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#397]
Is it possible to clear conversations from memory? My bot has 45 hangouts listed when I call hangouts but only maybe 10 are active.

**Comment by endofline** [comment]
It is possible to individually remove conversations entries: https://github.com/hangoutsbot/hangoutsbot/wiki/Permanent-Memory#remove-conversation-record - however, these entries will be re-generated if a new event occurs in the removed conversation. The only way to permanently remove a conversation  is to `/bot quit` the conversation(s) in question.

**Comment by bmbermn** [comment]
That works for groups it appears but not one on one's I get

08:53:31 INFO commands.permamem: resetunknownusers started
08:53:31 WARNING permamem: cannot remove conv: ONE_TO_ONE
Ugy92Uo8qDIO8McBXCh4AaABAQ Nick
08:53:31 INFO commands.permamem: resetunknownusers finished


Those are what is polluting the "/bot hangouts" report.

**Comment by endofline** [comment]
Presumably, your actual goal is to list only hangouts which are groups:

Use `/bot convfilter type:GROUP` command (part of [CONVID Commands](https://github.com/hangoutsbot/hangoutsbot/wiki/CONVID-Commands))
