### ISSUE TITLE
Tagset not working

### ISSUE THREAD

**Issue by foriamroot** [hangoutsbot/hangoutsbot#398]
Hi:

Tagset convuser is not accepting convuser with conv|user as an argument. 

Traceback (most recent call last):
File "/root/hangoutsbot/hangupsbot/commands/__init__.py", line 178, in run
  results = yield from func(bot, event, *args, **kwds)
File "/root/hangoutsbot/hangupsbot/commands/tagging.py", line 31, in tagset
  if bot.tags.add(type, id, tag):
File "/root/hangoutsbot/hangupsbot/tagging.py", line 174, in add
  return self.update(type, id, "set", tag)
File "/root/hangoutsbot/hangupsbot/tagging.py", line 112, in update
  raise ValueError("user {} is invalid".format(id))

Command used:

/root tagset convuser Ugy00YlAfnsb6_W6Nrh4AaABAQ|111768824008954169610 hunter

**Comment by foriamroot** [comment]
![screenshot_2015-09-20-10-49-00](https://cloud.githubusercontent.com/assets/8344379/9981249/0c2e8c4e-5f86-11e5-9dfa-b50206d03dab.png)

**Comment by endofline** [comment]
The user does not apparently exist in your `memory.json` file - it may be caused if the bot/user has never interacted with each other before. Try and @mention the user in question (if the mention plugin is active), or ask the user to request for `/bot help` and see whether u can set the tag after.

**Comment by foriamroot** [comment]
"111768824008954169610": {
      "1on1": "Ugwvo_PLOU4BKBB7QaZ4AaABAQ",
      "_hangups": {
        "chat_id": "111768824008954169610",
        "emails": [],
        "first_name": "User",
        "full_name": "Full User",
        "gaia_id": "111768824008954169610",
        "is_definitive": true,
        "is_self": false,
        "photo_url": "//lh4.googleusercontent.com/-fSXOVv1H59A/AAAAAAAAAAI/AAAAAAAAAio/QS3QIVuDG7U/photo.jpg",
        "updated": "20150913002644"
      },

**Comment by foriamroot** [comment]
pulling down to test now

**Comment by foriamroot** [comment]
awesome. thanks for th help :D
