### ISSUE TITLE
tagspurge

### ISSUE THREAD

**Issue by foriamroot** [hangoutsbot/hangoutsbot#399]
the same issue as 398 except in tagspurge.

tagspurge ValueError: user Ugy00YlAfnsb6_W6Nrh4AaABAQ|111768824008954169610 is invalid

**Comment by endofline** [comment]
This looks incorrect `**user** ...` - that should be convuser

**Comment by foriamroot** [comment]
checking now

**Comment by foriamroot** [comment]
correct you are sir; my mistake :D
