### ISSUE TITLE
[bug] leave blocked hangout

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#408]
I tired to leave a one to one conversation and got the following message back in the console apparently the user was already blocked whic I think means the hangout was already killed.  This message (or one like it) should be sent back the the botadmin who ran the command.

06:56:37 WARNING root: CONVLEAVE: cannot leave ONE_TO_ONE XXXXXXXXXXXXX

**Comment by nylonee** [comment]
I think I need more information... Are you trying to get the bot to leave a one-to-one conversation that isn't yours? Was the user blocking the bot, or was the bot blocking the user? What message did you receive in console? Were you intentionally trying to get the bot to leave the one-to-one, or did you think that it was a group?

**Comment by thannemann** [comment]
The user was blocked in the bot account. I did that because the user was
attempting to break the bots functions. I only tried to have the bot leave
the one to one  to remove it from the memorry.json file. The response in
the console was posted above.

**Comment by nylonee** [comment]
Ah. So to clarify, if somebody writes `/bot leave conv-x` you would expect a warning to be sent back via hangouts that the conversation is a 1-1?

**Comment by thannemann** [comment]
sorry I missed the reply, can a bot not leave a 1-1 hangout?

**Comment by nylonee** [comment]
Correct, a bot is unable to leave a 1-1 hangout.
Your best bet is to just log in and block the abusive user, as we don't yet have the functionality for a user whitelist/blacklist.
