### ISSUE TITLE
[bug] Problem installing enum34 with Python3.5

### ISSUE THREAD

**Issue by JimmyMow** [hangoutsbot/hangoutsbot#412]
I am getting an error installing enum34 which hangups requires on the specific commit the requirements.txt is referencing. According to here: https://github.com/tdryer/hangups/issues/147 hangups came out with a new version to fix this, but using that version in the requirements.txt file breaks hangoutsbot because of the hangups.schema change. Any workaround for this? Thanks.

**Comment by JimmyMow** [comment]
There should be some fix outside of installing python 3.4.2 because homebrew python3 is now python 3.5

**Comment by thannemann** [comment]
until the hangoutbotc code can catchup with the latest from tdryer we needed to use a specific buid. I assume this will be worked on at some point

**Comment by nylonee** [comment]
This was also mentioned in #416. I've adapted the solution from tdryer/hangups#147 to [hangoutsbot/hangups](https://github.com/hangoutsbot/hangups), which is the version of hangups that is guaranteed to work with hangoutsbot.

I've also updated the requirements.txt (see 6f5102b1333cc9dbf4ce38e7d8332597875cec6a) to install the correct hangups, so assuming you've attempted to install the old version of hangups in python 3.5, the following commands should fix your issue:

```
pip uninstall enum34
pip3 install -r requirements.txt
```

(Note: As of writing the requirements.txt is only updated in the staging branch)

I'll leave this open for a while longer
