### ISSUE TITLE
First Run After Auth token

### ISSUE THREAD

**Issue by dmyers86** [hangoutsbot/hangoutsbot#413]
Getting these errors when starting hangupsbot.py..

Saw another issue#20 with similar issues but not sure of the fix.

C:\GitHub\hangupsbot>python hangupsbot/hangupsbot.py -d
WARNING: hangups library out of date!
HangupsBot: memory file will be used: C:\Users\Admin\AppData\Local\hangupsbot\hangupsbot\memory.json
config.jsonrpc[0].certfile must be configured
config.jsonrpc[1].certfile must be configured
config.jsonrpc[2].certfile must be configured
config.jsonrpc[3].certfile must be configured
config.jsonrpc[4].certfile must be configured
Client unexpectedly disconnected:
_on_connect() missing 1 required positional argument: 'initial_data'
Waiting 5 seconds...
Trying to connect again (try 1 of 5)...
Client unexpectedly disconnected:
_on_connect() missing 1 required positional argument: 'initial_data'
Waiting 10 seconds...
Trying to connect again (try 2 of 5)...
Client unexpectedly disconnected:
_on_connect() missing 1 required positional argument: 'initial_data'
Waiting 15 seconds...
Trying to connect again (try 3 of 5)...
Client unexpectedly disconnected:
_on_connect() missing 1 required positional argument: 'initial_data'
Waiting 20 seconds...
Trying to connect again (try 4 of 5)...
Client unexpectedly disconnected:

**Comment by j16sdiz** [comment]
You need the exact version of hangup library.

**Comment by nylonee** [comment]
See #412 on the fix, you'll need to pull the correct [fork of hangups](https://github.com/hangoutsbot/hangups)
