### ISSUE TITLE
[plugin] Translator: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#414]
The translator plugin is returning an error 503:

`Translation server error: HTTP Error 503: Service Unavailable`

**Comment by FrNico** [comment]
@nylonee we are getting that message when we are reaching our quota with google translate library, right?
alternate option will be then to move to a different service like Bing Translator?

**Comment by nylonee** [comment]
The fix is in PR #479 to be merged into master
