### ISSUE TITLE
Allow parameters in autoreplies

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#418]
For example: `!blame jeff` should be able to return `I blame jeff.`. That same command should allow `!blame joe` to return `I blame joe.`.

**Comment by nightfire8199** [comment]
It seems to me that autoreplies are static, and wouldn't easily support this.

Whats wrong with authoring a plugin that registers a list of commands that you want? The one you described would be incredibly simple.

I'm new here, and might be misunderstanding thins though.

**Comment by vaindil** [comment]
I'm writing a plugin, you're correct. Thank you!
