### ISSUE TITLE
asyncio error when bot tries to respond

### ISSUE THREAD

**Issue by ckanoab** [hangoutsbot/hangoutsbot#419]
Trying to get bot running on a Win7 x64 system with python 3.5. Got through all the setup nonsense with the old version of hangups etc, but now when I "/bot ping" I get the following error in the console:

```
01:05:29 ERROR asyncio: Exception in callback HangupsBot._on_event.<locals>.<lambda>(<Task finishe...t callable",)>) at
hangupsbot/hangupsbot.py:587
handle: <Handle HangupsBot._on_event.<locals>.<lambda>(<Task finishe...t callable",)>) at hangupsbot/hangupsbot.py:587>
Traceback (most recent call last):
  File "C:\Python34\lib\asyncio\events.py", line 120, in _run
    self._callback(*self._args)
  File "hangupsbot/hangupsbot.py", line 587, in <lambda>
    ).add_done_callback(lambda future: future.result())
  File "C:\Python34\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "C:\Python34\lib\asyncio\tasks.py", line 238, in _step
    result = next(coro)
  File "C:\hangoutsbot\hangupsbot\handlers.py", line 147, in handle_chat_message
    yield from self.handle_command(event)
  File "C:\hangoutsbot\hangupsbot\handlers.py", line 199, in handle_command
    yield from command.unknown_command(self.bot, event, *line_args[1:])
TypeError: 'NoneType' object is not callable
```

I've tried uninstalling and reinstalling all components multiple times. What am I missing?

**Comment by ckanoab** [comment]
Tried with python 2.7 but no asyncio. 3.4.3 has same issue as 3.5

**Comment by cntrlwiz** [comment]
I realize this is a little stale, but...
I had exactly the same issue with fresh install. 
Found that basic.py imports resources, which doesn't exist in Windows builds.
So, upon startup, Basic.py crashes, and the commands in that file don't get registered.
I commented out the import and the code for the resourcememory command.
All is well now.

Devs need to look at avoiding this issue on Windows builds.

**Comment by gurumadmat** [comment]
@cntrlwiz what imports did you comment out?

**Comment by cntrlwiz** [comment]
Only "resource" from the first line:

`import logging, sys #,resource

import plugins

from version import __version__
from commands import command
.
.
.
`

**Comment by Gnarlywhale** [comment]
Just ran into this, @cntrlwiz 's method worked.
