### ISSUE TITLE
Bot uses group chat instead of private chat

### ISSUE THREAD

**Issue by topcu** [hangoutsbot/hangoutsbot#421]
Somehow for one of my users, bot tries to send private messages to a group chat.
Me, the user and bot was member of that group. Than we dismissed bot and leaved the group.
User realized that bot was not replying her commands in private. After we joined and put the bot back into the initial group It started to print all the responses to that group.

**Comment by nylonee** [comment]
After investigation, it seems like the group conversation got stored as the 1to1 for the user in memory.json. Changing this to the correct 1to1 worked, but I'm still unsure as to why this issue arose in the first place.

**Comment by j16sdiz** [comment]
Here https://github.com/hangoutsbot/hangoutsbot/blob/7ff137e2c7d66dba7c8e61aef226ef86d5164888/hangupsbot/hangupsbot.py#L403 and https://github.com/hangoutsbot/hangoutsbot/blob/7ff137e2c7d66dba7c8e61aef226ef86d5164888/hangupsbot/hangupsbot.py#L464 get the first conv with 2 users as one-on-one.

If a user with no previous 1on1 with bot get into a group of 2 with bot, the bot will record it in memory.json. Should have check conv type is ONE_TO_ONE.

**Comment by nylonee** [comment]
Good spotting. I'll reopen this issue

**Comment by JosephBlock** [comment]
Unsure on how to test this but as conversation (c) should contain the type of hangout, this should check for that.
Commit: ffa9044713f629507bb66390f90a622b794aa6c9

**Comment by j16sdiz** [comment]
@JosephBlock when this info is not available in hangups, conversation relies on memory.json to determine the conversation type. Kind of chicken and egg .
