### ISSUE TITLE
Images not loading across synced hangouts

### ISSUE THREAD

**Issue by azack** [hangoutsbot/hangoutsbot#422]
## Steps to reproduce:
1. Configure 2 hangouts with the bot spanning both conversations
2. Add an image to the first hangout

### Observe: 
Image is not duplicated to the second hangout.

### Notes
The bot prints this to stdout in this condition:
```
21:39:04 ERROR handlers: message: plugins.syncrooms._handle_incoming_message : coroutine
Traceback (most recent call last):
  File "/home/hangupsbot/hangupsbot/hangupsbot/handlers.py", line 256, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/home/hangupsbot/hangupsbot/hangupsbot/plugins/syncrooms.py", line 181, in _handle_incoming_message
    image_id = yield from bot._client.upload_image(image_data, filename=filename)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 472, in upload_image
    upload_url = (json.loads(res1.body.decode())['sessionStatus']
KeyError: 'sessionStatus'
```

It appears to be an issue with the configuration of the hangups lib, which was fixed here:
https://github.com/tdryer/hangups/pull/182

While the long-term solution is to upgrade the hangups version, which I think was discussed here:
https://github.com/hangoutsbot/hangoutsbot/issues/366

.. for now the workaround I used was to edit `/usr/local/lib/python3.4/site-packages/hangups/client.py` to change:
```
20c20
< IMAGE_UPLOAD_URL = 'http://docs.google.com/upload/photos/resumable'
---
> IMAGE_UPLOAD_URL = 'https://docs.google.com/upload/photos/resumable'
```

**Comment by PHLAK** [comment]
I'm not certain, but I think Google may have changed something on their end to break the way hangups handled this.  If that's true we have to wait for hangups to fix the bug, then hangupsbot to update with the new version of hangups.

**Comment by azack** [comment]
@PHLAK I think both those things were true and I tried to convey that above - it was probably addressed in this PR tdryer/hangups#182

**Comment by PHLAK** [comment]
Yeah, sorry.  Didn't fully read your initial post.  I hope the devs see this and give us a bugfix release soon.  Seems like there haven't been any commits since October 15th though. :cry:

**Comment by nylonee** [comment]
I've implemented the patch in [hangoutsbot/hangups](https://github.com/hangoutsbot/hangups/) (See commit [0818ad](https://github.com/hangoutsbot/hangups/commit/0818ade3f9ca505457b9da55bcc86757fd355335)).

You're right, the long-term solution is to have hangoutsbot work with the latest version of hangups. It's a work in progress!
