### ISSUE TITLE
Spotify Plugin - Authentication error

### ISSUE THREAD

**Issue by nightfire8199** [hangoutsbot/hangoutsbot#426]
So first off, I'll admit, this could be my bad.

Essentially I am getting an error when attempting to connect.
Any time I try to */bot spotify playlist* I get:  

*spotify AttributeError:'NoneType' object has no attribute 'user_playlist_create'*

When I check the log it says that the spotify user isn't configured after attempting a urllib3 connection, but what isn't configured correctly isn't stated.

I have all my Client IDs in the config file, do my URI and User fields have to be something specific? 
Currently I have the URI set to my personal homepage (not sure what else to set it to), and the user is set to the email for the spotify account.

Any help would be greatly appreciated.

**Comment by nylonee** [comment]
@linguinee See above

**Comment by linguinee** [comment]
`SPOTIFY_USER` in the config file should be replaced by the [Spotify user ID](https://developer.spotify.com/web-api/user-guide/#spotify-uris-and-ids), which isn't the same as the email. It should just be the username of that account.

**Comment by nightfire8199** [comment]
Thanks, I got it figured out. My config file got duplicated somehow and I was apparently editing the wrong one.
