### ISSUE TITLE
plugins.image_links not showing linked image & image_memegenerator not finding any memes 

### ISSUE THREAD

**Issue by hit0wnzzz** [hangoutsbot/hangoutsbot#429]
13:21:12 INFO plugins.image_links: getting https://media.giphy.com/media/iabcSfUB6VZYc/giphy.gif
13:21:13 ERROR handlers: message: plugins.image_links._watch_image_link : coroutine
Traceback (most recent call last):
  File "/Users/lightbleu/bot/hangoutsbot/hangupsbot/handlers.py", line 256, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/Users/lightbleu/bot/hangoutsbot/hangupsbot/plugins/image_links.py", line 62, in _watch_image_link
    image_id = yield from bot._client.upload_image(image_data, filename=filename)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 473, in upload_image
    ['externalFieldTransfers'][0]['putInfo']['url'])
KeyError: 'sessionStatus'

13:28:05 ERROR plugins.image_memegenerator: FAILED TO RETRIEVE MEME
Traceback (most recent call last):
  File "/Users/lightbleu/bot/hangoutsbot/hangupsbot/plugins/image_memegenerator.py", line 61, in meme
    photo_id = yield from bot._client.upload_image(image_data, filename=filename)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 473, in upload_image
    ['externalFieldTransfers'][0]['putInfo']['url'])
KeyError: 'sessionStatus'
13:28:05 INFO event: eid/dt: 7-H0Z7-2YY286pLo8JKEbr/2015-11-21 13:28:05
13:28:05 INFO event: cid/cn: UgycBF-vE6nG3hwozlB4AaABAQ/📚HOME OF FITO BOT📚
13:28:05 INFO event: c/g/un: 114255383798683708908/114255383798683708908/Fito Hackimail
13:28:05 INFO event: len/tx: 40/couldn't find a suitable meme! try again

Mac OS X 10.9.5
Python 3.4.2

**Comment by CmputrAce** [comment]
I am getting the same on syncrooms when someone posts an image.

**Comment by nylonee** [comment]
Hmm... This seems like another change that Google has done.

I don't think it's the same as issue #422, but have you tried updating your hangups from tdryer/hangups to [hangoutsbot/hangups](https://github.com/hangoutsbot/hangups/)?

**Comment by nylonee** [comment]
Ah just hit this bug on my local environment. I'll continue testing, but it seems like this is an issue that should be fixed on the hangups side.

**Comment by tdryer** [comment]
> Ah just hit this bug on my local environment. I'll continue testing, but it seems like this is an issue that should be fixed on the hangups side.

hangups image uploads are still working for me. Can you try to reproduce this with the latest version of the hangups client?

**Comment by hit0wnzzz** [comment]
I updated and it seems to be working now.

thanks for all the help!
