### ISSUE TITLE
Schedule message based on time of day

### ISSUE THREAD

**Issue by dylancaponi** [hangoutsbot/hangoutsbot#431]
Is there currently a method to schedule a bot message, in a specific group, at a specific time?

**Comment by nightfire8199** [comment]
I recently made a pull request #428  that allows you to schedule a message any number of minutes into the future either in the group the command was made in, or as a 1to1. You could wait until it gets pulled in, or go look at the pull request and grab it from there.

It's pretty simplistic, but should allow for easy extension.

**Comment by dylancaponi** [comment]
Thanks!  I'll wait until it gets pulled in.  Looking forward to repetitive scheduling!
