### ISSUE TITLE
Bot does not like emojies in hangout topic

### ISSUE THREAD

**Issue by JosephBlock** [hangoutsbot/hangoutsbot#436]
Message: 'cid/cn: Ugy1Z176TYgo3cR7GsN4AaABAQ/\U0001f634Chat In Question'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f634' in position 148: ordinal not in range(128)

(stack dump in file)

**Comment by pleasantone** [comment]
Is it possible you're running without setting either the LANG or PYTHONIOENCODING environment variables to include UTF-8?  e.g.

    export LANG=en-US.UTF-8
