### ISSUE TITLE
slackrtm needs a "users" command for hangouts that displays who is on the other side(s)

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#440]
There is no way, currently, for a slackrtm user on the HO side of things to request a membership list of the people on the slack side of the sync'ed connection.

I wrote something like this for the legacy slack plugin (see #388), but we need it for slackrtm too.

(not to be confused with @bot hangoutmembers which allows a Slack user to see HO users. We need the reflexive on the HO side to quiet the paranoids.)

**Comment by JosephBlock** [comment]
Added in #444

**Comment by pleasantone** [comment]
In 2.7.5

**Comment by pleasantone** [comment]
#445 has been merged into staging, apologies for the delay
