### ISSUE TITLE
Show user profile image to improve recognizability

### ISSUE THREAD

**Issue by lablua** [hangoutsbot/hangoutsbot#441]
One of the objections to using the Cross-chat Syncouts is:
> It looks VERY CONFUSING when people move to Slack and texts are replicated to HO by the BOT.
> 
> You dont see users icons anymore.. you receive messages from the BOT and the messages include 
> 
> '**Sender_name**
> Message'
> 
> We get used to the icons so we know who is sending without a second thought.
> 
> But a written name we need to read to make sure who is sending.. 

This should be fixable by grabbing the profile images and transmitting them along with the message, but it will require an extra call to get the image, so probably should use a cache.

Slack API for user profile image: https://api.slack.com/methods/users.info

**Comment by thannemann** [comment]
I dont think you can interject profile images into hangouts can you?

**Comment by nylonee** [comment]
Even if it's possible to interject profile images, the way current hangouts (on both desktop and mobile client) works is it'll precache the profile image, and it won't change until you refresh the browser or restart the app.

This is not feasible with current hangouts, closing until further notice.
