### ISSUE TITLE
Slack custom emoji look ugly in Hangouts

### ISSUE THREAD

**Issue by lablua** [hangoutsbot/hangoutsbot#442]
Slack emoji come across as meaningless text, rather than images:
> `:point_right::fist::dash::massage:`
instead of
> :point_right::fist::dash::massage:

Slack API definitely lets us get the custom emoji pictures: https://api.slack.com/methods/emoji.list

**Comment by pleasantone** [comment]
Which slack plugin are you using? slackrtm or the standard one?  I just noticed a bug in slackrtm's.

**Comment by JosephBlock** [comment]
Standard emojis work well it is the custom ones that are added that do not transfer like :bacon:

**Comment by j16sdiz** [comment]
I guess there is no way to do that automatically, the [emoji api](https://api.slack.com/methods/emoji.list) return images, not glyphs.

If this is to be implemented, it would be a separate mapping in the plugin config....

**Comment by pleasantone** [comment]
There are some aliases that can be returned, but nothing for custom, so I'm marking it closed.

I did, however, fix :simple_smile: which is a slack non-standard in #465.

If there are suggestions for other alias mappings, I'll support them as best I can when new issues are opened for particular emoji where the standard slack mappings are incorrect.

**Comment by errror** [comment]
Not sure, if I got this right. My slackrtm code (at least the one before it got merged in to mainline) already included a mapping for non-standard emojis to get them translated to "similar" standard emojis before sending them to hangouts. I'm sure :simple_smile: was the only mapping I added there but the code was designed with the possibility to add more.
