### ISSUE TITLE
SlackRTM should include the user's full name, not just slack username, in output

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#443]
Hangouts users are used to seeing people referred to by their name "Joe Blow" not their slack username joeblowofdestruction.

Show both when we bridge Slack to HO using SlackRTM.  If memory serves, the legacy plugin does this correctly.

**Comment by JosephBlock** [comment]
Added in #444

**Comment by pleasantone** [comment]
#445 was merged into the staging branch today, apologies for the delay and thank you for the excellent work.
