### ISSUE TITLE
pip3 goslate is failing

### ISSUE THREAD

**Issue by gurumadmat** [hangoutsbot/hangoutsbot#449]
Installing requirements.txt fails when it gets to goslate.

I fixed it by doing this:

LC_ALL=C.UTF-8 pip3 install -r requirements.txt

**Comment by deltreey** [comment]
:+1: same issue, fix did not work

**Comment by nylonee** [comment]
Is this still an issue that people are facing?

**Comment by deltreey** [comment]
No, different error.  I had to install as root (had to do that to install pip too so it's not on you guys), but otherwise, this worked.
