### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by memeshack** [hangoutsbot/hangoutsbot#450]
Noob user here, can someone possible help me install it? It always tells me I have an error when trying to run, can someone who successfully installed it send me their steps and help me? Thanks.

**Comment by ZeroTheSavior** [comment]
Post some logs.

**Comment by thannemann** [comment]
@memeshack what error are you getting

**Comment by 00svbeon** [comment]
Send me your Google plus link and I'll contact you viavia Hangouts to helphelp you
