### ISSUE TITLE
ImportError: cannot import name 'HangupsConversation'

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#451]
this was from the staging branch

Traceback (most recent call last):
  File "hangupsbot.py", line 21, in <module>
    from hangups_conversation import (HangupsConversation, FakeConversation)
ImportError: cannot import name 'HangupsConversation'

**Comment by JosephBlock** [comment]
Have you installed requirements.Txt via pip3?

**Comment by thannemann** [comment]
something odd was going on not sure what.

**Comment by nylonee** [comment]
I've run into this error too. Reopening until I figure out what's happening

**Comment by nylonee** [comment]
@gurumadmat FYI

**Comment by JosephBlock** [comment]
@nylonee which version of hangups?
using the version that requirements.txt installs (0.2.10) from https://github.com/hangoutsbot/hangups.git works. but if you do pip3 install hangups --upgrade it breaks with version 0.3.3

**Comment by nylonee** [comment]
I'm using the version that requirements.txt installs. Undoing commit d916e731e7b934f7197a5ca1e9765fb7c046c1a4 and trying again works for me though, so I believe it's something in that commit that breaks...
