### ISSUE TITLE
New User, Python Script won't execute

### ISSUE THREAD

**Issue by ADetectionAlgorithm** [hangoutsbot/hangoutsbot#453]
When attempting to start the bot software, the following command is issued per the installation guidelines:

python3 hangupsbot.py

when this command is executed, running in a newly cloned directory with the correct version of python, this error is retrieved:

Traceback (most recent call last):
  File "hangupsbot.py", line 2, in <module>
    import appdirs, argparse, asyncio, gettext, logging, logging.config, os, shutil, signal, sys, time
ImportError: No module named 'appdirs'

Am I doing something completely wrong?

[My name is A-A-ADA]

**Comment by JosephBlock** [comment]
Have you installed the requirements.txt?

**Comment by ADetectionAlgorithm** [comment]
Yes I have, several times to be safe.

**Comment by thannemann** [comment]
one thing that has bitten me more then once is making sure you are calling the right copy of python3

post back the results of which python3

**Comment by ADetectionAlgorithm** [comment]
It says it is running Python 3.4.0

[Initiate Log File ADA1.21G]
Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
[/Log]

Should a different version of Python be running on my mainframe?

**Comment by thannemann** [comment]
sorry, run the command   "which python3" this will tell you where it is located.  I think you need to use environment variables or point directly to that python version when calling the file.
ex. from the application directory my command is 

 ../../../../usr/bin/python3 hangupsbot.py

**Comment by j16sdiz** [comment]
Make sure your pip match your python

```
sdiz@grouper:~$ python3
Python 3.4.4rc1 (default, Dec  7 2015, 11:09:54)
[GCC 5.3.1 20151205] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path);
['', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages']
>>>
sdiz@grouper:~$
sdiz@grouper:~$ pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)
sdiz@grouper:~$
```

**Comment by ADetectionAlgorithm** [comment]
@thannemann which python3 gives me /usr/bin/python3

@j16sdiz I am using the normal pip command because pip3 comes back undefined when attempting to use that.  Could that be the source of the problem?

**Comment by ADetectionAlgorithm** [comment]
After installing Python3-based pip3, and reinstalling the requirements.txt, the same errors are still recieved through attempting to start the Python script.

**Comment by j16sdiz** [comment]
1: Don't mix and match different python version. When in doubt, use virtualenv.
2: Don't TRY to mix different python version.
3: Just use virtualenv.

**Comment by ADetectionAlgorithm** [comment]
So @j16sdiz what would you recommend I do?  Delete the progress that I have made and try to reinstall the software using correct versions of Python and pip?

**Comment by ADetectionAlgorithm** [comment]
Ok so I restarted everything fresh from a clean install, using fresh versions of Python and I am getting the same errors as described originally.

**Comment by thannemann** [comment]
The problem is that your python3 is installed in user/bin here is a link to virtenv

http://docs.python-guide.org/en/latest/dev/virtualenvs/

The correct fix is to create a virtual environment to the version you want to use, my "fix" was to go to the hangupsbot application directory and run ../../../../usr/bin/python3 hangupsbot.py which technically is not the correct way im still learning (virtenv is) but it works for me in the short time the ../../ needs to account for what level you are away from the root directory

**Comment by ADetectionAlgorithm** [comment]
I tryed the fix you recommended, as well as through using virtual env, on my previous installation and a fresh installation.  Both returned the same errors.  From the error codes, I guessed that Python3-appdirs was not installed, and so by sudo apt-get install python3-appdirs, I installed it.  That got rid of the error, but I ran into another error with hangups.  I tried installing it from source, using pip3 install hangups, and that led me to the error I am currently stuck on, described below:

(venv)root@chatbot:~/ADetectionAlgorithm/hangoutsbot/hangupsbot# python3 hangupsbot.py
Traceback (most recent call last):
  File "hangupsbot.py", line 6, in <module>
    from hangups.schemas import OffTheRecordStatus
ImportError: No module named 'hangups.schemas'

What am I doing wrong?

**Comment by ADetectionAlgorithm** [comment]
I still haven't gotten anything to work... Any advice?

**Comment by JosephBlock** [comment]
@ADetectionAlgorithm run `pip3 uninstall hangups` then run `pip3 install -r requirements.txt --upgrade`

**Comment by ADetectionAlgorithm** [comment]
@JosephBlock done, but received the following error... :/

(venv)root@chatbot:~/ADetectionAlgorithm/hangoutsbot# pip3 install -r requirements.txt --upgrade
Collecting git+https://github.com/hangoutsbot/hangups.git (from -r requirements.txt (line 1))
  Cloning https://github.com/hangoutsbot/hangups.git to /tmp/pip-yyphdocg-build
Collecting git+https://github.com/loisaidasam/pyslack.git (from -r requirements.txt (line 10))
  Cloning https://github.com/loisaidasam/pyslack.git to /tmp/pip-vv9614tk-build
Collecting git+https://github.com/carpedm20/emoji (from -r requirements.txt (line 11))
  Cloning https://github.com/carpedm20/emoji to /tmp/pip-ekfvo097-build
Requirement already up-to-date: appdirs in /root/ADetectionAlgorithm/venv/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Collecting asyncio (from -r requirements.txt (line 3))
  Using cached asyncio-3.4.3-py3-none-any.whl
Collecting jsonrpclib-pelix (from -r requirements.txt (line 4))
  Using cached jsonrpclib_pelix-0.2.6-py2.py3-none-any.whl
Collecting pushbullet.py (from -r requirements.txt (line 5))
  Using cached pushbullet.py-0.9.0-py2.py3-none-any.whl
Collecting beautifulsoup4 (from -r requirements.txt (line 6))
  Using cached beautifulsoup4-4.4.1-py3-none-any.whl
Collecting goslate (from -r requirements.txt (line 7))
  Using cached goslate-1.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-zuyeqeg6/goslate/setup.py", line 30, in <module>
        long_description=read('README.rst'),
      File "/tmp/pip-build-zuyeqeg6/goslate/setup.py", line 17, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/root/ADetectionAlgorithm/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2089: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zuyeqeg6/goslate

**Comment by ADetectionAlgorithm** [comment]
I tried again on a completely fresh server (different machine than before) and got the same errors.  Would it be possible to give someone temporary login credentials to the server (ssh) and have someone try debugging it manually for me?

**Comment by ADetectionAlgorithm** [comment]
Ok turned out I had two versions of Python installed, once I got rid of the copy in the /local directory, everything worked :)

Thanks for all the help!

**Comment by thannemann** [comment]
that's what I suspected and why I was trying to point you down the path of executing the version you wanted. glad to have this resolved

**Comment by 00svbeon** [comment]
Yeah I've had problem with Ubuntu VM's on amazon ec2 where there was one
python in /bin and one in /lib...

ons 30 dec 2015 19:35 thannemann <notifications@github.com> skrev:

> that's what I suspected and why I was trying to point you down the path of
> executing the version you wanted. glad to have this resolved
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hangoutsbot/hangoutsbot/issues/453#issuecomment-168051105>
> .
>
-- 

//S

**Comment by AhmetOZER** [comment]
/usr/local/bin/python3 hangupsbot.py
