### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by ppescitelli** [hangoutsbot/hangoutsbot#457]
I have the bot running and have my "spartacus" account.  What is the proper way to add new users?

Also, is there a more general discussion forum or google group to ask these sorts of questions? If not, it would be nice to have.

**Comment by 00svbeon** [comment]
Well there is a hangout... But it isn't very active atm as we that were
active developers when it started isn't that active anymore...

ons 30 dec 2015 15:50 ppescitelli <notifications@github.com> skrev:

> I have the bot running and have my "spartacus" account What is the proper
> way to add new users?
>
> Also, is there a more general discussion forum or google group to ask
> these sorts of questions? If not, it would be nice to have
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hangoutsbot/hangoutsbot/issues/457>.
>
-- 

//S

**Comment by gurumadmat** [comment]
Adding new users is simply creating new groupconversations with the bot added as well.
