### ISSUE TITLE
Botalias

### ISSUE THREAD

**Issue by ADetectionAlgorithm** [hangoutsbot/hangoutsbot#458]
What is the exact syntax of the botalias command?  And what is supposed to happen when you use it? 

I've been trying: /bot botalias add [Alias] but no matter what I try, nothing starting with /bot botalias will trigger any response from the bot.

This is probably just an ID10T error lol ;)

**Comment by thannemann** [comment]
the command is /bot botalias [Alias]  (add is not needed)

/bot botalias /hh will add /hh as a new alias but you wont get a response.

/bot botalias      will show your current alias's

and /bot botalias remove [Alias]     will remove the alias

**Comment by ADetectionAlgorithm** [comment]
Ok thanks it worked :)
