### ISSUE TITLE
Link in plugin output

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#459]
I'm writing a plugin and want a link in the output, the bot (or Hangouts itself?) isn't making it clickable. My very simplified code is below, I've tried both with and without the `<a>` tag. With `<a>` the entire line is output as-is, the tag isn't actually parsed. How do I make the link clickable in the plugin output?

    segments = [hangups.ChatMessageSegment("Example line: ", is_bold=True),
                hangups.ChatMessageSegment("test"),
                hangups.ChatMessageSegment("\n", hangups.SegmentType.LINE_BREAK),
                hangups.ChatMessageSegment("Full information: <a href=\"https://www.google.com\">https://www.google.com</a>")]
    
    yield from bot.coro_send_message(event.conv, segments)

**Comment by gurumadmat** [comment]
It is Hangouts (mobile versions)  itself. if you want to make it clickable, just remove the tag
and post the link as is.

**Comment by JosephBlock** [comment]
@vaindil change the yield to yield from bot.coro_send_message(event.conv, segments, context={ "parser": True })

**Comment by vaindil** [comment]
Perfect, thank you @JosephBlock !

**Comment by vaindil** [comment]
Hmm, this doesn't seem to work. I don't recall if it ever worked. I'll have to post the links manually. Thank you!
