### ISSUE TITLE
No pictures from Slack to HO in the new SlacRTM plugin

### ISSUE THREAD

**Issue by cd334** [hangoutsbot/hangoutsbot#468]
I updated the hangoutsbot and made the procedure described in the main page. After this all working exept that form Slack to HO there are no pictures only the message coming, only the message. In the log there is no error message. 
From HO to slack the picture transfer working.

**Comment by nylonee** [comment]
There is no way to send pictures from Slack to HO, as it involves changing the bot's profile picture, which is not feasible. Sorry.

**Comment by JosephBlock** [comment]
@nylonee i dont think its the profile picture, rather the uploaded photos.
seems to be broken before the update.

**Comment by cd334** [comment]
it is the normal picture, it has worked with the old SlackRTM plugin very well. The uploaded photos are the problem.

**Comment by cd334** [comment]
I see this at the HO side: Dániel Czigány (xxx): cd334 uploaded a file: larger.jpg But the picture doesn't show up.

**Comment by thannemann** [comment]
I didn't update yet and it's broken for me too. So it may be an Api change or Google change

**Comment by nylonee** [comment]
Sorry. I misread. Reopening

**Comment by pleasantone** [comment]
When I drag a photo to Slack, it does not work.  I believe this used to work for me, will investigate.

**Comment by JosephBlock** [comment]
@pleasantone fix in #472

**Comment by pleasantone** [comment]
I'm an idiot, I forgot images get uploaded! Thanks!

**Comment by jumoog** [comment]
i just see "jumoog (AOSPA): jumoog uploaded a file: chromium-logo.png"
using #472

**Comment by JosephBlock** [comment]
Did you restart the bot?

**Comment by jumoog** [comment]
yes
and enable it
and got "OK, I will now upload images to this Hangout when shared in alwaysparanoid:general."

**Comment by jumoog** [comment]
if i disable it im getting
jumoog (AOSPA): jumoog uploaded a file: allgood@2x.pnghttps://files.slack.com/files-pri/T0CJLBVNG-F0J193NDV/download/allgood_2x.png

**Comment by jumoog** [comment]
Makes sense because its Google can't access the file

**Comment by jumoog** [comment]
16:00:00 INFO plugins.slackrtm: uploading as illuminati-logo.png
16:00:01 ERROR plugins.slackrtm: upload_image: <class 'KeyError'>('sessionStatus')
Traceback (most recent call last):
  File "/root/hangoutsbot2/hangupsbot/plugins/slackrtm.py", line 508, in upload_image
    image_id = yield from self.bot._client.upload_image(image_response, filename=filename)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 473, in upload_image
    ['externalFieldTransfers'][0]['putInfo']['url'])
KeyError: 'sessionStatus'

**Comment by JosephBlock** [comment]
Make sure you're using https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/plugins/slackrtm.py as there were multiple changes

**Comment by jumoog** [comment]
i fixed it #449 

LC_ALL=C.UTF-8 pip3 install -r requirements.txt --upgrade
