### ISSUE TITLE
SlackRTM can't handle syncrooms

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#477]
Currently SlackRTM can't handle syncrooms from HO -> Slack

**Comment by thannemann** [comment]
What happens with them could you synx each ho seperatly

**Comment by nylonee** [comment]
Yes, so it appears that you can't have a syncroom and a slackrtm sync
happening simultaneously. The solution is to disable the syncroom and
connect slackrtm to all the hangouts you want to sync. I'll update the wiki
on this

**Comment by thannemann** [comment]
Is your configuration a single bot or two bots? I noticed that in a single bot configuration it also doesn't echo command results to slack when the bot responds.
