### ISSUE TITLE
Bot unable to load

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#478]
Getting the following error when trying to load a bot. 

23:12:27 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
23:12:27 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
23:12:27 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
23:12:27 ERROR sinks: config.jsonrpc[0].certfile must be configured
23:12:27 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
 File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 194, in _initialize_chat
   params=CHAT_INIT_PARAMS, connector=self._connector
 File "/usr/local/lib/python3.4/dist-packages/hangups/http_utils.py", line 57, in fetch
   .format(res.status, res.reason)
hangups.exceptions.NetworkError: Request return unexpected status: 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hangupsbot/hangupsbot.py", line 164, in run
   loop.run_until_complete(self._client.connect())
 File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
   return future.result()
 File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
   raise self._exception
 File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
   result = next(coro)
 File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 109, in connect
   initial_data = yield from self._initialize_chat()
 File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 198, in _initialize_chat
   .format(e))
hangups.exceptions.HangupsError: Initialize chat request failed: Request return unexpected status: 404: Not Found
Client unexpectedly disconnected:
Initialize chat request failed: Request return unexpected status: 404: Not Found

looks like google just deprecated https://talkgadget.google.com/u/0/talkgadget/_/chat

**Comment by oliveramann** [comment]
Same here,
i have installed it , and after 15 min of playing arround , the same error apears, login not possible ,404 not connecting to server.

raceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "hangupsbot/hangupsbot.py", line 194, in <lambda>
    ).add_done_callback(lambda future: future.result())
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 133, in disconnect
    self._listen_future.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
01:38:42 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 194, in _initialize_chat
    params=CHAT_INIT_PARAMS, connector=self._connector
  File "/usr/local/lib/python3.4/dist-packages/hangups/http_utils.py", line 57, in fetch
    .format(res.status, res.reason)
hangups.exceptions.NetworkError: Request return unexpected status: 404: Not Found

**Comment by lkbowen** [comment]
I can confirm same error here (same output as above).

**Comment by JosephBlock** [comment]
Can you post which branch you are using

**Comment by lkbowen** [comment]
Master.

**Comment by phantomdarkness** [comment]
Same, master

**Comment by vaindil** [comment]
Here as well. I have the master installed, a couple custom plugins too but they have no effect.

**Comment by tdryer** [comment]
Only hangups before version 0.3.0 appears to be affected by Google's API change.

**Comment by lkbowen** [comment]
How do we get hangups 0.3.0+ rolled into this hangoutsbot? Is there a manual fix we can apply in the meantime?

**Comment by thannemann** [comment]
At one point a change in hangups caused a problem with hangupsbot and a major rewrite of hangupsbot would have been needed. So i believe it was forked (not sure of the terminology) and it was kept at that version.

**Comment by tdryer** [comment]
It may be easy enough to patch hangoutsbot's fork of hangups. The equivalent URL appears to be:
https://hangouts.google.com/webchat/u/0/load

**Comment by JosephBlock** [comment]
it is worth a shot to try changing the url. 
Already running bots are not affected (yet)

**Comment by endofline** [comment]
thanks @tdryer for the url :+1: 

need some testers for 84aee94 - you will have to rebuild your hangups

**Comment by JosephBlock** [comment]
@endofline fix worked

**Comment by vaindil** [comment]
@endofline That did it, thank you to you and @tdryer ! I'll help over the next couple days to see what can be done about actually fixing hangups to use the new version, though I've never looked at it so I have no idea what it would entail.

**Comment by JosephBlock** [comment]
It would be a major rewrite unfortunately

**Comment by vaindil** [comment]
Even if it's a major rewrite it should still probably be done. hangups is actively developed, whereas the hangoutsbot/hangups branch hasn't been touched since November, which led to this problem. We've bought some time with this fix. now let's figure it out and do it properly.

_(Remember I haven't looked at any of it yet so I don't know how much of a rewrite we're talking, but within reason I stand by my opinion in favor of doing it.)_

**Comment by lkbowen** [comment]
I can confirm fix works here too. Thank you.

**Comment by dirtydave0221** [comment]
Was able to get this to work as well

**Comment by jfx41** [comment]
I can confirm the fix as well.  In my environment I had to comment out *goslate* and *wolframalpha* for 
@JosephBlock upgrade to work for me (*pip3 install -r requirements.txt --upgrade*).
