### ISSUE TITLE
Documentation: tldr plugin

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#482]
Missing keyword in help:

/bot help tldr
tldr: Adds a short message to a list saved for the conversation using:
   /bot tldr <message>
   All TLDRs can be retrieved by /bot tldr, **single tldr with /bot < number >**
   All TLDRs can be deleted using /bot tldr clear, **single tldr with /bot clear < number >**

=>  single tldr with /bot **tldr** < number >
=> single tldr with /bot **tldr** clear < number >

**Comment by pleasantone** [comment]
This was fixed on Nov24th. e5adcb002a59466816d499ba071a2166397e1ebc
