### ISSUE TITLE
SlackRTM doesn't handle TimeoutError 

### ISSUE THREAD

**Issue by diijkstra** [hangoutsbot/hangoutsbot#483]
I'm having the connection issues with SlackRTM plugin. At least once per day the bot will disconnect with Slack and will not reconnect until restarted. Looking from logs, it seems that TimeoutError is not handled. As a result Hangout connection is alive but Slack is not (and syncing doesn't work).
```
18:52:33 INFO root: Connection lost!
18:53:16 ERROR plugins.slackrtm: SlackRTMThread: unhandled exception: [Errno 60] Operation timed out
Traceback (most recent call last):
  File "/usr/slack-bot/hangupsbot/plugins/slackrtm.py", line 1143, in run
    replies = self._listener.rtm_read()
  File "/usr/slack-bot/hangupsbot/plugins/slackrtm.py", line 429, in rtm_read
    return self.slack.rtm_read()
  File "/usr/lib/python3.4/site-packages/slackclient/_client.py", line 27, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/usr/lib/python3.4/site-packages/slackclient/_server.py", line 109, in websocket_safe_read
    data += "{}\n".format(self.websocket.recv())
  File "/usr/lib/python3.4/site-packages/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3.4/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python3.4/site-packages/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python3.4/site-packages/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.4/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/usr/lib/python3.4/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python3.4/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/usr/lib/python3.4/site-packages/websocket/_core.py", line 479, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python3.4/site-packages/websocket/_socket.py", line 77, in recv
    bytes = sock.recv(bufsize)
  File "/usr/local/lib/python3.4/ssl.py", line 736, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.4/ssl.py", line 625, in read
    v = self._sslobj.read(len or 1024)
TimeoutError: [Errno 60] Operation timed out
```

It looks like it is enough to reconnect to slack, see patch proposal which handles TimeoutError in the same way as ConnectionFailedError.
```
diff --git a/hangupsbot/plugins/slackrtm.py b/hangupsbot/plugins/slackrtm.py
index 4a1485b..e60f8b4 100644
--- a/hangupsbot/plugins/slackrtm.py
+++ b/hangupsbot/plugins/slackrtm.py
@@ -1100,8 +1100,8 @@ class SlackRTMThread(threading.Thread):
             logger.exception('IncompleteLoginError, restarting')
             time.sleep(1)
             return self.run()
-        except ConnectionFailedError:
-            logger.exception('ConnectionFailedError, waiting 10 sec trying to restart')
+        except (ConnectionFailedError, TimeoutError):
+            logger.exception('Connection failed or timeout, waiting 10 sec trying to restart')
             time.sleep(10)
             return self.run()
         except Exception as e:
```

**Comment by cd334** [comment]
It is the same for me.

**Comment by pleasantone** [comment]
@cd334 @diijkstra I haven't seen this problem, can both of you verify the fix works?  I agree with it in theory, just haven't had a test case.

**Comment by cd334** [comment]
I will cheked my logs. After the modification the syncronisation is countinuosly, till now I haven't had this kind of error, so i don't know.

**Comment by diijkstra** [comment]
@pleasantone I'm running with that workaround for more than a week and haven't notice anything suspicious. The timeout did occurred two times in that period and bot has recovered (with ConnectionFailedError on first attempt to reconnect). Unfortunately I don't know how to trigger it, simply killing the network doesn't help. I think it is connected with my server's internet access but it is hard to catch or debug because happens rarely.

On the other hand, I can't think of any better response to TimeoutError, according to Python docs, it is raised when a system function timed out at the system level. So hard to react in any appropriate way. My patch assumes that the error comes from web socket connection but I'm not 100% sure it is always true.

Also, I'm not amused by the way the unhandled exception in SlackRTMThread.run() is taken care of. Basically the only thing which is done is logging it, but exception in the end is ignored/swallowed. As a result here, the connection to slack was dropped and there was no way to reestablish it. I think, the bot should quit/crash with error on such unhandled exceptions instead swallowing them. That way, the external watch dog can try to rerun the application.

**Comment by pleasantone** [comment]
I agree, plugin should restart or die.

@errror your thoughts?

**Comment by pleasantone** [comment]
Committed to staging.
