### ISSUE TITLE
How to cange /hobot to /xy

### ISSUE THREAD

**Issue by MTRNord** [hangoutsbot/hangoutsbot#485]
I need to change the /hobot to something else because I want to use it in Channels were are already HO-Bots. How can I do this?

**Comment by gurumadmat** [comment]
Wanted to refer you to the botalias section of the wiki. 
But it seems there is no such section. 

Check out the botalias command. 
/bot botalias /xy

**Comment by MTRNord** [comment]
But when I would do this an I am not the Admin would it only change the alias of the bot that i am Admin of or would change it both bot alias?

**Comment by gurumadmat** [comment]
No you need to ask the admin to do that or give you access.

**Comment by MTRNord** [comment]
ok :+1: thanks i will try to do so

**Comment by MTRNord** [comment]
And how can I remove aliases? (setiijng an alias did work :)

**Comment by MTRNord** [comment]
Nevermind I found the way to do that :)
