### ISSUE TITLE
Simpler Setup for User

### ISSUE THREAD

**Issue by Vikranth-Keerthipati** [hangoutsbot/hangoutsbot#491]
Hello there,

I was wondering if you guys could simply make an interface for the setup of slack and hangouts integration. It would be easier for the user, and less time-consuming. It would be really nice if you guys can do that. But so far, very good work.

**Comment by pleasantone** [comment]
Please be more specific

**Comment by jimsug** [comment]
@Vikranth-Keerthipati which parts of it are most difficult for you at the moment?
