### ISSUE TITLE
add a Update Notifier

### ISSUE THREAD

**Issue by jumoog** [hangoutsbot/hangoutsbot#492]
send defined users a message if a new Version is available

code example:

```
#!/usr/bin/env python3
import version
import urllib2


def updater():

    try:
        # Get latest version number. Wait 3 seconds and break out if
        # there's no response from the server.
        f = urllib2.urlopen("https://raw.githubusercontent.com/hangoutsbot/"
                            "hangoutsbot/master/hangupsbot/version.py", timeout=3)
        s = f.read().split('"')

        if s[1] != __version__:
            print('*******************************************')
            print('              IMPORTANT\n')
            print('      There is a new version available!')
            print('   Get the latest version {} from:\n'.format(s[1][1:])
            print('https://github.com/hangoutsbot/hangoutsbot/')
            print('*******************************************\n')
    except:
        # import traceback
        # print traceback.format_exc()
        pass

```

**Comment by thannemann** [comment]
so this would be run separately from the bot itself.  It would be nice if it could become part of the core code, somehow so it could send messages in hangouts not just to the screen.
it would also be nice if it wasn't hard coded to 'Master" and it could tell what branch you had installed.

**Comment by jumoog** [comment]
i'll add it to the hangoutsbot but im not sure where.

Its a core function or just a plugin?

**Comment by jimsug** [comment]
You can read the remote url and branch from `/.git/config` in the directory you cloned hangoutsbot, so perhaps there's a way that @thannemann's suggestion can be implemented.

**Comment by thannemann** [comment]
@jumoog I believe a plugin would work great so people could use it or not
