### ISSUE TITLE
How can send message to user?

### ISSUE THREAD

**Issue by naechin91004** [hangoutsbot/hangoutsbot#493]
If I want send message some people directly on server.
How can send message.
Hangoutsbot only wait command. But I want send message to user.

ex) when I type below command on server terminal, hangoutsbot send message to user
/bot -u TEST -m Please help.

**Comment by nylonee** [comment]
There isn't currently a way to interact directly with the hangoutsbot server. An alternative is toggling the API plugin and using the [api-send.py](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/tests/api-send.py) test file.
