### ISSUE TITLE
image_linker_reddit plugin no longer able to pull images from gfycat

### ISSUE THREAD

**Issue by Riptides** [hangoutsbot/hangoutsbot#495]
Using any of the triggers which pull an image from gfycat results in the following

`20:30:08 INFO event: len/tx: 11/popcorn.png
20:30:08 ERROR handlers: message: plugins.image_linker_reddit._scan_for_triggers : coroutine
Traceback (most recent call last):
  File "/home/karl/hangoutsbot/hangupsbot/handlers.py", line 259, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/home/karl/hangoutsbot/hangupsbot/plugins/image_linker_reddit/__init__.py", line 50, in _scan_for_triggers
    image_link = re.search("<a href=\"(.*?)\">\\1</a>", str(raw, 'utf-8')).group(1)
AttributeError: 'NoneType' object has no attribute 'group'`

Trigger scraping from imgur still work.

**Comment by redleader36** [comment]
I'm not sure how to make a pull request or anything, but changing line 50 of image_linker_reddit\__ini__.py to the following fixes this issue for me.
`image_link = re.search("href=\"(.*?)\">GIF</a>", str(raw, 'utf-8')).group(1)`

**Comment by nylonee** [comment]
Implemented the fix, thanks @redleader36

**Comment by neon-ninja** [comment]
oh, https://github.com/hangoutsbot/hangoutsbot/pull/550 was to fix this issue too
