### ISSUE TITLE
Comments in config files

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#512]
Is it possible to have comments in `config.json`? I know JSON is pure data, but some method of comments would be awesome. I'm managing a bot for just over 45 groups (250 one-to-one conversations), comments in the config file would help me keep track of what everything is.

**Comment by vaindil** [comment]
I read more about it, and comments in JSON are [explicitly prohibited](https://stackoverflow.com/questions/244777/can-i-use-comments-inside-a-json-file) by several RFC standards. I'll have to come up with something else.

**Comment by gurumadmat** [comment]
You can always add your comments as data. 
conversations": {
   "Ugw5JWGEn_AaABAQ": {
     "autoreplies_enabled": false,
     "name": "The name of the Ho conversation",
    ....

**Comment by vaindil** [comment]
That SO answer mentioned that; it won't mess with the bot? As I mentioned I use this for quite a few Hangouts, I don't want to try it out unless someone tells me I won't break everything. :P

**Comment by gurumadmat** [comment]
It won't as long as the Json is valid.

**Comment by vaindil** [comment]
Awesome. Thank you, I greatly appreciate it!
