### ISSUE TITLE
mentionall access with tags?

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#514]
Is there a way to allow `@all` mentions via tags? I'm new to the concept of tags and I believe I understand the concept, but I'm not sure how I would do that.

I know I can set per-user, per-conversation tags manually in `config.json`, but using tags would be very helpful.

**Comment by gurumadmat** [comment]
For now this is not possible, mention plugin should be extended for that.

**Comment by vaindil** [comment]
I'll work on this as I have time. Thank you!
