### ISSUE TITLE
Global autoreplies even with conversation-specific replies set

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#515]
I run a bot that's handling upwards of 250 1-to-1 conversations and 40 groups. (It's fun, let me tell you....) Because of this, my `config.json` is getting rather unwieldy. Is there a way to set certain autoreplies to be global to ALL conversations even if a given conversation has its own subset of replies? This would greatly simplify my workload; right now I have to copy/paste (or find/replace) the commands to every single customized conversation whenever they change. (I'm making sure that almost never happens. :P )

I have no problem writing this plugin/adapting the existing plugin if necessary, but I want to make sure I'm not reinventing the wheel.

**Comment by nylonee** [comment]
I'm not quite sure what you're trying to do, as the autoreplies plugin is designed to work globally with all hangouts, with the advanced features allowing you to extend that compatibility. See the [autoreply wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin) for more.

Feel free to suggest any new plugins/make changes to the existing plugin too

**Comment by vaindil** [comment]
Right now, global commands work just fine as long as a conversation doesn't have its own per-conversation settings. An autoreply set in the global config is not called if a per-conversation autoreply exists. I wanted to have global replies that work in every conversation _in addition to_ any per-conversation replies.

I'm not very happy with how I wrote it, but I implemented this in my fork yesterday in vaindil/wazebot@7932872.

**Comment by nylonee** [comment]
Ah! You're right, an autoreply that's set as global will be overridden by per-conversation autoreplies.

Taking a look at vaindil/wazebot@7932872, you've implemented a solution which looks good.

I'll leave this open for a bit to gauge interest from others in seeing a solution implemented in the core bot functionality.
