### ISSUE TITLE
slackrtm: Incompatibility with latest SlackClient

### ISSUE THREAD

**Issue by diijkstra** [hangoutsbot/hangoutsbot#516]
Since [this commit](https://github.com/slackhq/python-slackclient/commit/df14f56439e64d4fb75ad43e625c06134f9940bc), `SlackClient::api_call()` returns string instead binary data. As a result calls like that: `json.loads(self.slack.api_call('users.list').decode("utf-8"))` will end up with exception:
`AttributeError: 'str' object has no attribute 'decode``

It can be fixed by removing `.decode("utf-8")` on such calls.

**Comment by nylonee** [comment]
Thanks, I've updated the code in 99262b4ae09f0c029c7896e6eed3bf7a3649729b, maintaining backward compatibility.

**Comment by Terrance** [comment]
Newer versions of SlackRTM forego the client library and just make the API requests themselves, so this shouldn't be an issue any more.
