### ISSUE TITLE
allow hiding of ONE_TO_ONE hangouts from /bot hangouts command

### ISSUE THREAD

**Issue by triune** [hangoutsbot/hangoutsbot#521]
would be really handy :100:

**Comment by gurumadmat** [comment]
https://github.com/hangoutsbot/hangoutsbot/wiki/CONVID-Commands

/bot convfilter type:ONE_TO_ONE

**Comment by nylonee** [comment]
This is included in the convfilter toolset, as gurumadmat pointed out above

**Comment by triune** [comment]
After reading through the documentation, I cannot figure out how to create a custom trigger like !one2one that will internally just call the /bot convfilter type:ONE_TO_ONE command. Could you guys point me in the direction of how to accomplish this @nylonee or @gurumadmat -- cheers.

**Comment by thannemann** [comment]
@triune what is your end goal you have mentioned hiding a command but now you want to create it?

**Comment by triune** [comment]
@thannemann I want to hide the one to one, yes. I am sorry if I misled from my previous response. I am really trying to create a new trigger !groups and have it output the hangouts listed from from /bot convfilter type:GROUP. Does this require me to create a new custom plugin or can this be done in a simpler fashion?

**Comment by thannemann** [comment]
I think you would need a custom plugin but why wouldn't you just use /bot convfilter type:GROUP

**Comment by triune** [comment]
@thannemann in the larger context, I would like to make triggers similar to my proposed !groups trigger that run various different internal commands but they would be much shorter and easier to remember. If hangouts allowed you to recall the last msg with an up arrow key like IRC, this wouldn't be such an issue, but when I want to use the following command repeatedly:

/bot echo UgxeXOj2cHoRw5Axhb14A343kljkl msg

it would be much easier to just type a trigger like:

!c msg

So, I guess I'm trying to figure out how to setup these triggers. I can't imagine the plugin required to do this would be terribly complex, maybe a few lines? If you could get me going, that would be much much appreciated :100:

**Comment by thannemann** [comment]
It would be a custom plugin I think your asking for. I am still learning myself and would need to pull apart a working plugin to try and figure out the needed code.

**Comment by nylonee** [comment]
It sounds like a nice feature to implement into the bot, unfortunately at the moment the only way to bind custom commands is to create a plugin to do it.

**Comment by triune** [comment]
@nylonee could you point in the direction of a current plugin that implements something like this? I really need a primer to get going before I create one.
