### ISSUE TITLE
SlackRTM issue since v2.7.7

### ISSUE THREAD

**Issue by filemaniac** [hangoutsbot/hangoutsbot#526]
Since the commit from [99262b4](https://github.com/hangoutsbot/hangoutsbot/commit/99262b4ae09f0c029c7896e6eed3bf7a3649729b), I'm having issues with issuing certain commands to the bot from either Hangouts or Slack.  Errors seem to indicate that a 'str' is expected but is getting a 'dict' instead.  It is still syncing between Hangouts and Slack, just not allowing for most Slack related commands.

So far, from the Slack end, it responds to `whereami` but throws errors for commands like 
`help`, `listsyncs`, `admins`, `whois <@username>`.  From Hangouts, it responds to all non Slack related commands and to `/bot slacks`, but every Slack related command like `/bot listsyncs` throws the same `TypeError: the JSON object must be str, not 'dict'` that shows in console.

```
12:18:40 ERROR plugins.slackrtm: error in handleCommands: <class 'TypeError'>(the JSON object must be str, not 'dict')
Traceback (most recent call last):
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 374, in get_slackDM
    self.dminfos[userid] = json.loads(self.slack.api_call('im.open', user = userid).decode("utf-8"))['channel']
AttributeError: 'dict' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1145, in handle_reply
    self.handleCommands(msg)
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 721, in handleCommands
    userID = self.get_slackDM(msg.user)
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 376, in get_slackDM
    self.dminfos[userid] = json.loads(self.slack.api_call('im.open', user = userid))['channel']
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'dict'
```

```
12:30:25 ERROR plugins.slackrtm: error in handleCommands: <class 'TypeError'>(the JSON object must be str, not 'dict')
Traceback (most recent call last):
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 374, in get_slackDM
    self.dminfos[userid] = json.loads(self.slack.api_call('im.open', user = userid).decode("utf-8"))['channel']
AttributeError: 'dict' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1145, in handle_reply
    self.handleCommands(msg)
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 721, in handleCommands
    userID = self.get_slackDM(msg.user)
  File "/root/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 376, in get_slackDM
    self.dminfos[userid] = json.loads(self.slack.api_call('im.open', user = userid))['channel']
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'dict'
```

**Comment by nylonee** [comment]
What version of SlackClient do you have installed?

**Comment by filemaniac** [comment]
I ran `pip3 install -r requirements.txt --upgrade` after I git pulled the latest version yesterday and it showed that the SlackClient was already up to date:

`Requirement already up-to-date: slackclient>=0.16 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 18))`

This is the version it shows in PKG-INFO under /usr/local/lib/python3.4/dist-packages/slackclient-1.0.0.egg-info (if I need to look elsewhere, let me know):

```
Metadata-Version: 1.0
Name: slackclient
Version: 1.0.0
Summary: Python client for Slack.com
Home-page: http://github.com/slackhq/python-slackclient
Author: Ryan Huber
Author-email: ryan@slack-corp.com
License: MIT
Description: UNKNOWN
Platform: UNKNOWN
```

**Comment by TheSleepySlee** [comment]
Facing same issue on fresh install from today.
hangoutsbot is answering with below whan I try to list the channels:
`slack_channels TypeError: the JSON object must be str, not 'dict'`

console is showing this:
`
22:03:38 INFO event: len/tx: 38//bot slack_channels **XXX**
22:03:38 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): slack.com
22:03:38 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): slack.com
22:03:39 ERROR commands: RUN: slack_channels
Traceback (most recent call last):
  File "/volume3/**XXX**/hobot/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 461, in update_channelinfos
    response = json.loads(self.slack.api_call('channels.list').decode("utf-8"))
AttributeError: 'dict' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume3/**XXX**/hobot/hangoutsbot/hangupsbot/commands/__init__.py", line 178, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.4/asyncio/tasks.py", line 103, in coro
    res = func(*args, **kw)
  File "/volume3/**XXX**/hobot/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1412, in slack_channels
    slackrtm.update_channelinfos()
  File "/volume3/**XXX**/hobot/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 463, in update_channelinfos
    response = json.loads(self.slack.api_call('channels.list'))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'dict'
22:03:40 INFO event: eid/dt: **XXX**/2016-03-06 22:03:39
22:03:40 INFO event: cid/cn: **XXX**/**YYY**
22:03:40 INFO event: c/g/un: **ZZZ**
22:03:40 INFO event: len/tx: 65/slack_channels TypeError: the JSON object must be str, not 'dict'


`

**Comment by nylonee** [comment]
Thanks for info. See #530 for PR addressing this issue (thanks @xdgc)

**Comment by filemaniac** [comment]
Thanks!  Loaded the changed slackrtm.py for now and restarted the bot.  Preliminary testing looks good for both Slack and Hangouts queries to the bot (aka responding normally to the Slack related commands).

**Comment by TheSleepySlee** [comment]
yes, seems to work for me too. No extensive testing, however sync works on
fresh install.

2016-03-07 18:05 GMT+01:00 filemaniac <notifications@github.com>:

**Comment by xdgc** [comment]
This is great to hear — has anyone tested this change under an _older_ release of SlackClient? I haven't tested against regression. "It should just work...."

**Comment by JosephBlock** [comment]
@xdgc looks to be backwards compatible. Have not tested it yet.  But being on current version also helps
