### ISSUE TITLE
[telesync] markup-like message are not forwarded

### ISSUE THREAD

**Issue by j16sdiz** [hangoutsbot/hangoutsbot#539]
Step to reproduce:
1. Setup telesync
2. In hangout side, type  `# * this is a test`

Excepted result:
The text is forwarded to telegram

Actual result:
No text is found.

More Information:
Remove the `*`, the message can be forwarded correctly.

**Comment by makiftasova** [comment]
Well, it happens because telesync sends markdown formatted messages to chat group. (* is a  valid markdown tag) 

It could be fixed changing all telesync messages to html formatting

**Comment by makiftasova** [comment]
Pull request #561 should fix this
