### ISSUE TITLE
WARNING root: Adding fallback User

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#541]
I've been getting this error in the logs a lot lately. What does it mean? I see no other errors in the log.

    WARNING root: Adding fallback User: <hangups.user.User object at 0x7fc9491105f8>

**Comment by endofline** [comment]
this is a behaviour of the hangups library (more info: #102) and is more likely to show up when more users are in communication with the bot. it is a non-critical warning and not actually an error, and can be ignored
