### ISSUE TITLE
slackrtm returning errors

### ISSUE THREAD

**Issue by nerdlinger** [hangoutsbot/hangoutsbot#544]
/bot slack_listsyncs returns error:

slack_listsyncs TypeError: the JSON object must be str, not 'dict'

**Comment by nvrrvn** [comment]
Check #516

**Comment by nerdlinger** [comment]
Got that code and still returns errors. Today I saw:

_**slack_channels** TypeError: the JSON object must be str, not 'dict'_

Currently configured syncs work, but failure of commands makes configuration difficult or impossible.

This should have been tested better. Please make sure all slack* commands work properly before pushing plugin updated to master.

**Comment by JosephBlock** [comment]
I tested slack_channels just now and it was successful. @nerdlinger can you provide more info, the version numbers for slackclient and hangoutsbot

**Comment by nerdlinger** [comment]
Hangupsbot 2.7.7
slackclient 1.0

Maybe a compatibility problem with the latest version of slackclient?

**Comment by JosephBlock** [comment]
@nerdlinger could you clone the staging branch into a new directory and see if the error still exists
`git clone https://github.com/hangoutsbot/hangoutsbot.git --branch staging --single-branch`

**Comment by nerdlinger** [comment]
I can confirm that seems to have corrected the problems.

**Comment by cd334** [comment]
@JosephBlock i had the same error with the master version, but the staging version works correct
