### ISSUE TITLE
Slack to Many Hangouts

### ISSUE THREAD

**Issue by JosephBlock** [hangoutsbot/hangoutsbot#549]
SlackRTM sync one slack channel to many hangouts
`hangout <> Slack <> hangout`
What will not work
`Slack <> hangout <> Slack`
Sending to a second Slack currently not possible as the thread only knows its own Slack team

Fix is in PR #506

**Comment by Terrance** [comment]
> `hangout <> Slack <> hangout`

You should in fact use SlackRTM to sync Slack to one of the hangouts, then use syncrooms to bridge the other hangout: `Slack <--SlackRTM--> HO1 <--syncrooms--> HO2`

> `Slack <> hangout <> Slack`

v3 SlackRTM should support this as two separate syncs off of the hangout.
