### ISSUE TITLE
Suggestion: Add input sanitization (Can crash bot at will)

### ISSUE THREAD

**Issue by FelixAurelius** [hangoutsbot/hangoutsbot#564]
The bot can be intentionally crashed by sending the "diceroll" command with insane values (99999999999999999999999d9999999999999999999 for example). It seems to be using an integer literal, which is somewhat optimistic.

It might be worthwhile to sanitize or otherwise limit input values to a certain, configurable range of possible valid values, in order to prevent malicious crashing of the bot.

**Comment by makiftasova** [comment]
I've added a few checks, and sent a pull request for this issue.

simply, you can't enter something bigger than 99d9999 any more.

**Comment by pleasantone** [comment]
Does this crash the entire bot or just the diceroll plugin?

**Comment by nylonee** [comment]
See #578 for the PR

**Comment by nylonee** [comment]
Fixed the issue in https://github.com/hangoutsbot/hangoutsbot/commit/ac2767d3250cc70ff6eb77fa5902b8fb3ed27805, staged for push into master.
