### ISSUE TITLE
API plugin server not starting

### ISSUE THREAD

**Issue by rithvikvibhu** [hangoutsbot/hangoutsbot#568]
The certificate is valid and exists in the right location. Have this in config.json (the real one):
```
  "api_key": "test",
  "api":
  {
      "certfile": "~/hangoutsbot/server.hangoutsbot.pem",
      "name": "aioserver.cloudapp.net",
      "port": 9002
  }
```
The `api-send.py`, `POST`, and `GET` methods return Connection Refused.
`lsof -Pnl +M -i4` doesn't show any port bound to python3 (Apart from the 3 open connections to Google). Also, none of the other processes use the port.
Port 9002 is open, no firewall

Happened to anyone before?

**Comment by noahbeach** [comment]
```
"api_key": "test",

"api": [
  {
    "certfile": "blah",
    "name": "blah",
    "port": blah
  }
],
```

**Comment by rithvikvibhu** [comment]
Well that worked. Sort of. It seems it is trying to bind to the public IP and I can't find it being set anywhere.
So i get the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/base_events.py", line 870, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/rithvik/hangoutsbot/hangupsbot/sinks/__init__.py", line 168, in aiohttp_started
    server = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 874, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('168.61.170.37', 9002): cannot assign requested address
```

**Comment by pleasantone** [comment]
Bind to 0.0.0.0 instead?

**Comment by rithvikvibhu** [comment]
@pleasantone "and I can't find it being set anywhere." I know my way around web servers. Just that I couldn't find it in config.json.

**Comment by nylonee** [comment]
@rithvikvibhu Have you resolved the latter error? If not, would it be possible to create a new thread with your error. Thanks =)
Closing this thread now as the original issue has been resolved.
