### ISSUE TITLE
New to Github - Newbie question on enterprise usage of this Hangout-bot integration

### ISSUE THREAD

**Issue by krishnatgkk** [hangoutsbot/hangoutsbot#579]
Hi

I really appreciate the Project you have put forward to integrate Google Hangouts with bots. i am also looking for a similar project but from enterprise usage standpoint.

We have google Hangouts in our company and I want to use this Hangout bot for integration in our enterprise. I have 2 questions

1)  can i integrate into company wide Hangout
2) can i develop my own plugins and use in our enterprise and I cannot open source these plugins as they are pretty much enterprise use.

I am new to understand Licensing of this kind of open source projects.

**Comment by pleasantone** [comment]
The code is licensed under the GPLv2, which, in short, says you need to make the source code for any changes freely available. However if you write entirely new plugins, you  have no obligation to redistribute the source code to those plug-ins .
