### ISSUE TITLE
slackRTM Type error

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#580]
I am getting string type errors when I am trying to do any configuration with the bot and slackrtm. (plugin from master branch)  This is only an example  i have tried two different new private channels

21:18:16 ERROR plugins.slackrtm: error in handleCommands: <class 'TypeError'>(byte indices must be integers, not str)
Traceback (most recent call last):
  File "/home/XXXX/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1144, in handle_reply
    self.handleCommands(msg)
  File "/home/XXXX/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 752, in handleCommands
    channelname = '#%s' % self.get_channelname(msg.channel)
  File "/home/XXXX/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 475, in get_channelname
    self.update_channelinfos()
  File "/home/XXXX/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 466, in update_channelinfos
    channels = response['channels']
TypeError: byte indices must be integers, not str

**Comment by ckanoab** [comment]
Having the same issue. Have tried new config and memory files and regenerated key

**Comment by nylonee** [comment]
What version of hangoutsbot are you guys running?

**Comment by thannemann** [comment]
Bot Version: 2.7.5
pyslack-real==0.5.3

@nylonee  odd part is one bot on the box works one errors, both run by the same user, just using two different config and memory files, and api/slack teams and ports for the cert

**Comment by nylonee** [comment]
@thannemann Could you send me the output of `/bot config get slackrtm`? Of course take out the API token and the admin ID's, I'm just interested in the structure of your config.

Ensure that the slackrtm config is wrapped in a `[]` as per the [wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/SlackRTM-Plugin#configuration)

**Comment by laurentdinclaux** [comment]
Same here, I cannot setup a new sync:

```
/bot slack_listsyncs
slack_listsyncs TypeError: byte indices must be integers, not str

/bot slack_channels nc
slack_channels TypeError: byte indices must be integers, not str

/bot config get slackrtm
config slackrtm:
[
 {
   "admins": [
     "U04MN6C3T",
     "U0DARCYJZ"
   ],
   "key": "xoxb-xxxxxxxx-xxxxxxxxxxxxxxxxxxxxx",
   "name": "nc"
 }
]
```

**Comment by JosephBlock** [comment]
@laurentdinclaux are you on the most recent version of the bot and slackclient?

**Comment by laurentdinclaux** [comment]
Sorry, forget it. I pulled last version and had to solve a few python issue and it is now ok.

if @thannemann doesn't show up here, I think this bug can be closes

**Comment by thannemann** [comment]
Sorry this should have been closed awhile ago I had sent a PM with the
requested information to @nihal when he asked for it.
