### ISSUE TITLE
telesync doesn't send from ho to tg

### ISSUE THREAD

**Issue by MeDeVILe** [hangoutsbot/hangoutsbot#581]
Sync from tg to ho is working perfectly but the other way around there is error
`event: len/tx: 1/message
~/git/hangoutsbot/hangupsbot/plugins/telesync/__init__.py:595: RuntimeWarning: coroutine 'Bot.sendMessage' was never awaited
  disable_web_page_preview=True)
16:30:12 ERROR handlers: message: plugins.telesync.thunk : coroutine
Traceback (most recent call last):
  File "~/git/hangoutsbot/hangupsbot/handlers.py", line 259, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 208, in coro
    res = yield from res
  File "~/git/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 595, in _on_hangouts_message
    disable_web_page_preview=True)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator`

Is it something on my site or is this a conflict withe API 2.0?

**Comment by nylonee** [comment]
@MeDeVILe there have been several updates to the telesync plugin since your error. Have you tried updating, is the error still persisting?

**Comment by makiftasova** [comment]
Also which version of telepot you are using atm. Current telesync is not compatible with telepot8.0 or newer

**Comment by MeDeVILe** [comment]
Oh yes it was a problem with telepot8.0
After downgrade all is working great. I forgot to write earlier.
