### ISSUE TITLE
Telesync syncs messages twice in TG -> HO direction after loosing connection

### ISSUE THREAD

**Issue by 1110101** [hangoutsbot/hangoutsbot#582]
[crashlog.txt](https://github.com/hangoutsbot/hangoutsbot/files/273221/hangoutsbot.txt)

Hangoutsbot loses connection to google and after a automated restart everything is synced twice in TG -> HO direction:

> 2016-05-19 19:23:09 INFO plugins.telesync: [TELESYNC] Telegram message forwarded: Siehe bild to: [IDs REMOVED]
> 2016-05-19 19:23:09 INFO event: eid/dt: [IDs REMOVED]/2016-05-19 19:23:09
> 2016-05-19 19:23:09 INFO event: cid/cn: [IDs REMOVED]/[HO TITLE]
> 2016-05-19 19:23:09 INFO event: c/g/un: [IDs REMOVED]/[IDs REMOVED]/[BOT NAME]
> 2016-05-19 19:23:09 INFO event: len/tx: 18/[ME]: Siehe bild
> 2016-05-19 19:23:09 INFO plugins.telesync: [TELESYNC] Telegram message forwarded: Siehe bild to: [IDs REMOVED]
> 2016-05-19 19:23:09 INFO event: eid/dt: [IDs REMOVED]/2016-05-19 19:23:09
> 2016-05-19 19:23:09 INFO event: cid/cn: [IDs REMOVED]/[HO TITLE]
> 2016-05-19 19:23:09 INFO event: c/g/un: [IDs REMOVED]/[IDs REMOVED]/[BOT NAME]
> 2016-05-19 19:23:09 INFO event: len/tx: 18/[ME]: Siehe bild

**Comment by gurumadmat** [comment]
@1110101 is this issue resolved then?

**Comment by 1110101** [comment]
@gurumadmat please see https://github.com/1110101/hangoutsbot/commit/88c94f1d50a157da113c40f869741b5202356195
Lines 482 - 536.

This works for me, but i have no real experience with python so probably its overkill and or really bad coding.
