### ISSUE TITLE
Sending commands via API without the command itself being shown in the chat

### ISSUE THREAD

**Issue by Galtwise** [hangoutsbot/hangoutsbot#586]
For example, if I want to send '/bot ping' to my bot, I would like it to show just 'pong', not the '/bot ping' part. Is that possible?

**Comment by pleasantone** [comment]
Not possible.

**Comment by notmikeb** [comment]
Need to re-write the plugin
change the admin command to message
and check the event.text whether it is 'ping' or not
when it is 'ping', send the 'pong' back

**Comment by jpakusch** [comment]
But according to the Help file this should be possible:

> Provides a method for external services to execute commands on the bot
Furthermore, the Hint that it would be possible to add the bot's ID to the list of admins lets me assume this should be possible.
I am confused. Why is it not possible? 
What i want is trigger a self-written plugin "quote.py" with the command "/bot quote".
Is there any other way to execute a Function within this self-written plugin (or any other plugin) ?
