### ISSUE TITLE
Synced messages from slackrtm are not in correct order

### ISSUE THREAD

**Issue by redkite** [hangoutsbot/hangoutsbot#587]
Messages that are synced with slackrtm from Slack to Hangouts are not kept in proper order. If two or more messages are submitted in a very short period (before the first message is sent to hangouts the second already is received by the bot) the order of messages sent to Hangouts is random.

As stated in #560 this issue seems to be fixed in current hangups versions, but not in the hangups fork used by hangoutsbot.

**Comment by Terrance** [comment]
As we're now using a current version of hangups, this should hopefully be resolved.
