### ISSUE TITLE
Feature Request: SlackRTM to SlackRTM

### ISSUE THREAD

**Issue by bobpaul** [hangoutsbot/hangoutsbot#589]
The SlackRTM plugin supports multiple slack teams, but only allows syncing to hangouts. It would be nice to be able to sync one slack channel directly to a slack channel on another team.

**Comment by Terrance** [comment]
Ultimately this is a bot for Hangouts -- even with the new chatbridge framework introduced in v3, this still requires any external chat to bridge via a hangout, and this is unlikely to change.
