### ISSUE TITLE
SlackRTM not forwarding attachments

### ISSUE THREAD

**Issue by SneakyWhoami** [hangoutsbot/hangoutsbot#594]
I'm suggesting one issue here but if valid it could be two separate things.
First symptom is images:
writing an image url in slack unfurls it in slack but hangoutsbot doesn't post the image into hangouts - it would be nice if it did. It **looks** like it's been considered, maybe something is lacking in the underlying python slackclient **or something**, no?:

```
                if msg.file_attachment:
                    if sync.image_upload:
                        self.loop.call_soon_threadsafe(asyncio.async, self.upload_image(sync.hangoutid, msg.file_attachment))
                    else:
                        # we should not upload the images, so we have to send the url instead
                        response += msg.file_attachment
                self.bot.send_html_to_conversation(sync.hangoutid, response)
```

second thing:
I have a more complicated attachment with emoji, several fields, a thumbnail and a link. when i "say" it in the channel I get this response in console and nothing in hangout:

```
11:46:00 ERROR plugins.slackrtm: error parsing Slack reply: <class 'UnboundLocalError'>(local variable 'tag_from_slack' referenced before assignment)
Traceback (most recent call last):
  File "/home/sneaky/slack/bridge/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1135, in handle_reply
    msg = SlackMessage(self, reply)
  File "/home/sneaky/slack/bridge/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 240, in __init__
    self.tag_from_slack = tag_from_slack
UnboundLocalError: local variable 'tag_from_slack' referenced before assignment
```

Even in the case of an error I would hope to see the attachment fallback text at the very least. I have tried it with a couple of different messages with attachments and every time the message doesn't make it to hangouts.

**Comment by Terrance** [comment]
v3 has been released and includes a rewritten SlackRTM plugin, which supports the fallback of an attachment and will send that to Hangouts.
