### ISSUE TITLE
Re-add license to directory

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#600]
As per #579, the bot license file seems to have been lost in cyberspace. GPLv2 should be re-added to the repo.

**Comment by jumoog** [comment]
it's possible to add LGPL too?

**Comment by pleasantone** [comment]
What does LGPL get you?  I was actually going to suggest we move to AGPL v3.0 for stricter terms.

**Comment by jumoog** [comment]
i want use it commercial for internal communication without releasing/provide the sources

**Comment by nylonee** [comment]
I'm under the impression that GPLv3 allows for modification of the code without releasing the source code, as long as you use it for internal purposes. See excerpt from the [GPL website](https://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic):

> The GPL does not require you to release your modified version, or any part of it. You are free to make modifications and use them privately, without ever releasing them. This applies to organizations (including companies), too; an organization can make a modified version and use it internally without ever releasing it outside the organization.

Happy to use GPLv3

**Comment by makiftasova** [comment]
I think bot is used as a software service over network thus I  prefer AGPLv3 instead of plain GPLv3 (see https://www.gnu.org/licenses/why-affero-gpl.en.html ) also I  think there should be a notice regarding if the plugins are covered by bot's license or not

**Comment by pleasantone** [comment]
I totally agree.

**Comment by jumoog** [comment]
you can't change the license without asking @xmikos

**Comment by edgemaster** [comment]
The original License file was lost in commit 7bb45f4b
