### ISSUE TITLE
"no subscribe" for a specific conversation

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#601]
Feature request for subscribe plugin: allow to block all subscribe notification (mention will still work) for a conversation.
Example: you have a "social" very noisy hangout, you do:
/bot nosub on [conv_id]
and bot will no longer notify you of your subscribed words in that conv_id
/bot nosub off [conv_id]
to remove that.
If conv_id is not specified, then take current conversation

That might be easier, faster to implement than:
https://github.com/hangoutsbot/hangoutsbot/issues/278
even if it does not replace it completely (subscribe specific keyword per conv_id is still interesting)

**Comment by endofline** [comment]
latest staging and v3 now allows you to `/bot optout <convid>` - preliminary documentation for **per-conversation optout** at #776
