### ISSUE TITLE
Hangouts now supports kicking people from hangouts 

### ISSUE THREAD

**Issue by Galtwise** [hangoutsbot/hangoutsbot#602]
Is this something we can implement in hangoutsbot? Issue has already been mentioned at hangups: https://github.com/tdryer/hangups/issues/250#issuecomment-232221107

**Comment by JosephBlock** [comment]
This would only be possible when it is added into hangups AND hangoutsbot is upgraded to latest version of hangups.

**Comment by bing0USMC** [comment]
Need to find out how to keep the bot from being kicked out

**Comment by wishbone1138** [comment]
Unfortunately I don't think there is any way to keep anyone from being kicked out right now.  There are no moderator options that I can see.  All you could do is have multiple bots that try to cover each other.  If they were fast enough you might be able to kick someone before they could kick both.  That's the only way I can see to add actual protection to a hangout.  I'd love to see this implemented, I could work on the code, but it would be great if hangups wrote all the api calls first.

**Comment by Galtwise** [comment]
Hangupsbot is updated to work with kicking

**Comment by Galtwise** [comment]
Hangups is**

**Comment by nylonee** [comment]
@endofline Is there any chance that the framework could be updated to work with kicking mechanism?

**Comment by FrNico** [comment]
hangups: https://github.com/tdryer/hangups/issues/250

**Comment by beer-matt** [comment]
Has there been any progress on this? When the kick ability is implemented I would also suggest enhancing other functions to take advantage of it e.g.:-
* Namelock: optionally kick anyone that changes the conversation title
* Monitoradds: optionally kick the newly added person, also optionally kick the unauthorised person that added someone else
* Add ability to monitor for changes to conversation history status by non-admin (and restore if it is changed), and optionally kick person that changed status

**Comment by JosephBlock** [comment]
To implement this, the base bot code would need an almost entire rewrite to support the newest version of hangups

**Comment by jumoog** [comment]
maybe just write a wrapper?

**Comment by tapionx** [comment]
i need this! :)

**Comment by Terrance** [comment]
Convtools has been updated to support real kicking of users via `/bot kick`.

Hangouts already provides a mechanism to avoid the bot being removed: join by link.  If a user joins via the hangout invite link, they cannot remove other users.  In the ideal setup, all non-admins would only join a hangout via link.
