### ISSUE TITLE
How to get Location of Bot in Plugin

### ISSUE THREAD

**Issue by MTRNord** [hangoutsbot/hangoutsbot#603]
Is there a way to get the location of the Bot from inside an Plugin script?

**Comment by nylonee** [comment]
Consider using [this](http://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib) to find the local IP address (although it may not work in all cases). At the moment there isn't a way to find the location of a bot through the framework.

**Comment by MTRNord** [comment]
Sorry I didn't write it correct back than. It was more like "How do I get the actual path where the bot is installed on the file system"

**Comment by nylonee** [comment]
I think `os.path.dirname(__file__)` should do the trick

**Comment by MTRNord** [comment]
I will try that :) thanks
