### ISSUE TITLE
Execute commands issued in Telegram

### ISSUE THREAD

**Issue by nerdlinger** [hangoutsbot/hangoutsbot#604]
SlackRTM recently updated to allow issuing bot commands in Slack channels. See a0137eb3831810c6ca67ad58b16136171f8c75f2.

Would be good to have the same functionality in Telesync.

**Comment by Terrance** [comment]
This is now supported in v3, assuming you have completed the profile sync steps to map a Telegram user back to the corresponding Hangouts user.
