### ISSUE TITLE
Security issue: send message to admin when bot is admin

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#608]
When bot is admin of itself (so bot id is configured in admins), and bot try to send a message to admins, for example with plugin botaddnotif, a query is done to lookup admin IDs, and then to lookup conversations for each admin IDs.

Somehow for bot IDs, a more or less random conversation is picked (seems to be last GROUP conversation bot add with some people and all left except 1).

Fix: bot should not lookup for his own conversation when sending a message to his own id, message should be disregarded.

**Comment by FrNico** [comment]
Looking for logs, I found out that bot rememberd that 1-to-1 conv with that random user about a week ago, but can't find any other actions with that user at the same time:

2016-07-14 22:08:46 INFO handlers: reprocessor uuid found: 501b38ee-bda3-4f4e-9115-fc5cdd138855 coroutine=False
2016-07-14 22:08:46 INFO root: get_1on1: remembered Ugwl-hrWx1tYROIH3Ch1AaABAagB_cDLDA for 115613491031275660274
2016-07-14 22:08:46 INFO config: /home/blablausername/blablafoldername/memory.json write 0.448244571685791
2016-07-14 22:08:46 INFO handlers: reprocessor uuid found: d16225d7-898a-41f0-a0c8-428ba9afa086 coroutine=False

Note: 115613491031275660274 is my bot id

**Comment by Terrance** [comment]
This isn't a supported configuration, the bot should never be an admin of itself -- this is a security issue as messages from non-HO-identified users (e.g. from syncs without profile mapping) are processed under the bot's user, which would effectively grant them admin permissions (in v3, commands are only available to identified users, which should mitigate this for the most part).
