### ISSUE TITLE
Executing shell commands possible

### ISSUE THREAD

**Issue by jpakusch** [hangoutsbot/hangoutsbot#610]
Hello Everybody,

i am just playing around with this amazing project.
It is really fun.
Did anyone already realized a possibility to trigger a shell command on the Raspi the Bot is running on via chat keyword?
Here are some requirement describing what i would like to do:
- I would really appreciate it if it was possible to trigger a command without the /bot prefix. Is that possible at all?
- I would like to give some parameters to the shell command via hangouts message
- It would be great if i could return some "results text" from the script/command back to hangouts.

Thank you very much for your help/ideas how to adopt the bot fulfilling my needs.

greetings, Jan

**Comment by pleasantone** [comment]
Spawn plugin on staging branch.

**Comment by jpakusch** [comment]
Great,
thank you for your fast reply!
sounds like this is exaclty what i need.
But i cannot configure it properly.
when i add the example from the wiki page exactly as inserted below and reload the config the bot sais it expects a ',' just after the "fortune".
Can anyone give me a hint?
I inserted the Example just at the very ent of the config.json (but before the last '}' of course and put an additional  ',' after the last parameter in config.json

>     "spawn": {
        "home": "/nonstandard/home/directory",
        "commands":
            "fortune": {
                "command": ["/usr/games/fortune"]
            },
            "motd": {    <---this is a deliberately unsecure example
                "command": ["/bin/cat", "/etc/motd", "--"],
                "allow_args": true
            },
            "stock-info": {
                "command": ["/home/portfolio/stock-info", "--"]
                "home": "/home/portfolio",
                "allow_args": true
        }
    }

**Comment by onaclov2000** [comment]
I *could* be wrong, but you'll need {} around fortune, through the end of stock-info if you use a JSON Linter it'll help you find your issues,

http://jsonlint.com/


(you'll have to wrap whatever you're using in jsonlint with {} just to make sure it's valid starting out. I.E.
```

{
	"spawn": {
		"home": "/nonstandard/home/directory",
		"commands": "fortune": {
			"command": ["/usr/games/fortune"]
		},
		"motd": { < -- - this is a deliberately unsecure example "command": ["/bin/cat", "/etc/motd", "--"],
			"allow_args": true
		},
		"stock-info": {
			"command": ["/home/portfolio/stock-info", "--"]
			"home": "/home/portfolio",
			"allow_args": true
		}
	}
}
```

Also it's not terribly fancy but i added a plugin that retrieves a stock symbol price/etc when you type /bot stock <symbol>

https://github.com/onaclovtech/hangoutsbot/blob/master/hangupsbot/plugins/stock.py

Good luck!

**Comment by pleasantone** [comment]
OK, see that whole part about “<— this is a deliberately insecure example… that means DON'T DO THAT.
I’ve updated the wiki to remove the example of “stupid”, you’re own your own if you want to hang yourself.

You’re missing the “{“ after commands and before fortune, and for god sakes, remove the MOTD stanza or your system will get owned.
