### ISSUE TITLE
Android hangouts sync with syncouts

### ISSUE THREAD

**Issue by azack** [hangoutsbot/hangoutsbot#614]
Similar to the issue being fixed in SlackRTM with #612, the same issue exists with the syncrooms/syncouts plugin: two hangouts synced via this plugin will sync an image sent from desktop hangouts fine, but an image from android (e.g. a screenshot) will not sync from one hangout to the other.  Rather, a blank message from the bot appears, and an error is logged:

```
2016-07-27 15:03:48 ERROR handlers: message: plugins.syncrooms._handle_incoming_message : coroutine
Traceback (most recent call last):
  File "/home/hangupsbot/hangupsbot/hangupsbot/handlers.py", line 259, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/home/hangupsbot/hangupsbot/hangupsbot/plugins/syncrooms.py", line 184, in _handle_incoming_message
    image_id = yield from bot._client.upload_image(image_data, filename=filename)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 473, in upload_image
    upload_url = (json.loads(res1.body.decode())['sessionStatus']
KeyError: 'sessionStatus'
```

Observed in latest staging ce0255fa561372c29abd49b253cd01b593c87564

**Comment by pleasantone** [comment]
@errror FYI

**Comment by nylonee** [comment]
Interestingly, no matter what file extension I append to the url, the image comes out in the original file extension that it was sent in. In addition, appending the file extension to the desktop link won't change the format.

From this I made a hacky fix, to add `.gif` onto the end of every link that gets processed. The end results all seem to follow its original image format, without a loss of quality.

**Comment by Terrance** [comment]
Looks like this was resolved (by faking the extension), and should still be handled via the image plugin.
