### ISSUE TITLE
New user - best way to keep reloading config.json to get externally edited version be used for answers?

### ISSUE THREAD

**Issue by Karantula** [hangoutsbot/hangoutsbot#617]
COMPLETE EDIT: My question was too broad, and I have a better idea on how to ask it: basically, which plugin is the best to use in order to read config.json every 5 secs or so for updates?

**Comment by gurumadmat** [comment]
Why would you need to do this?

you could write an external script that sends the reload command to the bot every 5 seconds.

**Comment by Karantula** [comment]
If I am editing json file separately, literally in a text editor, to add new values, to keep it getting updated all the time.

I guess my problem is - since I have been doing one-file Python so far - I do not know the first thing on writing external scripts and adding them to an existing project. What would be the best source/good read to get a grasp on this?

**Comment by gurumadmat** [comment]
You'd better just issue a '/bot reload' command every time you save the config file, this way you can see whether you have made any mistakes and the config file has loaded or not.

**Comment by Karantula** [comment]
That is what I am doing right now. Ok, thanks.
