### ISSUE TITLE
Create new hangout by link

### ISSUE THREAD

**Issue by noirwave** [hangoutsbot/hangoutsbot#619]
Hello.
I'm going to use my bot as broadcaster and i need to add new hangouts to my bot.
I generated a link to start chat with bot https://hangouts.google.com/chat/person/117077625151508209249?key=V_pv5mC8LDN9
So i'm expecting new hangout after "/bot hangouts" when user follow this url, but there's no new hangout
When user type any message hangout appears.
I need to create new hangout without typing messages from user to bot.
Is it possible?

**Comment by gurumadmat** [comment]
I suggest you start the conversation not by link, but rather try to start it from the bot. This way the bot creates the hangout and not the user. 
When you do it via link the hangout is created by the user and bot has no idea of it.
