### ISSUE TITLE
Is there any plugin for auto apply invite and send welcome message?

### ISSUE THREAD

**Issue by noirwave** [hangoutsbot/hangoutsbot#620]
Need to adding user automaticaly when it sended an invite to bot.
Bot must apply this invite and send welcome message like "Hi! You are in broadcasting now!"

**Comment by noirwave** [comment]
I have founded autoreply plugin with this feature
https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin#advanced-features
But didn't understood how it works.
Please help.

**Comment by sabinico** [comment]
Take a look on this:

https://github.com/hangoutsbot/hangoutsbot/wiki/Framework-2.7#Bot_will_Autocreate_Private_Channels
https://github.com/hangoutsbot/hangoutsbot/wiki/Configuration#autocreate1to1

**Comment by jpakusch** [comment]
Thats fairly easy when you know how ;)
It is just an autoreply you have to add:
`/bot autoreply add [["JOIN"],"Hello {participants_namelist}, you are in broadcasting now"]`
And the bot will greet the new person with full name.
