### ISSUE TITLE
Telesync plugin staging pictures HO->TG not working

### ISSUE THREAD

**Issue by cd334** [hangoutsbot/hangoutsbot#630]
For me the pictures from HO to TG is not working currently with the staging version of telesync.
@makiftasova

**Comment by cd334** [comment]
I run the pip3 upgrade, and the switched back to master, and the HO-TG picture also broken the link, whitch was sent from ho to tg also not work any more, the pip3 upgrade updated the following things:
Successfully installed aiohttp jsonrpclib-pelix beautifulsoup4 google-api-python-client hangups pyslack-real emoji multidict oauth2client

**Comment by cd334** [comment]
UPDATE: from the android client works, from web not

**Comment by makiftasova** [comment]
#605 and #615 should have fixed this issue (at least for me, for now). if issue still persists, I'll try my best to fix it
