### ISSUE TITLE
read last event.text if it wasn't a /bot command?

### ISSUE THREAD

**Issue by jamenlang** [hangoutsbot/hangoutsbot#639]
I want to write a plugin to take advantage of the "Where are you?" / share your location in hangouts. I can't prepend the automatic link that hangouts creates with /bot <command> is there a way to read the last event.text afterward?
== example ==

me: /bot addlocation
bot: where are you?
me: [share location link]
me: /bot addlocation someplace

bot: sees that there is an argument for a location name, ~reads event.text~ replies, does some more work in the background - replies ok or whatever

**Comment by gurumadmat** [comment]
Try the documentation in the wiki:
https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Authoring-(2.4-and-above)#registering-handlers

**Comment by jamenlang** [comment]
Thank You!
