### ISSUE TITLE
Respond with options

### ISSUE THREAD

**Issue by n6426** [hangoutsbot/hangoutsbot#647]
Hey, 

New to python programming. Is there a plug in or some other kind of example for the bot asking questions to specify results?

For example: 

User: /bot autoreply configure

Bot: Which item would you like to edit? 
1.  List item 1
2. List item 2
3. (etc.) 

User: 2

Bot: what would you like to configure about list item 2?
1. Delete
2. Change question
3. Change answer

This is a basic flow based on user input. Just curious how to do it with this environment. 

Thanks!

**Comment by nylonee** [comment]
Unfortunately there isn't any prompt-based code implemented into the bot, and I can't think of any plugins that have utilized this.

This is certainly a largely requested feature that I don't think is being worked on by anybody yet. You're welcome to suggest code for implementing this feature. If you want to go down this path, submit it as a plugin that others can call when they want to use it.
