### ISSUE TITLE
Verification code in the first login

### ISSUE THREAD

**Issue by lindi200000** [hangoutsbot/hangoutsbot#651]
Hi,
with a current pull and a new bot, hangupsbot ask about Email, Password and a Verification code from the Bot G+ Account.
There are no OAuth Link.
If I enter the data (email, PW), no verification code comes by mail or mobile phone. How do I get this code?
I have loaded the current git and the current requirements.txt.
Does anyone have an idea?
![image](https://cloud.githubusercontent.com/assets/16406425/19835572/5af99c7a-9e8b-11e6-90ef-1d951b0e9cdd.png)

thx Lindi

**Comment by nickfennell** [comment]
Seeing a similar after a recent git pull.

{{{
[root@stick hangupsbot]# /usr/local/bin/python3.4 hangupsbot.py -d
16:13:50 INFO config: /root/.local/share/hangupsbot/config.json read
16:13:50 INFO root: memory = /root/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
16:13:50 INFO config: /root/.local/share/hangupsbot/memory.json read
16:13:50 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Sign in with your Google account:
Email: email_address@tbfh.org
Password:
16:13:56 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 132, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 183, in submit_form
    form.select(selector)[0]['value'] = value
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot.py", line 137, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 64, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 138, in get_auth
    session, credentials_prompt
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 221, in _get_authorization_code
    browser.submit_form(FORM_SELECTOR, {PASSWORD_SELECTOR: password})
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 186, in submit_form
    'Failed to find input {!r} in form'.format(selector)
hangups.auth.GoogleAuthError: Failed to find input '#Passwd' in form
16:13:56 ERROR root: Valid login required, exiting
}}}

**Comment by bafplus** [comment]
if neede, heres a pll from last week: https://www.google.com/url?q=https%3A%2F%2Fwww.wetransfer.com%2Fdownloads%2F14dd8ef116aae9eb92491f1436b5c34120161029120324%2F24d1c028b05ef652d1ea8417f53f460220161029120324%2Fb00f9f&sa=D&sntz=1&usg=AFQjCNHqHAlTOyIcGGvGjzY7degOy-v-zA

**Comment by Kenthalamas** [comment]
Getting the error on that pull too, but after the pip3 install requirements.  Potentially implies the issue lies within the pre-reqs?

**Comment by gurumadmat** [comment]
https://github.com/tdryer/hangups/issues/260#issuecomment-246578670

This comment will explain how to get auth code.

**Comment by mncj** [comment]
thanks @gurumadmat - could you share some detail on where/how to use the outh code once captured?

**Comment by thannemann** [comment]
in the past we never got a user name and password and verification box, this is a new response since the latest build it sounds

20:58:30 INFO config: /home/5555/.local/share/hangupsbot/555555555/config1.json read
20:58:30 INFO root: memory = /home/5555/.local/share/hangupsbot/555555555/memory1.json, failsafe = 3, delay = 1
20:58:30 INFO root: creating memory file: /home/5555/.local/share/hangupsbot/555555555/memory1.json
To log in, open the following link in a browser and paste the provided authorization code below:

https://accounts.google.com/o/oauth2/auth?...............................

Authorization Token: 20:58:31 INFO config: /home/5555/.local/share/hangupsbot/555555555/memory1.json write 0.00046539306640625

**Comment by Kenthalamas** [comment]
For mine at least, it ended up being Google, not the code; I was connecting via a VPN, and Google saw it as "unusual account activity"; their SOP is to ask for additional verification, then still deny the login anyways, most of the time, when they see something "unusual"

**Comment by edgemaster** [comment]
This bug has been fixed by hangoutsbot/hangups#3 being merged. The workaround in INSTALL.md is not required.

**Comment by nickfennell** [comment]
This hasn't been fixed. I've just checked the code out again, and I see the same prompt for username and password. The same error is displayed when my credentials are inserted.

{{{
[nickfennell@stick ENBM-hangoutsbout]$ python3.4 hangupsbot/hangupsbot.py -d
13:39:55 INFO config: /home/nickfennell/.local/share/hangupsbot/config.json read
13:39:55 INFO root: memory = /home/nickfennell/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
13:39:55 INFO config: /home/nickfennell/.local/share/hangupsbot/memory.json read
13:39:55 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Sign in with your Google account:
Email: email@address.tld
Password:
13:40:02 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 282, in _make_token_request
    r.raise_for_status()
  File "/usr/local/lib/python3.4/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 133, in get_auth
    access_token = _auth_with_refresh_token(session, refresh_token)
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 250, in _auth_with_refresh_token
    res = _make_token_request(session, token_request_data)
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 284, in _make_token_request
    raise GoogleAuthError('Token request failed: {}'.format(e))
hangups.auth.GoogleAuthError: Token request failed: 400 Client Error: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 183, in submit_form
    form.select(selector)[0]['value'] = value
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 137, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 64, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 138, in get_auth
    session, credentials_prompt
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 221, in _get_authorization_code
    browser.submit_form(FORM_SELECTOR, {PASSWORD_SELECTOR: password})
  File "/usr/local/lib/python3.4/site-packages/hangups/auth.py", line 186, in submit_form
    'Failed to find input {!r} in form'.format(selector)
hangups.auth.GoogleAuthError: Failed to find input '#Passwd' in form
13:40:02 ERROR root: Valid login required, exiting
}}}

**Comment by edgemaster** [comment]
You need to ensure the latest version of the hangoutsbot/hangups library is installed (possibly by uninstalling and reinstalling it), as the version number didn't get incremented.

**Comment by nickfennell** [comment]
@edgemaster thanks for the pointer. I've just deleted all reference to hangups within site-packages, I've re-ran pip to reinstall:

{{{
[nickfennell@stick ENBM-hangoutsbout]$ sudo /usr/local/bin/pip3.4 install -r requirements.txt --upgrade
Downloading/unpacking git+https://github.com/hangoutsbot/hangups.git (from -r requirements.txt (line 2))
  Cloning https://github.com/hangoutsbot/hangups.git to /tmp/pip-kfplf9tm-build
  Running setup.py (path:/tmp/pip-kfplf9tm-build/setup.py) egg_info for package from git+https://github.com/hangoutsbot/hangups.git
}}}

{{{
[nickfennell@stick site-packages]$ ls -d hangups*
hangups  hangups-0.2.10-py3.4.egg-info  hangups_urwid-1.2.2_dev-py3.4.egg-info
..
[nickfennell@stick site-packages]$ cat hangups/version.py
__version__ = '0.2.10'
}}}

**Comment by Gnarlywhale** [comment]
@Kenthalamas did you ever find a fix for getting it to run on a vpn?

**Comment by Kenthalamas** [comment]
@Gnarlywhale not so much a fix as a work around. I verified the account over a browser while on VPN. Google "learned" the account could connect to multiple locations after enough verification.

**Comment by TheSleepySlee** [comment]
Doesn't work for me. The link provided to get token never returns anything.

**Comment by mjervis** [comment]
I had this problem with a VM running in Oracle VirtualBox on my Windows 10 Home machine. Google see's it as funny. Logins in an incognito browser on windows 10 got no "verification code" issues. But from the py scripts on the VM it did. I solved by using Lynx:

`sudo apt install lynx`

Then run lynx, hit g and paste the URL for the Oauth thing over here https://github.com/tdryer/hangups/issues/260#issuecomment-246578670

Then you login in Lynx, have it text you a verification code, respond to that, then re-launch hangups bot. And it works.
