### ISSUE TITLE
Error: invalid_scope on google account for provided authorization

### ISSUE THREAD

**Issue by acondoriml** [hangoutsbot/hangoutsbot#660]
Hi, my hangout bot suddenly show this message:

 

> 08:54:00 INFO config: /root/.local/share/hangupsbot/config.json read
> 08:54:00 INFO root: memory = /root/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
> 08:54:00 INFO config: /root/.local/share/hangupsbot/memory.json read
> 08:54:00 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
> To log in, open the following link in a browser and paste the provided authorization code below:
> 
> https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.google.com%2Faccounts%2FOAuthLogin&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client_id=936475272427.apps.googleusercontent.com
> 

When I try to follow the instructions I have this error. 

> 400. That’s an error.
> 
> Error: invalid_scope
> 
> Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogi

n]

Any suggestions?

thanks you!

**Comment by wally2164** [comment]
See https://github.com/tdryer/hangups/issues/260#issuecomment-246578670 for getting auth code

**Comment by nylonee** [comment]
The hangouts version of hangups is also updated to allow you to get the auth code through username and password.

Do a `pip install -r requirements.txt --upgrade` and you should have the correct hangups to re-authenticate

**Comment by acondoriml** [comment]
Hi folks, I could fix with @wally2164 said. Thanks a lot!
