### ISSUE TITLE
starts very slow after last update

### ISSUE THREAD

**Issue by stoerenfried** [hangoutsbot/hangoutsbot#664]
Since I updated the bot today it starts very slow - > 4 Minutes until it finally responses, this seems to be too long even for a good ol' raspberry pi. Anything broken?

19:23:33 INFO config: /bla/hangupsbot/config.json read
19:23:33 INFO root: memory = /bla/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
19:23:33 INFO config: /bla/.local/share/hangupsbot/memory.json read
19:23:33 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
19:23:34 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
19:26:31 INFO tagging: refreshed
19:26:31 INFO monkeypatch.otr_support: removeuser replaced with otr_monkeypatch_removeuser
19:26:31 INFO monkeypatch.otr_support: adduser replaced with otr_monkeypatched_adduser
19:26:31 INFO plugins: otr_support - no commands
19:27:10 INFO permamem: loading 211 conversations from memory
19:27:10 INFO permamem: loading 196 users from hangups
19:27:11 INFO permamem: loading 30 conversations from hangups
19:27:11 INFO permamem: total conversations: 211
19:27:11 INFO permamem: total users: 356 cached: 356 definitive (at start): 315

**Comment by pleasantone** [comment]
not enough info to debug

**Comment by nylonee** [comment]
If this problem is persisting, please provide more information about your setup so that we can help debug. Provide information about your network connection, the amount of RAM and CPU being used on the pi, does it happen consistently or is it a one-off thing? Etc.

Closing this issue for now
