### ISSUE TITLE
/bot pluginload

### ISSUE THREAD

**Issue by gravestristen** [hangoutsbot/hangoutsbot#668]
every time I try and load a plugin other than the default it returns with <pluginname>:failed
/bot pluginload image_memegenerator
image_memegenerator: failed

**Comment by gurumadmat** [comment]
You should read the wiki:
https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Control-Commands#load-a-plugin

**Comment by nylonee** [comment]
If you're looking for a safe way to add and remove plugins from the bot within hangouts, also check out the [Pluginmanager](https://github.com/hangoutsbot/hangoutsbot/wiki/Pluginmanager-Plugin)
