### ISSUE TITLE
simpytranslate broken since google changed system

### ISSUE THREAD

**Issue by bafplus** [hangoutsbot/hangoutsbot#669]
Gives 503 error when used.
Google changed something, see Goslate:
Note Google has updated its translation service recently with a ticket mechanism to prevent simple crawler program like goslate from accessing. Though a more sophisticated crawler may still work technically, however it would have crossed the fine line between using the service and breaking the service. goslate will not be updated to break google’s ticket mechanism. Free lunch is over. Thanks for using.

**Comment by nylonee** [comment]
It's been broken for a while, I guess the only thing we can do now is deprecate the plugin until a new one comes around.

I just realized we don't actually have a system of deprecating plugins though... Hmm

**Comment by nylonee** [comment]
Also would be important to note that there are probably other plugins that have a dependency on the simplytranslate plugin. Like the syncroom_translate plugin
