### ISSUE TITLE
missing twitter plugin documentation

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#670]
Someone merged the twitter plugin without providing documentation.

Author: jimsug

**Comment by nylonee** [comment]
Whoops. That would have been my fault. I'll put it on my todo to add documentation. Sorry!

**Comment by jimsug** [comment]
@nylonee If you like I can write up documentation for it, my bad. Give me a sec.

**Comment by jimsug** [comment]
Documentation now at [https://github.com/hangoutsbot/hangoutsbot/wiki/Twitter-Plugin](https://github.com/hangoutsbot/hangoutsbot/wiki/Twitter-Pluginhttps://github.com/hangoutsbot/hangoutsbot/wiki/Twitter-Plugin)

**Comment by nylonee** [comment]
@jimsug Thanks a bunch =)
