### ISSUE TITLE
Autoreply: Expose regex matches in event object?

### ISSUE THREAD

**Issue by kpollich** [hangoutsbot/hangoutsbot#674]
Was poking around with regex-based autoreplies this morning trying to generate links to subreddits when a match occurs.

e.g.

```
/bot autoreply add [["regex:r/([a-zA-Z0-9-_]+)"],["subreddit link goes here"]]
```

As far as I can tell, the match groups from the regex aren't exposed anywhere so this isn't possible. Here's the relevant code where the regex search is done: 

https://github.com/hangoutsbot/hangoutsbot/blob/ed2a641f238ae9acc9c43931fa27a1f8495f0e26/hangupsbot/plugins/autoreply.py#L115

Would it be a possibility to add the regex matches as a property on the ConversationEvent that gets exposed here? Or even just the first match. I'm envisioning being to do something like `http://reddit.com/r/{event.matches[0]}` or `event.matched` above.

Any thoughts on this?

**Comment by kpollich** [comment]
We've moved on from using hangouts due to the impending API deprecation - so this is no longer relevant for us.

**Comment by JosephBlock** [comment]
@kpollich. Hangouts is not going away. Only the video overlay API. Does not effect this project

**Comment by kpollich** [comment]
@JosephBlock That's fine. We've just moved to Slack because of other factors and do not need this change. If there's someone else that wants to see it implemented, feel free to re-open and take over, but my motivations for implementing the change are no longer valid.

I assumed based on lack of discussion that this wasn't a highly sought after feature, but if it is after all my bad.
