### ISSUE TITLE
unable to connect to Google: Message field 'self_entity': Message expected list but got <class 'int'>

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#677]
Unable to connect to Google, repeatedly loops.
Tried regenerating OAuth token from username/password, didn't help.

Fired up tdryer/hangups master branch, everything works. Fired up our fork of hangups, master branch, fails in the same fashion as hangoutsbot, so it's definitely a hangups bug.

Actual error -- we were expecting a list, got an int, for self_entity.

Problem is widespread now.

```
ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/srv/hangoutsbot/lib/python3.4/site-packages/hangups/pblite.py", line 157, in parse
    p = field.parse(field_input)
  File "/srv/hangoutsbot/lib/python3.4/site-packages/hangups/pblite.py", line 149, in parse
    .format(type(input_)))
ValueError: Message expected list but got <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/srv/hangoutsbot/lib/python3.4/site-packages/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/srv/hangoutsbot/lib/python3.4/site-packages/hangups/client.py", line 249, in _initialize_chat
    ).self_entity
  File "/srv/hangoutsbot/lib/python3.4/site-packages/hangups/pblite.py", line 160, in parse
    format(name, e))
ValueError: Message field 'self_entity': Message expected list but got <class 'int'>
Client unexpectedly disconnected:
Message field 'self_entity': Message expected list but got <class 'int'>
INFO root: Waiting 5 seconds...
INFO root: Trying to connect again (try 1 of 5)...
```

**Comment by pleasantone** [comment]
Seeing same problem on multiple machines.

**Comment by nosybore** [comment]
same

**Comment by pleasantone** [comment]
Fixed in hangoutsbot/hangups module.

To get the fix, 'pip install -U -r requirements.txt'

**Comment by JosephBlock** [comment]
Confirmed fixed

**Comment by pleasantone** [comment]
@JosephBlock just fyi - if you have spare cycles, initial_entities is no longer being decoded properly. I found where the structure moved (ds:22) but it's not anything like what the code expects anymore.  It's not -critical- to the bot functioning so I let it stay broken.

**Comment by lindi200000** [comment]
thx for fix :) 
its works

**Comment by nylonee** [comment]
Might be good to have a redacted version of the data dump so that we can refer to it in future changes to find discrepancies.

Thanks for the quick fix @pleasantone!

**Comment by Zitti** [comment]
thx, very cool

**Comment by jpakusch** [comment]
Hello,
i am trying to get the fix too but only got this error:
It seems like my python version is not up to date?
How to i fix that?
`      File "/tmp/pip-build-JPyQDS/aiohttp/setup.py", line 61, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JPyQDS/aiohttp/
`

**Comment by pleasantone** [comment]
fix merged
