### ISSUE TITLE
Adding commands to sync plugins?

### ISSUE THREAD

**Issue by MTRNord** [hangoutsbot/hangoutsbot#686]
Is there some smart way to add custom commands to the slack or tg plugin? (Maybe without rewriting all of it?) I know I could get into the code of these plugins and readd the code but that is not what I want (to write the plugin for every sync plugin). Or is this planned? Because I feel the Bot is (yes it is a hangoutbot) very limited to Hangouts and is sad that the commands aren't synced to the other chats :/

**Comment by JosephBlock** [comment]
There is currently no way of adding new commands without modifying the
original plugins. Take a look at the telegram plugin for the TLDR command,
and how it was implemented.

**Comment by MTRNord** [comment]
I will take a look at that :)

**Comment by MTRNord** [comment]
Ok I took a look at it but that needs a complete rebuild of my plugin so I think that will take some time (I do send chat message and than wait until an picture is generated and want to send that but tldr in tg is build for single message)
