### ISSUE TITLE
Support for running hangupsbot.py as a daemon

### ISSUE THREAD

**Issue by warcriminal** [hangoutsbot/hangoutsbot#69]
http://www.jejik.com/files/examples/daemon3x.py

This link above allows python scripts to be run as daemons. After a personal catastrophe with a start script and cron, having native support to be run as a daemon would be invaluable.

**Comment by endofline** [comment]
daemons are part of the overall roadmap, although there are still some outstanding issues in the bot itself we would like to resolve first. we welcome pull requests to get this done faster :smile:

**Comment by endofline** [comment]
before we implement this, [this gist](https://gist.github.com/endofline/34fc36cfbd149bcc7d15) can help others get started with the bash pseudo-daemon, hopefully with less threat of issues

**Comment by endofline** [comment]
A section related to this issue was excised from the README file during a recent rewrite (a66232d101db9106585e903133b17ae3fb032a0a)

# Developers: TODO

* run as service
  * alternatively [cron](http://www.raspberrypi-spy.co.uk/2013/07/running-a-python-script-at-boot-using-cron/)
    and a [bash script](https://gist.github.com/endofline/34fc36cfbd149bcc7d15) works great too!

**Comment by endofline** [comment]
**alternate bash and expect script:** another dev used two bash scripts: an `expect` script that deletes `cookies.json` (forcing hangups relogin), and automated login: http://pastebin.com/sb5ttcLw and a bash script that is run periodically by cron (every 5 mins) to check whether the process is already running and to start it again if its not: http://pastebin.com/SatuPRZR - these scripts work in tandem with each other and is more flexible than the rudimentary bash infinite loop posted 12 Feb

**Comment by Riptides** [comment]
I haven't had any disconnects since hangups updated its authentication; granted I'm also often restarting the bot manually when changing things, but if the disconnection issue is really solved then daemon support may be less critical.

**Comment by pleasantone** [comment]
There is example code for using upstart and systemd.

**Comment by 1Charmjoe** [comment]
Guys..please

**Comment by 1Charmjoe** [comment]
Can I have ABI build for me
