### ISSUE TITLE
Unable to parse image link from Spawn process

### ISSUE THREAD

**Issue by gabeduke** [hangoutsbot/hangoutsbot#691]
When the bot passes an image link back to the chat using the Spawn plugin it is unable to parse its own text for the image.

**Comment by pleasantone** [comment]
What do you mean parse?

**Comment by gabeduke** [comment]
If a user posts an image URL then the bot can parse the link from the chat
logs and post the actual image. But it cannot perform this action on itself.

**Comment by pleasantone** [comment]
Right, which has nothing to do with the spawn code.

**Comment by gabeduke** [comment]
I see - this can be closed
