### ISSUE TITLE
Hangouts API to be shut down in April. Does this mean hangoutsbot will be no more?

### ISSUE THREAD

**Issue by csansone** [hangoutsbot/hangoutsbot#694]
[This article](https://techcrunch.com/2017/01/06/hangouts-api-shut-down/) says the official API is going the way of the dodo.

Does this software use the same API?

I mean to look into it when I have access to a computer, but thought somebody here likely knows already.

**Comment by KirbyJoe** [comment]
You're wrong, the Hangouts API is for older version of video calls.

**Comment by JosephBlock** [comment]
The underlying program, hangups, is a reversed engineered hangouts API. It
will not go away.

**Comment by csansone** [comment]
I thought this might be the case, but not so easy to look for on mobile. Thanks!
