### ISSUE TITLE
Google+ Hangouts API is no longer supported

### ISSUE THREAD

**Issue by windx0303** [hangoutsbot/hangoutsbot#696]
I happened to see this today. Will this influence our use of hangoutsbot?

https://developers.google.com/+/hangouts/support-faq
The *Google+ Hangouts API is no longer supported.* New apps cannot be created but existing apps will continue to run until April 25th, 2017. After that date, apps in Hangouts will no longer function.

**Comment by gurumadmat** [comment]
See #695 and #694.
