### ISSUE TITLE
extra plugins gets excluded and needs to be loaded manual

### ISSUE THREAD

**Issue by kameleon20** [hangoutsbot/hangoutsbot#697]
Added the events plugin, and enabled the tldr plugin in the correct config.json, but it gets excluded when I start the bot again.
I have to manually 'load' the plugins to get them working.

**Comment by jimsug** [comment]
You need to add it to the `plugins` key in `config.json`.

By default, only the following plugins are automatically loaded:

```python
"plugins": [
    "default",
    "mentions",
    "subscribe",
    "autoreply",
    "dnd",
    "starter",
    "remind"
]
```

You can add `events` using `/bot config append plugins events`

**Comment by trentfehl** [comment]
I have this same issue. Updated the config.json file with the plugin names and have the .py files in the plugin folder and during bot start up they get excluded (default ones still get included after removing them from config.json too). I've also checked the .json file a bunch of times just to make sure I saved it in the first place and I had.

**Comment by trentfehl** [comment]
config.json

"plugins": [ 
    "chance",
    "forecast",         
    "catfact", 
    "image_memegenerator", 
    "xkcd", 
    "lookup", 
    "simplewikipedia"
  ] 

on boot up

01:31:23 INFO plugins: excluded 44: ['metar', 'catfact', 'namelock', 'spotify', 'restrictedadd', 'monitoradds', 'convtools', 'image_screenshot', 'humor_hangoutcalls', 'chatlogger', 'forecast', 'image_memegenerator', 'cleverbot', 'botaddnotif', 'urbandict', 'pluginmanager', 'slackrtm', 'chance', 'api', 'botalive', 'easteregg', 'wolframalpha', 'tldr', 'image_linker_reddit', 'syncrooms_autotranslate', 'convtools_invitations', 'simplytranslate', 'webbridge_hubot', 'forwarding', 'lottery', 'showme', 'image_links', 'spawn', 'webbridge_telegram', 'telesync', 'foursquare', 'twitter', 'syncrooms_config', 'syncrooms', 'botaliases', 'xkcd', 'slack', 'simplewikipedia', 'lookup']
01:31:23 INFO plugins: included 7: ['default', 'mentions', 'subscribe', 'autoreply', 'dnd', 'starter', 'remind']
01:31:23 INFO plugins: default - *broadcast, *config, echo, *hangouts, *leave, *quit, *reload, *rename, *user, *users, *whereami, whoami

**Comment by trentfehl** [comment]
Ah! instead of going to the default folder (~/.local/share/hangupsbot/) i was editing the config.json in the folder that I had cloned to

edited the other one and it updated

**Comment by kameleon20** [comment]
For you, but it doesn't work for me. Still loading the default config somehow

**Comment by gurumadmat** [comment]
Use /bot files to see what file you need to edit and edit that config.json.

**Comment by kameleon20** [comment]
Yeah same path. I'll try a reinstall, maybe there went something wrong with 2nd try installation

**Comment by kameleon20** [comment]
Yes it's working now xD
