### ISSUE TITLE
 The Google+ API for Hangouts is no longer supported

### ISSUE THREAD

**Issue by fortiZde** [hangoutsbot/hangoutsbot#699]
> Important: The Google+ API for Hangouts is no longer supported. Apps will continue to function until April 25, 2017. 

[Hangouts FAQ](https://developers.google.com/+/hangouts/support-faq)

Will that affect the whole project?
// Sorry for opening an issue -  I have to look for an alternative early! :(

**Comment by JosephBlock** [comment]
@fortizde the bot will still work. See also: https://github.com/hangoutsbot/hangoutsbot/issues/694
