### ISSUE TITLE
Command examples in help don't use the bot's actual alias

### ISSUE THREAD

**Issue by PrinterElf** [hangoutsbot/hangoutsbot#702]
_/bot help tldr_ Returns the tldr help with examples of usage.
These examples are hard-coded and usually refer to /bot.
If your botalias is something different, then this could be confusing for users.

Suggest modifying the help parsing code to insert the first alias which is in use for the bot.

**Comment by PrinterElf** [comment]
PR #704 implements.

**Comment by endofline** [comment]
this is a better suggestion and doesn't disrupt the original flow of bot comments: https://github.com/hangoutsbot/hangoutsbot/pull/704#issuecomment-281510918

**Comment by endofline** [comment]
https://github.com/hangoutsbot/hangoutsbot/commit/5247b04bb47bc2ce634fb518abea1cacbf89b337#diff-ed2437fb5796e2cbd001d765ab23d3e0R81
