### ISSUE TITLE
sun: FR: Way to set the location per HO

### ISSUE THREAD

**Issue by bafplus** [hangoutsbot/hangoutsbot#705]
location is now hardcoded.
Would be nice if we can set it for each HO (that overrules the global)

**Comment by JosephBlock** [comment]
What do you mean by location?

**Comment by bafplus** [comment]
The location/timezone that is used to calculate the sun-times.
Like one HO may be focused on Amsterdam, while another HO would be New York.
Abviously they both need different settings/locale/location.

**Comment by JosephBlock** [comment]
I'm not sure which plugin you are referring to if you can link it, but the main issue it sounds is that the code for it needs to be modified to support per conversation settings. This would most likely would work better using memory instead of the config file.

**Comment by bafplus** [comment]
sorry wrong repo ;-)
Thanks for the reply tho
