### ISSUE TITLE
First setup failed with "GoogleAuthError: Failed to find input"

### ISSUE THREAD

**Issue by golbarg** [hangoutsbot/hangoutsbot#711]
Followed instructions from INSTALL.md

Running the commands goes fine.

I then followed the instructions for the first run, including this procedure which used to work for me: https://github.com/tdryer/hangups/issues/260#issuecomment-246578670

However, when I enter the code in the "Verification code" prompt, I get:
`hangups.auth.GoogleAuthError: Failed to find input '#totpPin' in form`
The issue is similar to #683 

I then activated and deactivated 2FA on the Google account. From this point on, I was no longer prompted for a "Verification code". However, I kept getting a hangups error:
`Authorization code cookie not found`
Sometime being prompted for the Google account password, sometimes not.

I believe all this is caused by Google auth changing.

Workaround:
- follow procedure from first run to get `oauth_code` cookie
- add this to the first line of `_get_authorization_code()` in your hangups/auth.py file:
`return "<insert oauth_code cookie here>"`
- run the `python3 hangupsbot/hangupsbot.py` command as mentioned in the instructions

This will force your cookie to be stored and you will then be able to comment out or remove the line to prevent interaction with other/future code.

All this was done with a fresh clone from yesterday.

**Comment by JosephBlock** [comment]
The workaround required creating the cookie.txt file by hand, did not
require editing the python code

**Comment by clintness** [comment]
Where do I place the cookie.txt?

**Comment by JosephBlock** [comment]
@clintness where the bot config and memory files are

**Comment by clintness** [comment]
so this is in /usr/local/lib/python3.5/dist-packages/hangups
or somewhere in the cloned repo?

**Comment by JosephBlock** [comment]
~/.local/share/hangupsbot

**Comment by clintness** [comment]
Is this the best place to ask these questions? 
i created a cookies.txt and pasted the key from  #260 (ref above)
same errors I got before. should i post them here? where would be the proper place? create a new issue?

**Comment by JosephBlock** [comment]
Make a new issue

**Comment by JosephBlock** [comment]
@clintness. My mistake cookie.txt should be cookies.json, .txt is hangups

**Comment by golbarg** [comment]
I believe the stored cookie is different from the oauth_code one returned using instructions from install instructions.

You can also specify a custom file/location for storing or reading the cookie by using the following option:
--cookies [rel-path-to-file]

**Comment by clintness** [comment]
Well I created a new issue detailing my exact issue, greatly appreciate any help. #717 

looks like there might be a new google auth change as I see another new auth related issue as well.

**Comment by oboote** [comment]
tl;dr solution:
1. Login manually: https://github.com/tdryer/hangups/issues/350#issuecomment-323553771
2. Copy ~/.cache/hangups/refresh_token.txt to ~/.local/share/hangupsbot/cookies.json

Struggled getting bot to login for a while before eventually finding workaround.

Suspected issue:
Unrecognised/untrusted new login is being served an additional challenge which the bot is unable to complete (captcha, etc.)

Attempted workarounds which didn't help:
- SSH tunneling to server and login using a browser from server IP.
- Login from server using lynx
- Opening https://accounts.google.com/displayunlockcaptcha locally and whilst tunneling.

**Comment by Terrance** [comment]
hangups now provides a manual login flow option, which can be used to simplify the workaround steps (reading cookies in the browser) without downloading a standalone script.
