### ISSUE TITLE
Question: Autoreply response on "ELSE"

### ISSUE THREAD

**Issue by mavewei** [hangoutsbot/hangoutsbot#712]
Hi ya,

May I know how to let bot make a response to the message/keyword which is not in reply list? I mean in PM mode.

Example: "I have no idea on what you are talking about."

Thanks and cheers.

**Comment by nylonee** [comment]
I don't think this is feasible. Autoreplies read every word you send, looking for a match with one of the canned replies configured.

If you want this functionality, that means that autoreplies will be responding to every message you send it in PM, even bot commands. I imagine it would get pretty annoying.
