### ISSUE TITLE
First Run login failure

### ISSUE THREAD

**Issue by clintness** [hangoutsbot/hangoutsbot#717]
I am installing hangoutsbot to a VPS running Ubuntu 16.04 via PuTTY.

I am logged in as a sudo user named bot

I have followed INSTALL.md but it is unclear what to do with the 0Auth code

Please help or direct me to a place to get help or learn, 

googlefu has failed me.

Below is the scroll back from trying to do First Run:
bot@BridgeSmurf:~/1/hangoutsbot$ python3 hangupsbot/hangupsbot.py                
23:39:23 INFO config: /home/bot/.local/share/hangupsbot/config.json read
23:39:23 INFO root: memory = /home/bot/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
23:39:23 INFO config: /home/bot/.local/share/hangupsbot/memory.json read
23:39:23 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Sign in with your Google account:
Email: bridgesmurf@gmail.com
Password:
23:39:34 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/home/bot/.local/lib/python3.5/site-packages/hangups/auth.py", line 132, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bot/.local/lib/python3.5/site-packages/hangups/auth.py", line 231, in _get_authorization_code
    return browser.get_cookie('oauth_code')
  File "/home/bot/.local/lib/python3.5/site-packages/hangups/auth.py", line 199, in get_cookie
    return self._session.cookies[name]
  File "/home/bot/.local/lib/python3.5/site-packages/requests/cookies.py", line 282, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/bot/.local/lib/python3.5/site-packages/requests/cookies.py", line 340, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='oauth_code', domain=None, path=None"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 137, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/home/bot/.local/lib/python3.5/site-packages/hangups/auth.py", line 64, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/home/bot/.local/lib/python3.5/site-packages/hangups/auth.py", line 138, in get_auth
    session, credentials_prompt
  File "/home/bot/.local/lib/python3.5/site-packages/hangups/auth.py", line 233, in _get_authorization_code
    raise GoogleAuthError('Authorization code cookie not found')
hangups.auth.GoogleAuthError: Authorization code cookie not found
23:39:34 ERROR root: Valid login required, exiting

**Comment by clintness** [comment]
Updated the initial comment above with information from a fresh complete rebuild of the VPS...

**Comment by clintness** [comment]
so i ran it with
 python3.5 hangupsbot/hangupsbot.py -d --log ~/log.txt
and it performs the first run...

**Comment by h3** [comment]
Any updates?

I can't get pass the initial login, all I tet it this error.

I tried with  source branch v3 and pip3 versions..

**Comment by pleasantone** [comment]
Try staging. Do you have 2fa enabled? If so, you need to disable the authenticate via the Google app setting and use a two factor code.

**Comment by das7pad** [comment]
Another approach to login: https://github.com/tdryer/hangups/issues/350#issuecomment-323553771
to use the login for the hangupsbot:
- manually edit line 15 to a path of your choice
- or copy the content of the `refresh_token`-file from the `~/.cache/hangups/` folder to `~/.local/share/hangupsbot/cookies.json`.

**Comment by oboote** [comment]
tl;dr solution:
1. Login manually: https://github.com/tdryer/hangups/issues/350#issuecomment-323553771
2. Copy ~/.cache/hangups/refresh_token.txt to ~/.local/share/hangupsbot/cookies.json

Struggled getting bot to login for a while before eventually finding workaround.

Suspected issue:
Unrecognised/untrusted new login is being served an additional challenge which the bot is unable to complete (captcha, etc.)

Attempted workarounds which didn't help:
- SSH tunneling to server and login using a browser from server IP.
- Login from server using lynx
- Opening https://accounts.google.com/displayunlockcaptcha locally and whilst tunneling.
