### ISSUE TITLE
GoogleAuthError: Failed to find input

### ISSUE THREAD

**Issue by romode** [hangoutsbot/hangoutsbot#718]
![0authj](https://cloud.githubusercontent.com/assets/25352520/22305254/1d077758-e33b-11e6-9300-81c81481fb1d.PNG)
[0authj](https://cloud.githubusercontent.com/assets/25352520/22305254/1d077758-e33b-11e6-9300-81c81481fb1d.PNG)
i tried to set up the bot and i typed my email addres and my passwort in and 
the auth code and i get an error saying `    'Failed to find input {!r} in form'.format(selector)
hangups.auth.GoogleAuthError: Failed to find input '#totpPin' in form
09:18:19 ERROR root: Valid login required, exiting
` can someone help me please

**Comment by nylonee** [comment]
Please see #711
