### ISSUE TITLE
Message sent to user on @all should say "used @all" instead of "mentioned you"

### ISSUE THREAD

**Issue by jkg** [hangoutsbot/hangoutsbot#719]
Regarding the "mentions" plugin.

Simple enough: as a recipient, the bot incorrectly tells me someone mentioned me, when in fact it's probably spam. If the PM tells me that it's an @all I can treat it appropriately (given I also know the hangout and the sender, from that notification, but generally not the content).

I am happy to work on this and submit for review...

**Comment by nylonee** [comment]
Good point, feel free to play with the code and submit a pull request =)

**Comment by jumoog** [comment]
#734

**Comment by nylonee** [comment]
#727 introduced proper mention of all. Closing this now
