### ISSUE TITLE
bot wont run in the background or on startup

### ISSUE THREAD

**Issue by mjbehrendt** [hangoutsbot/hangoutsbot#721]
I went through the install instructions and troubleshooting, but can't find an answer to this.

When I run the script manually, it never returns me to a command prompt, basically hijacking my ssh/console session. If I close that session, the bot closes. I've tried adding it to the init.d startup and crontab at startup, but the script doesn't run. 

Is this normal behavior? How do I get this to run as a background task so that I can close my SSH window?

**Comment by JosephBlock** [comment]
Use one of the startup scripts that are provided,  screen, cron, or even append & at end of command.

**Comment by JosephBlock** [comment]
If none of the options work, show any errors it has and the os version.

**Comment by clintness** [comment]
How did you get past the initial Auth?

**Comment by mjbehrendt** [comment]
Hi, Running on a CentOS box, fyi...

I was able to follow the initial install/1st run instructions. 
Everything was initially installed to /root/hangoutsbot/hangupsbot and the config.json was in /root/.local/share/config.json. was able to get the bot working fine, just wanted it to run at startup/not close when i close my ssh session.

I was able to find the startup script at https://github.com/hangoutsbot/hangoutsbot/blob/master/examples/hangoutsbot.sh.centos6

So following the directions, I've moved all files to /etc/hangoutsbot. I've copied the script into /etc/init.d and gave it execute permissions. when i run the command to start it (sudo /etc/rc.d/init.d/hangoutsbot start) i don't see any errors, and there is no log file in /var/log (as indicated in the command)

I'm not super great on LINUX in general. I appreciate the help. I'm sure i'm just missing some options some where.

**Comment by mjbehrendt** [comment]
Little more information:

Initially the service was exiting because it couldn't find python. Fixed that, now I'm at:

Starting hangoutsbot (via systemctl):  Job for hangoutsbot.service failed because a configured resource limit was exceeded. See "systemctl status hangoutsbot.service" and "journalctl -xe" for details.
                                                           [FAILED]

**Comment by mjbehrendt** [comment]
OK, found the problem. It seems the init.d script doesn't have the path for python3 (on my system its /usr/local/bin/). Once I added that in things started behaving like they should. Thanks.
