### ISSUE TITLE
telesync - adds a lot of links in TG group's shared links

### ISSUE THREAD

**Issue by TheSleepySlee** [hangoutsbot/hangoutsbot#725]
Everytime a user talks in HO synced with TG group, it add the users G+ user link into the shared links database of the TG groups.
It would be great to be able to configure the sync to disable users G+ link to be added into the name by removing the HREF url code. Thanks.

**Comment by nylonee** [comment]
I am unable to find this functionality on the desktop version of Telegram. Can you clarify which version and client of Telegram you're able to access 'shared links'?

**Comment by TheSleepySlee** [comment]
Using Telegram Desktop on MacOS for example, click on the group title, then
on shared links. See picture below.
But I just checked, and it seems this issue is no longer seen.



​

2017-03-23 15:01 GMT+01:00 Nihal Mirpuri <notifications@github.com>:

**Comment by Terrance** [comment]
This was a somewhat awkward quirk of one of the TG clients, unfurling profile links in the user name portion of the message, but it sounds like the client in question doesn't do it any more, and I haven't seen this feature in any of the official clients.
