### ISSUE TITLE
Externally managing user command permissions

### ISSUE THREAD

**Issue by OllieTerrance** [hangoutsbot/hangoutsbot#729]
I have a webapp that handles users and privileges, and currently this manages its own hangups connection to accept slash commands and move users between hangouts as they register.

I'm hoping to integrate the commands into a hangoutsbot plugin, to play nice with the existing features.  I've already got the commands mounted under a top-level command (e.g. `/bot app command`, where `app()` handles the authentication and only accepts valid subcommands for that user), but ideally I'd like to make them first-class citizens (`/bot command`), available only to the right users.

This means I have three classes of commands: unregistered, registered and admin.  Trouble is, I need to dynamically update the tags as users register in the webapp.  I'm guessing some combination of tags and a sync plugin are the way to go here?  Any tips welcome.  🙂

**Comment by endofline** [comment]
This question is probably beyond the scope of the bot as it amounts to a "shadow framework" that sits on top of the existing handlers. Nevertheless, here are some pointers:

If you don't mind providing separate documentation for event commands, you could actually just write a new chat message handler that handles a separate prefix space like `/custom <command>`:
* `plugins.register_handler(_custom_handler, type="message")`
* following the original handler implementation: https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/handlers.py#L120

Another way is to dynamically register commands via `register_command` in https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/__init__.py#L71 - the complexity of this implementation varies depending on whether the custom command list is always changing, or the bot is aware of the command list during plugin startup, then it can be registered fairly easily like the spawn plugin: https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/spawn.py#L83

**Comment by OllieTerrance** [comment]
Sorry, yes, this is rather out of scope.

Previous to the "mounted" command, I did have a completely separate command parser (with its own `/command` space) -- I'm looking to unify it with hangoutsbot as it felt rather disconnected having two separate commands.  I think `register_command` is the way to go for the bot side of things, hardcoding the list of commands should be fine for now.  I'll see where I can get with that.  👍

**Comment by endofline** [comment]
No worries :) I'm mentioning the "out of scope" bit just to note that support for this functionality may be limited and prone to breaking in the future. Familiarity with [standard plugin design](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Authoring-(2.4-and-above)) will give you the greatest stability. I'll close this issue for now, but feel free to to add to this issue for further Q&A, comments, etc.
