### ISSUE TITLE
Bot will not connect "IndexError: string index out of range"

### ISSUE THREAD

**Issue by Raptor123471** [hangoutsbot/hangoutsbot#742]
[error.txt](https://github.com/hangoutsbot/hangoutsbot/files/781791/error.txt)

Error details in text file

**Comment by JosephBlock** [comment]
What version of the bot are you running?

**Comment by Raptor123471** [comment]
@JosephBlock I'm running 2.7.9  I tried the same version on a raspberry pi and with updated requirements.txt. Also tried the latest staging branch with with no luck.

**Comment by Raptor123471** [comment]
@JosephBlock that command failed. I set up the latest master branch on a friend's laptop and I am still getting the same exact error.

**Comment by Raptor123471** [comment]
@JosephBlock I figured out the issue. The error only happens with my bot account and only that account.
