### ISSUE TITLE
INSTALL.md shouldn't immediately describe compiling python [anyver] from source!

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#754]
Talk about steep learning curves:  https://github.com/hangoutsbot/hangoutsbot/blob/master/INSTALL.md

Modern/common distros will already have a version of python that is supported and in their package repos. We should make this clear for platforms like ubuntu, raspbian, etc. Otherwise it raises potential barriers like [this](https://www.reddit.com/r/learnpython/comments/4vh61t/found_a_github_project_i_wanna_use_now_what/d5yo2xk/?st=izgkkkfn&sh=4671afd5) (reddit link)

**Comment by nylonee** [comment]
On that note, we should be installing Python3.5, not 3.4. That also needs to be updated within the file.

**Comment by pleasantone** [comment]
I ripped that part out in the docker branch as I was adding support.

**Comment by endofline** [comment]
FYI, made changes to [INSTALL.md](https://github.com/hangoutsbot/hangoutsbot/blob/staging/INSTALL.md), there were some weird formatting bugs and overall flow was improved.

**Comment by pleasantone** [comment]
Thanks!
