### ISSUE TITLE
/bot config echoes to group hangout

### ISSUE THREAD

**Issue by PrinterElf** [hangoutsbot/hangoutsbot#759]
As it says in the title.
Should the config really echo to group, or to PM as with help?

**Comment by bafplus** [comment]
PM

**Comment by sleavitt** [comment]
Since it's a command sent in hangout by a user to a bot, is there really any way to prevent this from happening if it's in a group hangout? The bot's reply should be in a DM, yes, but if you're wanting to prevent it from being seen in a group hangout in the first place, you should try to do it in a DM with the bot instead.

**Comment by PrinterElf** [comment]
You should do it in PM, yes. However is it not better to safeguard for accidents?

**Comment by sleavitt** [comment]
Yes, I agree. The bot's reply should take place in a PM rather than in the group hangout for precisely that reason.

**Comment by thannemann** [comment]
The command is an admin only command so if a user knows it is there they can try and use it but wont get too far.  However the response should come back in a 1 to 1 with a response in the original hangout like the bot help command does.

**Comment by bafplus** [comment]
Yrs,  but thats the case.... It doesn't go to 1-1...

Op 24 feb. 2017 9:05 p.m. schreef "thannemann" <notifications@github.com>:

**Comment by JosephBlock** [comment]
While admin commands probably shouldn't be used within a group conversation, this should probably be disabled by default and only do 1-1, but have a way to allow a chat to receive the messages. Example: I have a chat that I use to configure the multiple bots that I run to make it easier for running commands against the multiple bots.

**Comment by thannemann** [comment]
The way I can see this working for both instances is the /bot config should respond in a 1 to 1 but to keep instances like @JosephBlock explained there needs to be a new argument /bot config here which would respond in the chat the command was run even if it is group chat.  this at least makes the attempt to safeguard against accidental use of the basic /bot config command 

what does everyone think?

**Comment by JosephBlock** [comment]
@thannemann probably something as simple as /bot config here. To override

**Comment by MTRNord** [comment]
what about a config switch to let the admin decide about this?

**Comment by thannemann** [comment]
That's what I was trying to say, when I said add a "new argument" currently we have the following arguments that are parsed as part of the config command:
/bot config 
/bot config get
/bot config set
/bot config append 
/bot config remove

I recommend /bot config is changed to respond in a 1 to 1 message and add an option for /bot config here to act like the current /bot config

**Comment by JosephBlock** [comment]
I have submitted a pull request adding this feature: https://github.com/hangoutsbot/hangoutsbot/pull/769
