### ISSUE TITLE
CORS support for API and sinks

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#763]
The sink plugins and API endpoints should handle CORS properly.  The base level code, something to the effect of:

```
def do_OPTIONS(self):
       self.send_response(200, "ok")
       self.send_header('Access-Control-Allow-Origin', '*')
       self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
       self.send_header("Access-Control-Allow-Headers", "X-Requested-With")
       self.send_header("Access-Control-Allow-Headers", "Content-Type")
       self.end_headers()
```

in  `base_bot_request_handler.py`'s handlers is a cheap start at it, but we should probably think more about when '*' is an acceptable origin and when it is not.

**Comment by MTRNord** [comment]
Why not define the acceptable origin via a config variable? So every User can decide for the specific Sink

**Comment by endofline** [comment]
i concur with @pleasantone to modify `base_bot_request_handler.py`, specifically [`AsyncRequestHandler`](https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/sinks/base_bot_request_handler.py#L124) 

and to add to @MTRNord's comment, we may have to roll changes made from #641 into a unified config mechanism that allows you to set CORS on a per-sink/per-plugin/global basis. in retrospect, i should have made [`aiohttp_start`](https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/sinks/__init__.py#L142) a little bit more flexible so we can pass additional configuration parameters - perhaps adding a `context` parameter where we can pass a dict with optional settings (including allowed origins)?

**Comment by pleasantone** [comment]
As I understand it, CORS is really there to protect the server by asking the client to block the call.
Given that we have no sink points currently where setting Allow-Origin to anything but '*' would be appropriate at this time, let me make the following suggestion.

Instead of config file stuff, we allow '*' to be overridden by class inheritance, and if a sink ever needs to change it to something else, or disable support entirely, we just let them do it on an application basis and let them worry about their own configuration.

we just make the base routines for the async and sync handlers do something like this:

```
CORS_ORIGIN = '*'
def do_OPTIONS(self):
       self.send_response(200, "ok")
       self.send_header('Access-Control-Allow-Origin', self.CORS_ORIGIN)
       self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
       self.send_header("Access-Control-Allow-Headers", "X-Requested-With")
       self.send_header("Access-Control-Allow-Headers", "Content-Type")
       self.end_headers()
```
Sane?  Insane?

The biggest reason I bring it up is we are great at providing mechanisms like tags, but less great at then having applications create their specific UIs for what the tags are all about.  I kinda don't want to give people more nerd knobs that are too generic to understand until we know the use case.

**Comment by endofline** [comment]
I was thinking an even more conservative option by only making CORS support available when explicitly requested by config. We can encapsulate it into a single `allow_cors_origin` configuration command in a sink config. This won't alter any behaviour for the ignorant ;P (since the directive won't be defined) and allow maximum flexibility for the developers, who can either put it in their plugin instructions or directly override `do_OPTIONS` if they really need more advanced kung-fu.

**Comment by pleasantone** [comment]
CORS is mostly useless in general for our server.
For me, principal of least astonishment is that requests should work, especially for those who are working with IITC or other browser based plugins.

 I'll defer if you feel strongly, but I feel CORS broke  REST and this restores a sane default.

**Comment by endofline** [comment]
I tend to do everything server-side so I'm actually OK leaving it as `*` and applying it across all sinks by default, since I just realised that's the current default for the API plugin. So unless there is any strong disagreement from others - which you may post it here - I'll probably go ahead with the most straightforward implementation outlined by @pleasantone first
