### ISSUE TITLE
SlackRTM: images stored in code/running directory?

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#773]
@errror can you confirm this?

It looks like if image uploading is enabled, we're downloading the image into the running
directory of the bot.  Seems to me that they should be downloaded into /tmp.

```
    @asyncio.coroutine
    def upload_image(self, hoid, image):
        try:
            token = self.apikey
            logger.info('downloading %s', image)
            filename = os.path.basename(image)
            request = urllib.request.Request(image)
            request.add_header("Authorization", "Bearer %s" % token)
            image_response = urllib.request.urlopen(request)
            content_type = image_response.info().get_content_type()
            filename_extension = mimetypes.guess_extension(content_type)
            if filename[-(len(filename_extension)):] != filename_extension:
```

**Comment by errror** [comment]
@pleasantone  Sorry, I think, you are wrong: I'm using urllib.request.urlopen here. AFAIK, this will not generate a (temp.) file in the working directory but give me the data as python data (stored in image_response). I just use os.path.basename to generate a *name* for the data, that I forward to bot._client.upload_image as "filename", maybe that consuses you. ;-)

**Comment by pleasantone** [comment]
Ok thanks, I'm sorry.
