### ISSUE TITLE
SlackRTM -> HObot -> Telegram fails to relay through

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#781]
...but Telegram -> HObot -> Slack works just fine.

SlackRTM -> HO works.
HO -> SlackRTM works.
TG -> HO works.
HO -> TG works.

Telegram is registering on event=hangups.ChatMessageEvent (_on_hangouts_message).
Slack is registering an input handler on "allmessages".

Slack is using: `coro_send_message(hangoutid, msg, context={'slack': True}` to send messages to hangouts.

Telegram is using `coro_send_message(hangoutid, msg)` to send messages to hangouts.

I suspect that we need to add a context otherwise it won't get relayed through.

**Comment by pleasantone** [comment]
The bug is in slackrtm.

When it sends a message out that is a "relay message" it should be attaching a reprocessor (similar to the legacy slack's _slack_repeater_cleaner()) which sets a "do not rebroadcast this to myself" flag  that does something vaguely like this:
```
def _slack_repeater_cleaner(bot, event, id):
    event_tokens = event.text.split(":", maxsplit=1)
    event_text = event_tokens[1].strip()
    if event_text.lower().startswith(tuple([cmd.lower() for cmd in bot._handlers.bot_command])):
        event_text = bot._handlers.bot_command[0] + " [REDACTED]"
    event.text = event_text
    event.from_bot = False
    event._slack_no_repeat = True
    event._external_source = event_tokens[0].strip() + "@slack"
```

I'll take this on.

**Comment by pleasantone** [comment]
Yeah, I tried a few other ways other than the reprocessor (which really is overkill) and failed.
I think there are possibly two things we want to try to solve, and they may not have the same solution:

1. Has a message already been sent out a particular output channel

2. How do we indicate the source of a message so it never gets relayed back out the same output channel.  _is_<service>_relayed is a hack/kludge, and I suspect what we really want is to pass something in in the context parameter.  My big problem was that context itself is lost in a rebroadcast, hence resorting to the reprocessor which comes along after the event has actually been generated.

**Comment by endofline** [comment]
the context parameter itself is a kludge. the protobuf entity that we use for relaying the reprocessor id only seems to accept scalar values, in this case the reprocessor id string which is remapped to some other function or handler. as far as i can tell that's the only way you can make metadata survive a trip through google servers at the moment.

therefore if you actually need the send_message context retained, we could map an automated reprocessor to re-attach the context values back at the handler level prior to entry into the command, chat handlers

**Comment by thannemann** [comment]
I have seen recent work on #636 (discord sync plugin) so I am going to reference it here so it can be verified it works properly with the reprocessor in v3.

**Comment by endofline** [comment]
further comment: what if you could relay before the broadcast? we do have a [`sending` handler](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Authoring-(2.4-and-above)#supported-eventshandlers) which catches outgoing message first before the bot send it. it would more suitable to perform the relay here, and would simplify the type of context that needs to survive the broadcast: in this scenario, we only need to specify a generic `no-relay` flag. all relay plugins would register a dedicated sending handler (something like [syncrooms](https://github.com/hangoutsbot/hangoutsbot/blob/c1bd9e53043e84e13b9a30ffe0e7603b09cbd2dc/hangupsbot/plugins/syncrooms.py#L25) but without modifying the broadcast list) to filter which conversations need to be relayed

**Comment by endofline** [comment]
types of messages:
* user messages in a hangout
  * sending handler: NA, sent by other clients
  * message handler: no metadata / standard non-bot event
    * relay: always
* user messages in third-party chat
  * sending handler: context = "no-relay" + "bridge" + pluginname
    * relay: not by same pluginame
  * message handler: context = "no-relay"
    * relay: never
* bot messages in a hangout (as result of user command)
  * sending handler: context = pluginname (or none, for old plugins)
    * relay: always
  * message handler: no metadata / standard bot event
    * relay: never

**Comment by pleasantone** [comment]
Consider the case where we want to syncrooms slack channel/team to slack channel/team.. it's not no-relay, it's no relay back to source x

**Comment by endofline** [comment]
that would be a filtering issue resolved at the sending handler, I've updated the "story"

**Comment by endofline** [comment]
modified the story to reflect use of "allmessages" handler rather than "messages", as [demonstrated](https://github.com/hangoutsbot/hangoutsbot/commit/5ce2f7343acc50cedbe6befba4d82e8aed9197d5#diff-7aed67d18f9f133fe570b627724e6ad6R8)

**Comment by endofline** [comment]
consider adding sourcebot as well to the context, as running this on upgraded multi-bot relays may cause message looping/duplication since upgraded bots can see each other's context

**Comment by endofline** [comment]
after some testing with context-aware syncrooms, we may have to work on a unified "sending" handler that  can call a standard shared function available through all chat bridges to format incoming identities and messages. we can consider using `call_shared`; or passing the function directly in a context. [the code seems a lot easier](https://github.com/hangoutsbot/hangoutsbot/commit/1277a8b702277511e9555cd0e20055874f174e93) to build tho, and may have some bugs right now, I'm committing it as a guide, feel free to modify it further to test interaction with other chat bridges.
