### ISSUE TITLE
subscribe command doesnt send alerts to bot

### ISSUE THREAD

**Issue by bing0USMC** [hangoutsbot/hangoutsbot#784]
Subscribed words do not trigger a DM from the bot.

**Comment by endofline** [comment]
tested on latest v3.0 branch, seems to be working - check that you are not opted-out on a per-conversation basis; that you are not trying to trigger your own subscriptions (you can't); and provide a log dump if the condition persist

**Comment by endofline** [comment]
merged to `staging`, `v3` - matches subscribed keyword "ABC" to:
```
this is the ABC?
ABC ini
ABC
this is a great ABC jude
wow #ABC!
hey there, ABC - how are you?
what the hell,ABC-i mean, really???
ABC!
#ABC
i need a ABC here!
heh #ABC hashtag
what a#ABC
```

will not match compound words:
```
ini ABCbah!
```
