### ISSUE TITLE
telesync->name sync: please sync also "nickname" if set

### ISSUE THREAD

**Issue by Astrofreak85** [hangoutsbot/hangoutsbot#789]
Please also sync the G+ nickname if send.
G+ Name is "Max Maximus" but also the nickname is set "Maximus123"
So G+ normaly shows "Max Maximus (Maximus123)"

Now, the sync only syncs "Max Maximus" but not the Nickname.

It would be usefull if it could also sync the Nickname!

**Comment by phantomdarkness** [comment]
I believe this was resolved in https://github.com/hangoutsbot/hangoutsbot/pull/761/commits/60efe0ff243402274087b56b9b9a22179cae36cb

**Comment by Terrance** [comment]
v3 chatbridge will sync names and nicknames if present.
