### ISSUE TITLE
docstring error [botalias] + empty string

### ISSUE THREAD

**Issue by sabinico** [hangoutsbot/hangoutsbot#798]
Testing v3 branch I found some errors related to help text in docstring.

1. The [botalias] var is not replaced by real botalias (/bot)
> /bot help

Return:
> [botalias] help command
> Show more info about a command.
> ...

2. When use command specific help, some commands response with error:
> /bot help pluginload
>
> help AttributeError: 'NoneType' object has no attribute 'strip'

Console:
> ERROR commands: RUN: help
>Traceback (most recent call last):
>  File "/home/resmipbot/ho_bot/hangoutsbot/hangupsbot/commands/__init__.py", line 179, in run
>    results = yield from func(bot, event, *args, **kwds)
>  File "/home/resmipbot/ho_bot/hangoutsbot/hangupsbot/commands/basic.py", line 72, in help
>    _docstring = command_fn.__doc__.strip()
>AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by pleasantone** [comment]
Missing r"

**Comment by endofline** [comment]
changes were introduced in v2, so its logical to assume that this affects all current versions

**Comment by endofline** [comment]
also, please avoid using botalias in docstrings, its less readable than just using `/bot`, which will be replaced automatically by whatever configured bot alias actually is when the help text is displayed: https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/commands/basic.py#L86
