### ISSUE TITLE
[telesync] sync breaks on upgrade to Super Group

### ISSUE THREAD

**Issue by HuXDK** [hangoutsbot/hangoutsbot#802]
If sync is setup, before upgrading a TG channel to Super Group, the sync breaks.

**Comment by endofline** [comment]
when it "breaks", what is the log output?

the logic that reacts to super group updates remains [unchanged](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/telesync/__init__.py#L441) [across](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/telesync/__init__.py#L448) [telesync](https://github.com/hangoutsbot/hangoutsbot/blob/feature/chatbridges/hangupsbot/plugins/telesync/__init__.py#L553) versions - can anybody else chime in whether this was verified working in master, v2 staging or v3?

**Comment by JosephBlock** [comment]
I do not believe the v2 was working as a recent chat that was created was upgraded needed to be re-synced. Telegram does return the correct ID in the error message when trying to send to the old chat. Adding a catch for telepot.exception.MigratedToSupergroupChatError may be able to update the ID.

**Comment by HuXDK** [comment]
Might have been network congestion, as i can see nothing in the log.

**Comment by endofline** [comment]
this issue is caused by the telesync plugin not writing its changes to `memory.json` after a supergroup upgrade and is also present in the v2 branch
