### ISSUE TITLE
[Telesync] No response on /Syncprofile

### ISSUE THREAD

**Issue by HuXDK** [hangoutsbot/hangoutsbot#803]
When people do the /syncprofile in TG, and pastes the command into a HO PM, it would be cool, if the HO bot gave a success/failure message.
I'm getting spammed by people that thinks it doesn't work.

Running V3.0 branch

**Comment by Aspersat** [comment]
I get **no response at all in TG**. So no command to copy-paste to hangouts.
So if i enter /syncprofile in a private 1:1 with the bot in TG i get no answer at all
Also there is nothing in the logifiles.

**Comment by nylonee** [comment]
@Aspersat, does running `/bot telesync` from the Hangouts end work?

**Comment by Aspersat** [comment]
@nylonee yes if i enter /bot syncprofile in hangouts it tells me 
"supply registration id as single parameter" so this works.

**Comment by nylonee** [comment]
@Aspersat Have you [disabled privacy](https://github.com/hangoutsbot/hangoutsbot/wiki/telesync-Plugin#basic) on the telegram side?

**Comment by Aspersat** [comment]
@nylonee yes
"Current status is: DISABLED"

**Comment by thannemann** [comment]
Latest V3.0 works for me I'm not sure if there was any code changed recently or is still a problem for you.

**Comment by phoerious** [comment]
I have the same problem. I have one bot for which it works and another for which it doesn't. I've always wondered what the problem is. I tried messing with the config file of the broken bot, but I couldn't get it to answer when I type /syncprofile in the TG chat.

**Comment by das7pad** [comment]
Could you check if your bot can read all messages with the provided api-key?

I wrote a script to extract only messages from the updates loop. 
https://gist.github.com/das7pad/762917bc461a7ae6fe95b95bc66098de
```
$ /path/to/venv/bin/python3 telepot_test.py
```

**Comment by Terrance** [comment]
Regarding the OP, in v3 you should always get a reply from the TG `/syncprofile` and HO `/bot syncprofile` commands.
