### ISSUE TITLE
[v3] Messages duplicating from slackrtm to syncrooms

### ISSUE THREAD

**Issue by azack** [hangoutsbot/hangoutsbot#809]
In this configuration:
[Slack channel] <--slackrtm -->[hangout]<--syncrooms-->[hangout2]

Messages sent from [Slack channel] appear duplicated in hangout2.

**Comment by endofline** [comment]
Is this on features/chatbridges branch or just the plain v3.0 branch?

**Comment by azack** [comment]
@endofline  plain v3.0

**Comment by endofline** [comment]
Noted. This is a known issue on v2, staging and plain v3. We have a fix
pending in the feature/chatbridges branch, which should be merged to 3.0 by
this weekend :) on the other hand, if you need it in a hurry, you can
switch to the branch first. You can use existing config.json and
memory.json. Please see https://github.com/hangoutsbot/hangoutsbot/pull/799
for more info.

**Comment by azack** [comment]
Thanks! Looking forward to that.

**Comment by azack** [comment]
Looks good in v3.0 now

**Comment by dirtheart** [comment]
Having a similar issue after upgrading to the latest version of everything yesterday (5/11/17).  We use a simple syncto from hangouts to slack.  We now find that a message sent in slack gets relayed to hangouts as expected, however hangouts then relays it back to slack creating a duplicate message in the slack channel.  When a message is sent FROM hangouts to slack, this does not happen.  Any ideas on what we can look for to correct the issue?

**Comment by Terrance** [comment]
This should be resolved by the chatbridge layer in v3.
