### ISSUE TITLE
[v3] Join message not relaying Slack->HO->2nd Slack

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#813]
Have 1 bot syncing 2 different slacks to 1 hangout.  Bot syncs messages between the slacks fine.  However, when a user joins Slack 1, that message is relayed to the HO, but then not to Slack 2.

**Comment by endofline** [comment]
this is an unanticipated use-case for the current slackrtm rewrite and it should be broken down to the messaging level ;P are these two channels on separate teams, or are they two channels on the same team?

**Comment by phantomdarkness** [comment]
Oh...for a while it was syncing 2 different slacks/teams to 1 HO just fine.  Seems to have stopped working this AM (or at least i noticed that this AM).

So 2 channels, different teams to answer your question.

**Comment by phantomdarkness** [comment]
Update: updating to latest commits seems to have fixed issue.  Will test.
