### ISSUE TITLE
[v3] Extra "shared media from slack" messages with slackrtm to hangouts

### ISSUE THREAD

**Issue by azack** [hangoutsbot/hangoutsbot#815]
When sharing an image on a slack channel, on the hangout side there is an extra message:
"<user>: shared media from slack".   It seems like this is redundant

(using v3 as of 2017-04-03)

**Comment by endofline** [comment]
this was raised earlier during a review of the slackrtm plugin - the gist of it is for reasons of consistency across telesync and slackrtm. fuller explanation in this [comment on the pr](https://github.com/hangoutsbot/hangoutsbot/pull/761#issuecomment-291378985)

**Comment by Terrance** [comment]
This is gone in the SlackRTM rewrite.
