### ISSUE TITLE
[upgrade] segments_to_html parser

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#82]
presently there is only `simple_parse_to_segments()` (html to ChatMessageSegments) - project needs a reverse parser for testing and general usage by plugins when necessary re: #59

**Comment by xmikos** [comment]
I have this in my [QHangups](https://github.com/xmikos/qhangups) client:
https://github.com/xmikos/qhangups/blob/master/qhangups/utils.py

See `segment_to_html` and `message_to_html`.

**Comment by endofline** [comment]
Put to good use in #300 for the API plugin extension :)
