### ISSUE TITLE
Multi-person mention doesn't catch individual failures

### ISSUE THREAD

**Issue by Terrance** [hangoutsbot/hangoutsbot#820]
After using `@all` in a group, towards the end of notifications being sent out:

```
ERROR root: CORO_SEND_MESSAGE: error sending <1-to-1 ho>
Traceback (most recent call last):
  File "hangoutsbot/hangupsbot/hangupsbot.py", line 761, in coro_send_message
    context = context )
  File "hangoutsbot/hangupsbot/hangups_conversation.py", line 252, in send_message
    expected_otr = otr_status )))
  File "hangoutsbot/venv/lib/python3.6/site-packages/hangups/client.py", line 552, in send_chat_message
    send_chat_message_request, response)
  File "hangoutsbot/venv/lib/python3.6/site-packages/hangups/client.py", line 379, in _pb_request
    .format(status, description)
hangups.exceptions.NetworkError: Request failed with status 4: 'BlockedUserException SENDER_IS_BLOCKED'
```

Looks like someone in the hangout has blocked the bot user.  I can't see any exception handling to catch these whilst looping through the users to mention, which means some notifications wouldn't be delivered.

For the general case, perhaps it would be prudent to set a flag somewhere on a user, if we fail to send a message to them due to being blocked?

**Comment by endofline** [comment]
this is accounted for here: https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/hangupsbot.py#L754 - the exception is indeed caught and logged, and processing continues regardless

**Comment by OllieTerrance** [comment]
Ah, so it is.  🙂  Curious that I didn't get any more mentions sent after that one, maybe it was just the very last person on the list.
