### ISSUE TITLE
[v3] CPU leak (100% usage) when telesync is running

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#825]
I've noticed massive CPU leaks on my production bots, taking up all four cores on my server over the course of a few hours.

Nothing in logs point to anything, but disabling telesync will bring the bot back down to manageable levels.

hangoutsbot v3.0
telepot==10.5
aiohttp==1.3.0

Note: Possibly related to [this telepot issue](https://github.com/nickoala/telepot/issues/53)

**Comment by pschwaller** [comment]
Might be related... I have a testcase using just the jsonrpc hook.  Send a message every second to an otherwise idle bot.  Memory and CPU both incrementally increase.

**Comment by nylonee** [comment]
To those with the same issue, please provide your hangoutsbot version, your telepot version, and your aiohttp version when reporting the issue.

**Comment by endofline** [comment]
Further details, this might be related to the way telepot uses connection pooling [here](https://github.com/nickoala/telepot/blob/master/telepot/aio/api.py#L8). Since this part lacks documentation, I'll add a summary of my findings:
* Running aiohttp 1.3.5 - had to patch [setup.py](https://github.com/nickoala/telepot/blob/master/setup.py#L39) to allow local builds that don't conflict with hangoutsbot v3 and hangups master
* `_which_pool` always for aio always goes to the above `aiohttp.TCPConnector`
* I've tried adding `force_close=True` to this, seems to be a slight reduction in cpu usage over time (but still leaks)
* I've used `response.close()` after this [point](https://github.com/nickoala/telepot/blob/master/telepot/aio/api.py#L87) to see whether I can get aiohttp to release resources. Note: This should not be necessary, as the context manager should actually release resources after use [here](https://github.com/nickoala/telepot/blob/master/telepot/aio/api.py#L109).

**Comment by endofline** [comment]
To further test a hypothesis, anybody with a runaway telesync, run 'netstat -at | grep 149' and report back the output. I'm wondering whether aiohttp is leaving multiple half-open connections strewn around the memory with each one stuck in an asyncio loop waiting for a return. The `149` bit is part of the IP address of telegram api server as given by `nslookup api.telegram.org 8.8.8.8`

**Comment by das7pad** [comment]
closing all aiohttp connections including the ones from hangups, I end up at ~4, ~5 and ~8% CPU leak on a 4c maschine after 27h. It is lower than before but still far to high.

**Comment by pschwaller** [comment]
aiohttp==1.3.5
telepot==10.5
hangoutsbot v3.0

**Comment by endofline** [comment]
test environment:
* Digital Ocean standard 512MB droplet, running ubuntu 16.04 python 3.5.2
* aiohttp == 1.3.5
* telepot == 10.5 (local build)
* latest v3.0 

findings so far:
* further testing with the aforementioned `force_close=True` and `response.close()` shows a **slight but noticeable reduction** in cpu usage over time
* manual garbage collection with `gc.collect()` **does not work** - telesync, telepot and hangoutsbot in general are pretty good with standard gc and everything seems to be collected properly
* now testing a longer timeout in the telesync plugin - the change is on this [line](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/telesync/__init__.py#L1168):
  ```
  plugins.start_asyncio_task(tg_bot.message_loop(timeout=50))
  ```
  caveats:
  * this only reduces the idle cpu leak - constantly busy telegram relays will (probably) not derive much benefit from this modification - telesync/telepot default is at 20 seconds and the telegram api doesn't honor anything above 50 seconds
  * at 50 seconds, the cpu "leak" is reduced to roughly X%/hour, so technically this **does work**, and seems to indicate the telepot `message_loop` as the source of the leak
  * this change will not be as effective if you are not running your bot on a fast and stable line - transient connectivity issues may kill the connection before it properly times out
* the following graph shows the difference from baseline (unchanged telepot); `response.close`; `force_close` and both changes active in telepot (in all 4 tests, `timeout=50`) - [raw data](https://docs.google.com/spreadsheets/d/1LkRTIgMGW4luqKqyPiHUpbXYtKolLquTmY6hr7rSMFY/edit?usp=sharing):
![hangoutsbot performance with telesync and timeout=50](https://cloud.githubusercontent.com/assets/1592553/25512358/abd1e6a0-2bff-11e7-8132-931accc69502.png)

sidenote: hangoutsbot v3 core is aiohttp 2.x-ready, and now we wait upon https://github.com/nickoala/telepot/issues/224

**Comment by nylonee** [comment]
Looks like nickoala/telepot#234 introduces telepot v11.0, which is aiohttp 2.x ready

**Comment by nylonee** [comment]
The latest hangoutsbot v3.0 with aiohttp=2.0.7 and telepot=11.0 fixes the issue for me

**Comment by endofline** [comment]
![telesync leak aiohttp2](https://cloud.githubusercontent.com/assets/1592553/25835424/4556e942-34b1-11e7-9232-ffa2c032fb19.png)

The aiohttp2 upgrade appears to fix it according to a 2-hour run - orange line represents vanilla telesync (`timeout=50`) with telepot 11.0

**Comment by endofline** [comment]
note: the message loop timeout has been restored to its default value in the latest commit
