### ISSUE TITLE
V3 Telesync doesent sync other bots

### ISSUE THREAD

**Issue by bafplus** [hangoutsbot/hangoutsbot#834]
The v3 telesync doesent sync messages from other bots in the same HO.
While this is a nice feature IF there are other bots also syncing to avoid syncloops, in most cases only 1 bot runs the sync and tg side is now missing all the other bot messages.

Can there be a on/of toggle in config and/or conv?

something like "sync_other_bot_msg: true/false"

**Comment by nylonee** [comment]
This is a bug, not a feature, which has already been fixed in commit 34bc3c540aae442e7c14514339dabc4d3bb2fc09. Please pull the latest from the v3 branch
