### ISSUE TITLE
v3 SlackRTM - Bot does not pick up on @botname in public channels

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#835]
Trying to run @botname whereami (or other commands) in a public channel is not picked up by the bot, nothing in log.  Seems to work ok in a private channel.

**Comment by endofline** [comment]
this works fine on my v3.0 branch, look for `INFO plugins.slackrtm.core: message` in your logs

**Comment by phantomdarkness** [comment]
Nope, nothing.  I cleaned out my log entirely, regenerated the api token, rebooted, still no response.

**Comment by endofline** [comment]
is the slack channel where you are issuing the command part of a sync? it might be associated with the recent optimisation that stops the bot from listening to all slack channels, regardless of their sync state. if the channel is unsynced then its considered an expected behaviour of v3.0

**Comment by phantomdarkness** [comment]
No it's not part of the sync (yet).  I'm trying to set up the sync :-) (bot doesn't even respond to @botname syncto HOID).  Can be done from HO but have to get the full channel list (which for this particular slack is rather long).

**Comment by phantomdarkness** [comment]
Setting up the sync gets the bot to respond.

**Comment by pleasantone** [comment]
@endofline how do we establish the sync from Slack then? This forces us to do it from the ho side?

**Comment by pleasantone** [comment]
Fixed
