### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#838]
Is this a problem?

```
Apr 13 18:18:53 charlie ashbot[3183]: INFO root: Connection lost!
Apr 13 18:21:03 charlie ashbot[3183]: ERROR asyncio: Unclosed response
Apr 13 18:21:03 charlie ashbot[3183]: client_response: <ClientResponse(https://0.client-channel.google.com/client-channel/channel/bind?SID=64A7CDE46010943A&CI=0&VER=8&t=1&TYPE=xmlhttp&ctype=hangouts&RID=rpc&gsessionid=Fb9z3znnKpFTzFypBgJDBPittGKDosUc) [200 OK]>
Apr 13 18:21:03 charlie ashbot[3183]: <CIMultiDictProxy('Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'Date': 'Fri, 14 Apr 2017 01:16:52 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Transfer-Encoding': 'chunked', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Server': 'GSE', 'Alt-Svc': 'quic=":443"; ma=2592000; v="37,36,35"')>
```

**Comment by endofline** [comment]
possibly, its arising from hangups and happens quite often, recommend checking [this issue](https://github.com/tdryer/hangups/issues/301) on hangups

**Comment by endofline** [comment]
as per the previously-linked issue, upgrading to aiohttp2 might eliminate these warnings, will report back if it does (running v3 on aiohttp-2.0.7)

**Comment by onaclov2000** [comment]
I tried updating and am still erroring out (sorry I came across this trying to get my bot working) it was working previously for I think weeks at a time, but now it dies usually within a day or so. Next time I get an error log I'll upload it. Usally if I'm having problems there is a fix already out and it's a common issue, sad that it's not working (consistently) right now for me.

**Comment by endofline** [comment]
@onaclov2000 - are you building hangups from source? might be related: i build hangups from source and forgot to `setup.py install` hangups after the aiohttp2 module upgrade, it caused weird dependencies problems: in my case the bot starts up but crashes on reconnect. 

if you have enough system resources, i would recommend running the terminal hangups client concurrently with your bot, and see whether both crash simultaneously as well - the log output of both will be helpful

**Comment by windx0303** [comment]
@endofline so is it fixed now? I posted Issue #861 and my bot still has that problem... My error log is attached:

21:49:55 INFO root: Connection lost!
21:49:55 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
File "hangoutsbot-master/hangupsbot/hangupsbot.py", line 164, in run
loop.run_until_complete(self._client.connect())
File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
return future.result()
File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
raise self._exception
File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
result = coro.throw(exc)
File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/hangups/client.py", line 122, in connect
yield from self._listen_future
File "/usr/lib/python3.4/asyncio/futures.py", line 386, in iter
yield self # This tells Task to wait for completion.
File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
value = future.result()
File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
raise self._exception
File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
result = next(coro)
File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/hangups/channel.py", line 204, in listen
yield from self._longpoll_request()
File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/hangups/channel.py", line 321, in _longpoll_request
), CONNECT_TIMEOUT)
File "/usr/lib/python3.4/asyncio/tasks.py", line 377, in wait_for
return fut.result()
File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
raise self._exception
File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
result = next(coro)
File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/aiohttp/client.py", line 605, in iter
return (yield from self._coro)
File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/aiohttp/client.py", line 161, in _request
raise RuntimeError('Session is closed')
RuntimeError: Session is closed
Client unexpectedly disconnected:
Session is closed
21:49:55 INFO plugins: commands.permamem unloaded
21:49:55 INFO plugins: commands.plugincontrol unloaded
21:49:55 INFO plugins: commands.basic unloaded
21:49:55 INFO plugins: commands.convid unloaded
21:49:55 INFO plugins: commands.tagging unloaded
21:49:55 INFO plugins: plugins.chorus unloaded
21:49:55 INFO plugins: commands.loggertochat unloaded
21:49:55 INFO plugins: monkeypatch.otr_support unloaded
21:49:55 INFO root: Waiting 5 seconds...
21:50:00 INFO root: Trying to connect again (try 1 of 5)...
21:50:07 INFO tagging: refreshed
21:50:07 INFO root: reprocessor.attach_reprocessor already registered in shared
21:50:07 INFO plugins: otr_support - no commands
21:50:07 INFO permamem: loading 174 conversations from memory
21:50:07 INFO permamem: loading 31 users from hangups
21:50:07 INFO permamem: loading 30 conversations from hangups
21:50:07 INFO permamem: total conversations: 174
21:50:07 INFO permamem: total users: 176 cached: 176 definitive (at start): 176
21:50:07 INFO plugins: plugincontrol - *addplugin, *getplugins, *plugininfo, *pluginload, *pluginreload, *pluginunload, *removeplugin
21:50:07 INFO plugins: basic - help, *locale, optout, ping, *resourcememory, version
21:50:07 INFO plugins: tagging - *tagdel, *tagindexdump, *tagscommand, *tagsconv, *tagset, *tagspurge, *tagsuser, *tagsuserlist
21:50:07 INFO plugins: permamem - *dumpconv, *dumpunknownusers, *makeallusersindefinite, *refreshusermemory, *removeconvrecord, *resetunknownusers
21:50:07 INFO plugins: convid - *convecho, *convfilter, *convleave, *convrename, *convusers
21:50:07 INFO commands.loggertochat: ChatMessageLogger already attached
21:50:07 INFO plugins: loggertochat - *logconfig, *lograise
21:50:07 INFO plugins: excluded 63: ['cleverbot', 'forwarding', '_unittest', '_unittest.unittest_memory', '_unittest.unittest_statusevents', '_unittest.unittest_geticon', '_unittest.unittest_reprocessor', '_unittest.unittest_shutup', 'monitoradds', 'restrictedadd', 'autoreply', 'default', 'mentions', 'namelock', '_cam_mail_intercept', 'forecast', 'subscribe', 'xkcd', 'spawn', 'syncrooms', 'api', 'tldr', 'remind', 'image', 'image.image_linker_reddit', 'image.image_links', 'image.image_screenshot', 'image.image_memegenerator', 'slack', 'botaddnotif', 'convtools', '_DEPRECATED_simplytranslate', 'metar', 'botaliases', '_example', '_example.example_watchmembers', '_example.example_webbridge', '_example.example_printrenames', '_example.example_memory', '_DEPRECATED_syncrooms_autotranslate', 'urbandict', 'humor_hangoutcalls', 'wolframalpha', 'starter', 'webbridge_telegram', 'simplewikipedia', 'slackrtm', 'twitter', 'spotify', 'botalive', 'showme', 'convtools_invitations', 'dnd', 'chatlogger', 'lookup', 'catfact', 'foursquare', 'chance', 'easteregg', 'syncrooms_config', 'telesync', 'lottery', 'webbridge_hubot']
21:50:07 INFO plugins: included 1: ['chorus']
21:50:07 INFO plugins: chorus - choruslink
21:50:07 INFO root: bot initialised

**Comment by das7pad** [comment]
https://github.com/tdryer/hangups/pull/326 fixed this.

**Comment by Terrance** [comment]
Fixed in upstream hangups, which v3 now uses.
