### ISSUE TITLE
2.8.0 version tagged as "v2.8.0" instead of "2.8.0"

### ISSUE THREAD

**Issue by PHLAK** [hangoutsbot/hangoutsbot#844]
A minor gripe but up until now all tags have followed a consistent pattern. This breaks any automation built relying on consistent tags.  See: https://github.com/hangoutsbot/hangoutsbot/tags

If this was a mistake you can simply add another "2.8.0" tag pointing to the same commit. 
If this is going to be the default from here on out that's fine too, I'd just like to know if that's the case.

**Comment by endofline** [comment]
corrected this oversight and pushed tag [2.8.0](https://github.com/hangoutsbot/hangoutsbot/tree/2.8.0) :) thanks for the ping

**Comment by PHLAK** [comment]
Thanks!

**Comment by nylonee** [comment]
Whoops. My bad. Thanks for the quick fix @endofline
