### ISSUE TITLE
Error 128 and server certificate verification faild

### ISSUE THREAD

**Issue by nilsee1** [hangoutsbot/hangoutsbot#851]
## Description 
Whilst trigered the 'pip3 install -r requirements.txt' comand got a Certificate fail and an Error 128
## Output of `/bot version`
See attached screenshot
## Expected behaviour 
install 
## Actual behaviour 
got a Server Certificate failed and Error 128
![screenshot_20170430-082648](https://cloud.githubusercontent.com/assets/28217011/25562690/f0e9bd54-2d84-11e7-8788-15721a8da3f0.png)

**Comment by OllieTerrance** [comment]
Your RPi isn't trusting GitHub's SSL certificate.

* Have you got certificates installed?  (`apt-get install ca-certificates` for Debian)
* Is your system clock accurate?  (consider installing `ntpd` to keep it accurate if not already)

You may be able to get more info by exporting `GIT_CURL_VERBOSE=1` in your env.

**Comment by jumoog** [comment]
can be closed?
