### ISSUE TITLE
[v3] telesync full migration to telepot 11.0

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#855]
`message_loop()` has been deprecated in https://github.com/nickoala/telepot/issues/234#issue-227218232 - telesync should be updated to the new loop "style". backward-compatibility with telepot<11.0 is **not required**

**Comment by phantomdarkness** [comment]
Images are not syncing from TG->HO.  Images do sync from HO->TG.  Nothing in the log indicating an issue.

**Comment by endofline** [comment]
@phantomdarkness - your issue appears to be unrelated and may have been addressed in the most recent commit 118e80322ed9fa4e68c5f3ce21ffa402f37121b7 - friendly note: in the future, please create a new issue instead of adding unto existing issues, especially if there is no further information linking the two :)

**Comment by phantomdarkness** [comment]
Sorry I thought this was for any issue related to the telepot 11 update. My mistake. And thanks for the patch.

**Comment by endofline** [comment]
@phantomdarkness - hold on, this appears to be 2 issues in one, i'm exploring another issue that might be telepot 11.0 and image-related (but not specific to the new implementation of the loop), would appreciate if you could open a new issue on this, while i dig into the code.

**Comment by endofline** [comment]
@phantomdarkness - never mind on the new issue, the secondary issue is resolved and isn't related with telepot 11.0, but with telesync logic: apparently images that are sent as a document were not being handled properly for quite some time (most likely since v2). 45d386265e1c42a9efec6d1d4890a32767da0b7c addresses this
