### ISSUE TITLE
RuntimeError: Session is closed

### ISSUE THREAD

**Issue by windx0303** [hangoutsbot/hangoutsbot#861]
## Description

Mostly the bot is working fine. Just that I noticed it disconnects (and then re-connects) more often these couple days. Anyone has similar problem?

## Log output

  File "/usr/lib/python3.4/asyncio/tasks.py", line 377, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 605, in __iter__
    return (yield from self._coro)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 161, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
Client unexpectedly disconnected:
Session is closed
14:39:56 INFO plugins: plugins.chorus unloaded
14:39:56 INFO plugins: commands.convid unloaded
14:39:56 INFO plugins: commands.plugincontrol unloaded
14:39:56 INFO plugins: commands.loggertochat unloaded
14:39:56 INFO plugins: commands.permamem unloaded
14:39:56 INFO plugins: commands.basic unloaded
14:39:56 INFO plugins: commands.tagging unloaded
14:39:56 INFO plugins: monkeypatch.otr_support unloaded
14:39:56 INFO root: Waiting 20 seconds...
14:40:16 INFO root: Trying to connect again (try 4 of 5)...
14:40:23 INFO tagging: refreshed
14:40:23 INFO root: reprocessor.attach_reprocessor already registered in shared

**Comment by windx0303** [comment]
More details: Whenever I start a conversation, this log shows up:

22:17:47 ERROR asyncio: Unclosed connection
client_connection: Connection<('0.client-channel.google.com', 443, True)>
22:17:47 ERROR asyncio: Unclosed response
client_response: <ClientResponse(https://0.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&CI=0&VER=8&SID=***&TYPE=xmlhttp&t=1&gsessionid=***&RID=rpc) [200 OK]>
<CIMultiDictProxy('Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'Date': 'Fri, 09 Jun 2017 02:00:03 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Transfer-Encoding': 'chunked', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Server': 'GSE', 'Alt-Svc': 'quic=":443"; ma=2592000; v="38,37,36,35"')>

Any ideas?

**Comment by das7pad** [comment]
The timing for keep-alives on long-polling requests has changed, this results in disconnects.
For more details see https://github.com/tdryer/hangups/issues/331

And for the resource warning in your comment see #838 with a pending fix here https://github.com/tdryer/hangups/pull/326

**Comment by windx0303** [comment]
Thanks for reply! So it's not fixed yet?

(Since I'm using an older version (from Feb 2017 I think), does the newer version fix this?)

**Comment by das7pad** [comment]
not in the main repository. You can use my fork of hangups, the master branch has all my pull requests already merged.
Note: as this is an up-to-date hangups version, old plugins might stop working - ones that access deprecated hangups constants for example.

in the ```requirements.txt``` for pip change the line
```git+https://github.com/hangoutsbot/hangups.git```
to
```git+https://github.com/das7pad/hangups.git```
and install it via ```pip3 install -r /path/to/requirements.txt --upgrade```

You can always go back by reverting the change in the ```requirements.txt``` and upgrading via pip.

**Comment by windx0303** [comment]
Ok, got it. Thanks.

**Comment by das7pad** [comment]
@windx0303 the pull request for an increased pushtimeout on long-polling request got merged https://github.com/tdryer/hangups/commit/77719ca1226373270cb270639168b3d9dd270e71.

If you are running the bot on branch v3.0, a simple ```pip3 install -r /path/to/requirements.txt --upgrade``` should do the magic.

**Comment by windx0303** [comment]
@das7pad Thanks for the response! However, I still encountered the following errors pretty much everyday:

  File "hangoutsbot-master/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 122, in connect
    yield from self._listen_future
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 204, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 321, in _longpoll_request
    ), CONNECT_TIMEOUT)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 377, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 605, in __iter__
    return (yield from self._coro)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 161, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
Client unexpectedly disconnected:
Session is closed
22:27:48 INFO plugins: commands.loggertochat unloaded
22:27:48 INFO plugins: monkeypatch.otr_support unloaded
22:27:48 INFO plugins: plugins.chorus unloaded
22:27:48 INFO plugins: commands.basic unloaded
22:27:48 INFO plugins: commands.tagging unloaded
22:27:48 INFO plugins: commands.plugincontrol unloaded
22:27:48 INFO plugins: commands.permamem unloaded
22:27:48 INFO plugins: commands.convid unloaded
22:27:48 INFO root: Waiting 10 seconds...
22:27:58 INFO root: Trying to connect again (try 2 of 5)...

Is it because my Python version?...

Thanks!

**Comment by windx0303** [comment]
@das7pad Also when I ran update, I saw some packages are not (re)installed, is that a problem?

Requirement already up-to-date: telepot==7.1 in /usr/local/lib/python3.4/dist-packages (from -r hangoutsbot-master/requirements.txt (line 20))
Requirement already up-to-date: cleverwrap in /usr/local/lib/python3.4/dist-packages (from -r hangoutsbot-master/requirements.txt (line 21))
Requirement already up-to-date: TwitterAPI in /usr/local/lib/python3.4/dist-packages (from -r hangoutsbot-master/requirements.txt (line 22))
Requirement already up-to-date: google-api-python-client in /usr/local/lib/python3.4/dist-packages (from -r hangoutsbot-master/requirements.txt (line 23))
Requirement already up-to-date: spotipy in /usr/local/lib/python3.4/dist-packages (from -r hangoutsbot-master/requirements.txt (line 24))
Requirement already up-to-date: soundcloud in /usr/local/lib/python3.4/dist-packages (from -r hangoutsbot-master/requirements.txt (line 25))
Requirement already up-to-date: ConfigArgParse==0.9.3 in /usr/local/lib/python3.4/dist-packages (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
Requirement already up-to-date: purplex==0.2.4 in /usr/local/lib/python3.4/dist-packages (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
Requirement already up-to-date: readlike>=0.1 in /usr/local/lib/python3.4/dist-packages (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
Downloading/unpacking requests==2.6.0 (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
  Downloading requests-2.6.0-py2.py3-none-any.whl (469kB): 469kB downloaded
Requirement already up-to-date: ReParser>=1.4 in /usr/local/lib/python3.4/dist-packages (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
Requirement already up-to-date: hangups-urwid==1.2.2-dev in /usr/local/lib/python3.4/dist-packages (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
Requirement already up-to-date: MechanicalSoup==0.4.0 in /usr/local/lib/python3.4/dist-packages (from hangups==0.2.10.2->-r hangoutsbot-master/requirements.txt (line 2))
Downloading/unpacking chardet from https://pypi.python.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl#md5=0004b00caff7bb543a1d0d0bd0185a03 (from aiohttp>=1.0,<1.1->-r hangoutsbot-master/requirements.txt (line 5))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Requirement already up-to-date: multidict>=2.0 in /usr/local/lib/python3.4/dist-packages (from aiohttp>=1.0,<1.1->-r hangoutsbot-master/requirements.txt (line 5))
Requirement already up-to-date: async-timeout in /usr/local/lib/python3.4/dist-packages (from aiohttp>=1.0,<1.1->-r hangoutsbot-master/requirements.txt (line 5))
Downloading/unpacking six>=1.5 from https://pypi.python.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8 (from python-dateutil->-r hangoutsbot-master/requirements.txt (line 10))
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already up-to-date: futures in /usr/local/lib/python3.4/dist-packages (from goslate->-r hangoutsbot-master/requirements.txt (line 12))
Requirement already up-to-date: beautifulsoup4 in /usr/local/lib/python3.4/dist-packages (from wikipedia->-r hangoutsbot-master/requirements.txt (line 14))
Requirement already up-to-date: websocket-client in /usr/local/lib/python3.4/dist-packages (from slackclient>=0.16->-r hangoutsbot-master/requirements.txt (line 18))
Requirement already up-to-date: requests-oauthlib in /usr/local/lib/python3.4/dist-packages (from TwitterAPI->-r hangoutsbot-master/requirements.txt (line 22))
Requirement already up-to-date: fudge>=1.0.3 in /usr/local/lib/python3.4/dist-packages (from soundcloud->-r hangoutsbot-master/requirements.txt (line 25))
Requirement already up-to-date: simplejson>=2.0 in /usr/local/lib/python3.4/dist-packages (from soundcloud->-r hangoutsbot-master/requirements.txt (line 25))
Installing collected packages: appdirs, python-dateutil, requests, hangups, emoji, pyslack-real, chardet, six
  Found existing installation: appdirs 1.3.0
    Not uninstalling appdirs at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: python-dateutil 2.0
    Not uninstalling python-dateutil at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: hangups 0.2.10.2
    Uninstalling hangups:
      Successfully uninstalled hangups
  Running setup.py install for hangups

    Installing hangups script to /usr/local/bin
  Found existing installation: emoji 0.4.5
    Uninstalling emoji:
      Successfully uninstalled emoji
  Running setup.py install for emoji

  Found existing installation: pyslack-real 0.6.0
    Uninstalling pyslack-real:
      Successfully uninstalled pyslack-real
  Running setup.py install for pyslack-real

  Found existing installation: chardet 2.2.1
    Not uninstalling chardet at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python3/dist-packages, owned by OS
Successfully installed appdirs python-dateutil requests hangups emoji pyslack-real chardet six
Cleaning up...

**Comment by das7pad** [comment]
@windx0303 You are not using a virtual environment for the packages of the bot right?
I suggest doing so as other applications might upgrade or downgrade certain packages.
https://docs.python.org/3/tutorial/venv.html#introduction

Which python and aiohttp version are you using?

**Comment by windx0303** [comment]
@das7pad You're totally right. I just moved my code to virtual environment, run the pip install, and it works smoothly (so far). Great thanks!

**Comment by windx0303** [comment]
@das7pad it happened again today though :(

Log is attached. Any ideas?...

21:49:55 INFO root: Connection lost!
21:49:55 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "hangoutsbot-master/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/hangups/client.py", line 122, in connect
    yield from self._listen_future
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/hangups/channel.py", line 204, in listen
    yield from self._longpoll_request()
  File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/hangups/channel.py", line 321, in _longpoll_request
    ), CONNECT_TIMEOUT)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 377, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/aiohttp/client.py", line 605, in __iter__
    return (yield from self._coro)
  File "/root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages/aiohttp/client.py", line 161, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
Client unexpectedly disconnected:
Session is closed
21:49:55 INFO plugins: commands.permamem unloaded
21:49:55 INFO plugins: commands.plugincontrol unloaded
21:49:55 INFO plugins: commands.basic unloaded
21:49:55 INFO plugins: commands.convid unloaded
21:49:55 INFO plugins: commands.tagging unloaded
21:49:55 INFO plugins: plugins.chorus unloaded
21:49:55 INFO plugins: commands.loggertochat unloaded
21:49:55 INFO plugins: monkeypatch.otr_support unloaded
21:49:55 INFO root: Waiting 5 seconds...
21:50:00 INFO root: Trying to connect again (try 1 of 5)...
21:50:07 INFO tagging: refreshed
21:50:07 INFO root: reprocessor.attach_reprocessor already registered in shared
21:50:07 INFO plugins: otr_support - no commands
21:50:07 INFO permamem: loading 174 conversations from memory
21:50:07 INFO permamem: loading 31 users from hangups
21:50:07 INFO permamem: loading 30 conversations from hangups
21:50:07 INFO permamem: total conversations: 174
21:50:07 INFO permamem: total users: 176 cached: 176 definitive (at start): 176
21:50:07 INFO plugins: plugincontrol - *addplugin, *getplugins, *plugininfo, *pluginload, *pluginreload, *pluginunload, *removeplugin
21:50:07 INFO plugins: basic - help, *locale, optout, ping, *resourcememory, version
21:50:07 INFO plugins: tagging - *tagdel, *tagindexdump, *tagscommand, *tagsconv, *tagset, *tagspurge, *tagsuser, *tagsuserlist
21:50:07 INFO plugins: permamem - *dumpconv, *dumpunknownusers, *makeallusersindefinite, *refreshusermemory, *removeconvrecord, *resetunknownusers
21:50:07 INFO plugins: convid - *convecho, *convfilter, *convleave, *convrename, *convusers
21:50:07 INFO commands.loggertochat: ChatMessageLogger already attached
21:50:07 INFO plugins: loggertochat - *logconfig, *lograise
21:50:07 INFO plugins: excluded 63: ['cleverbot', 'forwarding', '_unittest', '_unittest.unittest_memory', '_unittest.unittest_statusevents', '_unittest.unittest_geticon', '_unittest.unittest_reprocessor', '_unittest.unittest_shutup', 'monitoradds', 'restrictedadd', 'autoreply', 'default', 'mentions', 'namelock', '_cam_mail_intercept', 'forecast', 'subscribe', 'xkcd', 'spawn', 'syncrooms', 'api', 'tldr', 'remind', 'image', 'image.image_linker_reddit', 'image.image_links', 'image.image_screenshot', 'image.image_memegenerator', 'slack', 'botaddnotif', 'convtools', '_DEPRECATED_simplytranslate', 'metar', 'botaliases', '_example', '_example.example_watchmembers', '_example.example_webbridge', '_example.example_printrenames', '_example.example_memory', '_DEPRECATED_syncrooms_autotranslate', 'urbandict', 'humor_hangoutcalls', 'wolframalpha', 'starter', 'webbridge_telegram', 'simplewikipedia', 'slackrtm', 'twitter', 'spotify', 'botalive', 'showme', 'convtools_invitations', 'dnd', 'chatlogger', 'lookup', 'catfact', 'foursquare', 'chance', 'easteregg', 'syncrooms_config', 'telesync', 'lottery', 'webbridge_hubot']
21:50:07 INFO plugins: included 1: ['chorus']
21:50:07 INFO plugins: chorus - choruslink
21:50:07 INFO root: bot initialised

**Comment by das7pad** [comment]
``aiohttp`` version 1.0.5 is slightly outdated (Nov 2016) and might contibute to the cause for this issue.
I also see this ``hangups==0.2.10.2`` in the installation log, which pulls an outdated (June 2015) hangups version.

This line from the hangupsbot log ``21:49:55 INFO plugins: monkeypatch.otr_support unloaded`` indicates an old bot version. Which one are you using?

I suggest upgrading your bot to v2.8 or even the step to v3.0 and running pip upgrades then.

**Comment by windx0303** [comment]
I just updated `aiohttp` and `hangups` to the latest version, and the following 3 warning (?) log (text in bold font) occurred when I use `pip3 install -requirement.txtx --upgrade` to update the bot:

Installing hangups script to /root/chorus-bot-repo/bot-venv/bin
  **Could not find .egg-info directory in install record for hangups==0.2.10.2 from git+https://github.com/hangoutsbot/hangups.git (from -r hangoutsbot-master/requirements.txt (line 2))
  Found existing installation: emoji 0.4.5**
    Can't uninstall 'emoji'. No files were found to uninstall.
  Running setup.py install for emoji
  **Could not find .egg-info directory in install record for emoji==0.4.5 from git+https://github.com/carpedm20/emoji in /root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages (from -r hangoutsbot-master/requirements.txt (line 16))**
  Found existing installation: pyslack-real 0.6.0
    Can't uninstall 'pyslack-real'. No files were found to uninstall.
  Running setup.py install for pyslack-real
  **Could not find .egg-info directory in install record for pyslack-real==0.6.0 from git+https://github.com/loisaidasam/pyslack.git in /root/chorus-bot-repo/bot-venv/lib/python3.4/site-packages (from -r hangoutsbot-master/requirements.txt (line 17))**

And the bot is still crashing daily (about 1 or 2 times per day). Any ideas? (I downloaded the code as a .zip file from this Github repo in June 2017. I think this is the latest bot?...)

**Comment by das7pad** [comment]
I suggest starting with a new virtual environment as the current one can not cleanup itself.

You are still pulling an outdated ``hangups`` version. I see that it is a requirement for ``v2.8``, but the [diff](https://github.com/hangoutsbot/hangups/compare/master...tdryer:master) between https://github.com/hangoutsbot/hangups/ and https://github.com/tdryer/hangups/ is huge.

Hangupsbot version 3 is stable in general, however it has some memory leak issues. A checkout to ``v3.0`` and upgraded pip requirements should fix the random crashes caused by ``hangups``, but might create other issues with legacy plugins.

_Are you sure about running your bot as root?_

**Comment by windx0303** [comment]
@das7pad it seems everything is working fine after I switched to v3. Is there any official timeline to release it?

**Comment by das7pad** [comment]
@windx0303 Great! There is no schedule for a merge in this repository.
