### ISSUE TITLE
docker-entrypoint.sh needs +x permission

### ISSUE THREAD

**Issue by fizux** [hangoutsbot/hangoutsbot#869]
docker container fails to run docker-entrypoint.sh on start due to lack of +x permission.

suggest adding:
RUN ["chmod", "+x", "docker-entrypoint.sh"]

to Dockerfile between:
ADD docker-entrypoint.sh .
and:
ENTRYPOINT ["./docker-entrypoint.sh"]

**Comment by das7pad** [comment]
@fizux Can you raise a pull request for your suggested changes please?

**Comment by eigood** [comment]
The correct fix is to do "chmod +x docker-entrypoint.sh" in the git repo, and commit that.  No changes to the Dockerfile at all.
