### ISSUE TITLE
[v3] ERROR hangups.channel: Ran out of retries for long-polling request

### ISSUE THREAD

**Issue by windx0303** [hangoutsbot/hangoutsbot#871]
## Description

Bot stop running when the error "Ran out of retries for long-polling request" occurred. 

## Output of `/bot version`

Bot Version: 3.0.0-beta
Python Version: 3.4.3
* aiohttp 2.2.3
* appdirs 1.4.3
* emoji 0.4.5
* hangups 0.4.2
* telepot 12.1

## Expected behaviour

I thought the bot will re-boot (for at most 5 times?).

## Actual behaviour

The bot just exits and stop running...

## Log output

```
00:24:24 INFO root: Connection lost!
04:47:46 INFO root: Connection lost!
15:55:18 INFO root: Connection lost!
15:57:16 INFO root: Connection lost!
21:48:43 INFO root: Connection lost!
22:55:17 INFO root: Connection lost!
22:58:19 ERROR hangups.channel: Ran out of retries for long-polling request
22:58:19 INFO root: bot is exiting
22:58:19 INFO plugins: plugins.chorus unloaded
22:58:19 INFO plugins: commands.convid unloaded
22:58:19 INFO plugins: commands.loggertochat unloaded
22:58:19 INFO plugins: commands.basic unloaded
22:58:19 INFO plugins: commands.tagging unloaded
22:58:19 INFO plugins: commands.plugincontrol unloaded
22:58:19 INFO plugins: commands.permamem unloaded
```

**Comment by das7pad** [comment]
Thats not the case on a clean exit of the long-polling request. I can work on a fix.

**Comment by das7pad** [comment]
@windx0303 you can checkout the fix with
> $ git fetch origin pull/872/head:pr-873
> $ git checkout pr-872

_**"pr-872"** can be changed to a custom name as needed_
