### ISSUE TITLE
Better guide to setup forecast plugin

### ISSUE THREAD

**Issue by survivor303** [hangoutsbot/hangoutsbot#874]
What we really need is better guide to the wiki, on how to setup forecast plugin for Hangoutsbot.

https://github.com/hangoutsbot/hangoutsbot/wiki/Forecast-Plugin
Isnt tell almost nothing how to setup it to config.json file, there need to be where exactly and what users needed to put there and which line order and so on...

**Comment by OllieTerrance** [comment]
It's just the one config key:

> Store your Forecast.io API key in config.json:
> ```
> "forecast_api_key": "FORECAST_API_KEY"
> ```

The config file isn't ordered, it can go anywhere as long as it's top-level.  You can also just use the config command: `/bot config set forecast_api_key "FORECAST_API_KEY"`

In terms of actually finding your config file, perhaps [this](https://github.com/hangoutsbot/hangoutsbot/blob/master/INSTALL.md#additional-configuration) is what you need?

**Comment by survivor303** [comment]
Top level?
I get errors when i put the line to the config.json file.
There are these [ and } symbols, i dont know how to put config file together that the program itself can read it correctly.

**Comment by survivor303** [comment]
well, when i add the api key from the bot (using command /bot config), it saves it to config.json file correctly, but if you want send commands to it, you need allow access to it and add "commands_enabled": true, directly under the line.

**Comment by OllieTerrance** [comment]
> There are these [ and } symbols, i dont know how to put config file together that the program itself can read it correctly.

There is an assumption that if you're editing the config file directory, you already have an understanding of [JSON files](http://json.org) in general (it's a fairly standard file format).  In short, at least in our case:
* file starts with `{` and ends with `}` -- this is the outermost layer
* each entry is a key/value pair of the form `"key": value`, comma-delimited
* values may be text, numbers etc., or lists of values, or nested key/value sets

> if you want send commands to it, you need allow access to it and add "commands_enabled": true, directly under the apikey line.

[Here's the default config file](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/config.json) -- note that `commands_enabled` is already there.  You shouldn't get into a state where it's off unless you've already edited your config file...
