### ISSUE TITLE
Cannot make bot run on its self.

### ISSUE THREAD

**Issue by EvanjKrul** [hangoutsbot/hangoutsbot#877]
Hello,
Excuse my noobness.
I am trying to get the bot to start automatically on boot with my raspberry pi so I ran chown -X on the hangoutsbot.sh file from examples but it returns nothing and does nothing... What am i missing?
## Output of `/bot version`
Bot Version: 2.8.0
Thanks in advance.
-Evan

**Comment by OllieTerrance** [comment]
`chown` is for **ch**anging **own**ership of files, you shouldn't need to do that.

Depending on your init system, you'll probably want to use either the [init script](https://github.com/hangoutsbot/hangoutsbot/blob/master/examples/hangoutsbot.sh) or [systemd service](https://github.com/hangoutsbot/hangoutsbot/blob/master/examples/hangupsbot.service), modified to point to the paths where your bot is installed and a suitable system user.

If you've installed the dependencies in a virtual environment, you'll need to change the start line to be something like `/path/to/venv/bin/python /path/to/repo/hangupsbot/hangupsbot.py`.

**Comment by EvanjKrul** [comment]
I'm sorry I meant to write chmod +x (to make it executable?) ... Any ways so I copied the systemd service to /etc/systemd/system/ as it says and changed it to this:
`# This is a .service file for systemd(8)
#
# If you are using systemd as a system daemon manager, you may use this file
# (with your own local modifications) as a reference.
#
# This file may be copied to /etc/systemd/system/ and modified with your own
# local changes, such as the user to run the daemon as, and where the daemon
# is located

[Unit]
Description=Hangouts Helper Bot
After=network-online.target

[Service]
ExecStart=/home/pi/hangoutsbot/hangupsbot/hangupsbot.py
User=pi
Group=hangupsbot

Restart=on-failure
SyslogIdentifier=hangupsbot

[Install]
WantedBy=multi-user.target`
This did not work... what do I set my group as?
Sorry,
Evan

**Comment by OllieTerrance** [comment]
You're probably better creating a new user and group specifically for the bot:

```
# useradd -m -d /var/lib/hangoutsbot -r -s /usr/sbin/nologin -U hangoutsbot
```

Then both your user and group are `hangoutsbot`, and config files will go in `/var/lib/hangoutsbot`.

**Comment by EvanjKrul** [comment]
Ok so i run that script then update my /etc/systemd/system/hangupsbot.service to match that... How do i transfer my config... Do I need to configure anything for my pi to know to run the script?

**Comment by OllieTerrance** [comment]
> If you've installed the dependencies in a virtual environment, you'll need to change the start line to be something like /path/to/venv/bin/python /path/to/repo/hangupsbot/hangupsbot.py.

That still applies -- update the `ExecStart` line if relevant.

Otherwise, you should then be able to start the service:

```
# systemctl enable hangoutsbot
# systemctl start hangoutsbot
```

If it's not working, check the journal for errors:

```
# journalctl -u hangoutsbot
```

**Comment by EvanjKrul** [comment]
Hello thank you for the reply... when ran journalctl -u hangupsbot i received this output:
`-- Logs begin at Fri 2017-07-28 20:08:38 UTC, end at Fri 2017-07-28 21:15:12 UTC. --
Jul 28 20:58:20 raspberrypi systemd[1]: Starting Hangouts Helper Bot...
Jul 28 20:58:20 raspberrypi systemd[1]: Started Hangouts Helper Bot.
Jul 28 20:58:21 raspberrypi hangupsbot[2055]: 20:58:21 INFO config: /var/lib/hangoutsbot/.local/share/hangupsbot/config.json read
Jul 28 20:58:21 raspberrypi hangupsbot[2055]: 20:58:21 INFO root: memory = /var/lib/hangoutsbot/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
Jul 28 20:58:21 raspberrypi hangupsbot[2055]: 20:58:21 INFO root: creating memory file: /var/lib/hangoutsbot/.local/share/hangupsbot/memory.json
Jul 28 20:58:21 raspberrypi hangupsbot[2055]: 20:58:21 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: Sign in with your Google account:
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: Email: 20:58:22 INFO config: /var/lib/hangoutsbot/.local/share/hangupsbot/memory.json write 0.0007195472717285156
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: Traceback (most recent call last):
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/usr/local/lib/python3.4/dist-packages/hangups/auth.py", line 132, in get_auth
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: raise GoogleAuthError("Refresh token not found")
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: hangups.auth.GoogleAuthError: Refresh token not found
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: During handling of the above exception, another exception occurred:
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: Traceback (most recent call last):
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 1007, in <module>
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: main()
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 1003, in main
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: bot.run()
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 146, in run
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: cookies = self.login(self._cookies_path)
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 137, in login
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: cookies = hangups.auth.get_auth_stdin(cookies_path)
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/usr/local/lib/python3.4/dist-packages/hangups/auth.py", line 64, in get_auth_stdin
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: return get_auth(CredentialsPrompt(), refresh_token_cache)
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/usr/local/lib/python3.4/dist-packages/hangups/auth.py", line 138, in get_auth
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: session, credentials_prompt
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/usr/local/lib/python3.4/dist-packages/hangups/auth.py", line 217, in _get_authorization_code
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: email = credentials_prompt.get_email()
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: File "/usr/local/lib/python3.4/dist-packages/hangups/auth.py", line 74, in get_email
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: return input('Email: ')
Jul 28 20:58:22 raspberrypi hangupsbot[2055]: EOFError: EOF when reading a line
Jul 28 20:58:22 raspberrypi systemd[1]: hangupsbot.service: main process exited, code=exited, status=1/FAILURE
Jul 28 20:58:22 raspberrypi systemd[1]: Unit hangupsbot.service entered failed state.
Jul 28 20:58:22 raspberrypi systemd[1]: hangupsbot.service holdoff time over, scheduling restart.
Jul 28 20:58:22 raspberrypi systemd[1]: Stopping Hangouts Helper Bot...
Jul 28 20:58:22 raspberrypi systemd[1]: Starting Hangouts Helper Bot...
Jul 28 20:58:23 raspberrypi systemd[1]: Started Hangouts Helper Bot.
Jul 28 20:58:24 raspberrypi hangupsbot[2062]: 20:58:24 INFO config: /var/lib/hangoutsbot/.local/share/hangupsbot/config.json read
Jul 28 20:58:24 raspberrypi hangupsbot[2062]: 20:58:24 INFO root: memory = /var/lib/hangoutsbot/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
Jul 28 20:58:24 raspberrypi hangupsbot[2062]: 20:58:24 INFO config: /var/lib/hangoutsbot/.local/share/hangupsbot/memory.json read
Jul 28 20:58:24 raspberrypi hangupsbot[2062]: 20:58:24 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: Sign in with your Google account:
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: Email: Traceback (most recent call last):
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: File "/usr/local/lib/python3.4/dist-packages/hangups/auth.py", line 132, in get_auth
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: raise GoogleAuthError("Refresh token not found")
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: hangups.auth.GoogleAuthError: Refresh token not found
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: During handling of the above exception, another exception occurred:
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: Traceback (most recent call last):
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 1007, in <module>
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: main()
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 1003, in main
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: bot.run()
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 146, in run
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: cookies = self.login(self._cookies_path)
Jul 28 20:58:25 raspberrypi hangupsbot[2062]: File "/home/pi/hangoutsbot/hangupsbot/hangupsbot.py", line 137, in login
lines 1-56`
Any idea on why i get that?

**Comment by OllieTerrance** [comment]
Ahh, you need to run it yourself once so you can sign in:

```
$ sudo -u hangoutsbot /home/pi/hangoutsbot/hangupsbot/hangupsbot.py
```

**Comment by EvanjKrul** [comment]
WOW that worked.... Your a lifesaver! Thanks and sorry for being a noob...I am new to linux.

**Comment by das7pad** [comment]
@EvanjKrul Can you please close the issue, as it is resolved?
