### ISSUE TITLE
Hangout to Telegram bot tldrclear does not work

### ISSUE THREAD

**Issue by nekojaba** [hangoutsbot/hangoutsbot#882]
tldr have to be removed one by one , on v3.0.0 hangoutsbot

ME =  /sync tldr clear
Sync HOTG: Nothing specified to clear.

**Comment by PrinterElf** [comment]
You've read the help for the clear command? ;)

**Comment by das7pad** [comment]
_I updated the [wiki entry](https://github.com/hangoutsbot/hangoutsbot/wiki/TLDR-Plugin#basic-commands) to reflect the actual command behaviour._

**Comment by Terrance** [comment]
As hinted above, it's `/bot tldr clear all` to empty the tl;dr for a hangout.
