### ISSUE TITLE
No token provided when searching with spotify plugin

### ISSUE THREAD

**Issue by vicelversa** [hangoutsbot/hangoutsbot#884]
## Description
After enabling the spotify plugin I receive step for authentication for spotify which requires me to navigate to link and then paste in the link which was redirected to.  This appears to work as a new playlist is created on the spotify account for the chat room.  However, when I try to add a song link in the chat, I receive "No token provided" error in the logs.

## Output of `/bot version`
Bot Version: 2.8.0

## Expected behaviour
Song links (youtube / spotify / soundcloud) should search spotify for matching track and add to chat room (spotify) playlist.

## Actual behaviour
Bot returns "No Tracks Found for..." and logs show error when attempting to search spotify : "No token provided"

## Steps to reproduce:
  1. Enable spotify plugin and proceed with authentication step (browser)
  2. input youtube / spotify / soundcloud link into chat room
  3. observe error about no token:
## Log output

```
06:05:12 INFO plugins.spotify: Searching Spotify for 'Tame Impala Let It Happen'
06:05:12 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): api.spotify.com
06:05:13 ERROR plugins.spotify: <b>Error when searching Spotify:</b> http status: 401, code:-1 - https://api.spotify.com/v1/search?limit=10&q=Tame+Impala+Let+It+Happen&offset=0&type=track:
 No token provided
06:05:13 INFO plugins.spotify: <em>No tracks found for 'Tame Impala - Let It Happen'.</em>

```

**Comment by vicelversa** [comment]
I've been trying again to get the authorization prompt to pop up but cannot seem to figure it out.  Removed plugin details from both config.json as well as conv_data details from memory.json.  Stopped bot, restarted server and went through plugin install again but still cannot get the authorization to pop up again.  Any ideas?

Here is another example of the log errors when simply pasting in a direct spotify track link into chat:

```
19:16:56 INFO event: len/tx: 53/https://open.spotify.com/track/0vwZMxkQo8s0NhWg4EtwYN
19:16:56 INFO plugins.spotify: Music link: https://open.spotify.com/track/0vwZMxkQo8s0NhWg4EtwYN
19:16:56 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): api.spotify.com
19:16:56 ERROR handlers: message: plugins.spotify._watch_for_music_link : coroutine
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spotipy/client.py", line 119, in _internal_call
    r.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/hangoutsbot/hangupsbot/handlers.py", line 263, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/home/ubuntu/hangoutsbot/hangupsbot/plugins/spotify.py", line 70, in _watch_for_music_link
    tr = sp.track(link)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spotipy/client.py", line 223, in track
    return self._get('tracks/' + trid)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spotipy/client.py", line 146, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spotipy/client.py", line 124, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/tracks/0vwZMxkQo8s0NhWg4EtwYN:
 No token provided
```

**Comment by das7pad** [comment]
Thanks for the detailed report @vicelversa 

> I've been trying again to get the authorization prompt to pop up but cannot seem to figure it out.

The core of the plugin `spotipy` writes into the file `.cache-<your spotifyusername>` in your working directory when starting the bot.

I took a glance at the plugin code and found [a note](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/spotify.py#L69)
> track info doesn't require user auth

Could you try using the client with auth?

To do so replace the [lines 69 to 72](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/spotify.py#L69..L72) with the following:
```
            sp = spotify_client(bot)
            if sp is not None:
                tr = sp.track(link)
                track = SpotifyTrack(tr["id"],
                                     tr["name"],
                                     tr["artists"][0]["name"])
                success = add_to_playlist(bot, event, track)
            else:
                success = _('Spotify auth is missing')
```

**Comment by vicelversa** [comment]
Thank you very much @das7pad this worked like a charm for adding direct Spotify track links!
It looks like Spotify made a change as of 29/05/2017 which now requires access tokens for this functionality.

https://developer.spotify.com/migration-guide-for-unauthenticated-web-api-calls/

With that said, it appears imputing a youtube link still encounters the same no token error.  Any hope of fixing that as well?

**Comment by das7pad** [comment]
@vicelversa see #885

**Comment by vicelversa** [comment]
Awesome work! Thank you!
