### ISSUE TITLE
Have query for Integrate hangoutsbot with python(Django)

### ISSUE THREAD

**Issue by skumaran125** [hangoutsbot/hangoutsbot#889]
Hi,
    This is Sabarish. first of all this is Not a Issue, I have some query to integration with Hangoutsbot

Someone sends a message i should respond with an "website url". It works fine for me.(Normal bot flow)
                         
But My query is, when that "website url" is clicked from hangout ,it should redirect to site and check whether the site is logged in by a user or not, using python code and again whether the user is logged in, my response should be "yes" by redirecting it to hangout. If not , "No" by redirecting it to hangout and need to send a corresponding message

Is that possible?

Can anyone please help me by giving ideas in python

**Comment by das7pad** [comment]
_Are you new to Python/Async programming? If that applies, you may start with an easier project first :)_

Could you provide an example conversation with comments what to bot/script should do in each step?
> - User: "/bot myplugin http://example.com"
>   _parse the url_
> - ....

Do you host the mentioned website?

**Comment by skumaran125** [comment]
Hi 

step 1:
Hangout bot has been configured for email (example : xxx@gmail.com)

step 2:
From our mail "Hi" is given, xxx@gmail.com gives a reply as "Hi" by using bot.
If we give a message as "Login", xxx@gmail.com provides an app url (Django python app), after it is clicked it should redirect to our application 

step 3:
From my site, i have picked a response through API, and bringing back to the same app url (Django python app), whether the user is authenticated or not.

Do i have any ways to give the receiving response back to hangout bot as "Yes" logged in and "No" for logged out using python Django code.

**Comment by OllieTerrance** [comment]
Sounds like you're looking for the [API Plugin](https://github.com/hangoutsbot/hangoutsbot/wiki/API-Plugin)?  That will allow you send a Hangouts message (which may be another slash command) to a specified conversation from outside the bot.  See [here](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/tests/api-send.py) for a basic sender.

If you need something more advanced, you may need to set up your own message passing channel so your bot and webapp can communicate, for example [RabbitMQ](https://www.rabbitmq.com) or [Redis pub/sub](https://redis.io/topics/pubsub).  Your webapp would push to the channel, and your plugin would need to listen for messages on the other end.
