### ISSUE TITLE
Sending Message automatically in Thread

### ISSUE THREAD

**Issue by jpakusch** [hangoutsbot/hangoutsbot#891]
Hello Guys,

can anyone help me with sending a message  which is triggered not by a hangouts mesage/event but by  a thread running in the Backgroud?
What i want to achieve is: I wrote a plugin which shall parse a website. by command, i can trigger it and it works fine, it gives me the information i want. But as the next step, i want to check the page permanently for special changes and the trigger a message automatically. 
First of all, this is my example-Thread which is running as expected and which i inserted inside the plugin i wrote by myself:

`# Define a function for the thread

def check_newlog( threadName, delay, bot):
   count = 0
   while count < 5:
      time.sleep(delay)
      count += 1
      print ("%s: %s" % ( threadName, time.ctime(time.time()) ))
      yield from bot.coro.send_message("UgxWJWUKA17uNtJNrh54AaABAagB8ZfGBA", "Thread-Test, every 9s")`

I start the Thread by this command inside the _initialize routine:

`    try:
      _thread.start_new_thread( check_newlog, ("check new logs", 9, bot ) )
    except:
      print ("Error: unable to start thread")`

The print() inside the thread is executed, so the thread works fien. what is not working is the bot.coro.send_message. No Message is sent at all, i suppose its bcause of the "bot" which is not handed over correctly.

I also tried several other things without success:
I defined a sink, which works fine when i call the "base-send.py" example as explained in your tutorial.
It does not work when i call it inside my thread or inside a hangouts-triggered function.
I tried i by two ways:
First of all, i tried to re-implement the base-send.py inside my plugin:

`def send_bot_msg(url, text):
   payload = {'echo': text}
   print(url)
   print(payload)

   headers = {'content-type': 'application/json'}
   print(headers)
   r = requests.post(url, data = payload, headers = headers, verify=False)
   print(r)`

The second, more "dirty" way i tried it was to call a python subroutine:

`   #subprocess.call("sudo /usr/bin/python3 /home/pi/hangoutsbot/hangupsbot/tests/base-send.py "+url+ " "+chr(34) +text+chr(34), shell=True)`

but as you can imagine, both ways did not work.
Does anyone have an idea to solve my problem?

Thanks in advance!

**Comment by OllieTerrance** [comment]
You should avoid using threads with asyncio-based programs such as hangoutsbot, and use [asyncio tasks](https://docs.python.org/3/library/asyncio-task.html) instead.  Start your task using `plugins.start_asyncio_task()` to allow the bot to manage it alongside the rest of the plugin (e.g. stopping it when the plugin is unloaded).

Take a look at the [botalive](https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/plugins/botalive.py) plugin for an example.

**Comment by jpakusch** [comment]
Hello Ollie,

thanks for your message.
I tried starting the Thread as in botalive plugin by calling
`plugins.start_asyncio_task(_check_newlog(bot))`
That worked partly...
First of all, the Task did not run in the Background. So, the Bot was not usable anymore.
Then, when adding a send message function call, the task was not startet anymore.
(that was my original question, how to send a message)
Can anyone help me with that?

Thank you very much!

**Comment by OllieTerrance** [comment]
> the Task did not run in the Background

Assuming that's the same function as `check_newlog` in your original post, you need to replace `time.sleep` with `yield from asyncio.sleep` in order to pass control back to other tasks when yours is waiting.

> when adding a send message function call, the task was not startet anymore

What do you mean?  The task stops after trying to send a message?

**Comment by jpakusch** [comment]
Thanks again for your fast reply!
Okay, first of all, i tried using asyncio.sleep instead of time.sleep as you suggested (and yes, your assumption was right, the called function was exactly the same:
`yield from asyncio.sleep(9)`
The error given when calling the coroutine then is this:
   RuntimeError: coroutine function must be supplied
i also tried using 
`await asyncio.sleep(9)`
but this then leads to an "invalid syntax".

To your other question:
> What do you mean? The task stops after trying to send a message?
No, when trying to send a message using 

`yield from bot.send_message`

the error is the same as above, i get an 
   RuntimeError: coroutine function must be supplied

**Comment by OllieTerrance** [comment]
Presumably you haven't defined your task function as a coroutine then -- it needs to be decorated with `asyncio.coroutine` in order to support calling other coroutines.  (I'd recommend reading the previously linked doc page on asyncio if you haven't used it before, answers to these questions can be found there.)

> i also tried using
> `await asyncio.sleep(9)`
> but this then leads to an "invalid syntax".

The `async`/`await` syntax requires Python 3.5, but is not recommended here given hangoutsbot uses the legacy syntax and they shouldn't be mixed.

**Comment by jpakusch** [comment]
Sorry that i have to bother you again.
first, i tried to understand your link that i did not recognize as such before.
Then i tried to decorate my function either with @asyncio.coroutine in the line above my def or with async def:

`@asyncio.coroutine
def _check_newlog(bot):`

`async def _check_newlog(bot):`

as you might already guess: none of them worked.
i either get an 
`    async def _check_newlog(bot):# threadName, delay, bot):
            ^
SyntaxError: invalid syntax`

or an

`RuntimeError: coroutine function must be supplied`

**Comment by OllieTerrance** [comment]
I'm currently looking at bits of your code in each of your comments, it would help if you post it all together in its current state.  Please wrap it in triple-backticks (` ``` `) to preserve line breaks and spacing.

Your task should be something like this:

```
@asyncio.coroutine
def _check_newlog(bot):
    ...
```

Which should pass hangoutsbot's coroutine check:

```
>>> asyncio.iscoroutinefunction(_check_newlog)
True
```

**Comment by jpakusch** [comment]
Hi Ollie,
i found some time again to continue with my little project.
As expected, your proposed function asycio.iscoroutinefunction(_check_newlog(bot)) returns a false.
So first of all, i would be glad if you helped with with that problem.

Here is the complete code:
```
import logging, sys, resource
import plugins
import requests
import random
import subprocess
import time
import operator
from datetime import date
import string
from collections import Counter
import geocachingsitelib as gc
import argparse, base64
import json
import subprocess
import asyncio

logger = logging.getLogger(__name__)

# Define a function for the thread
@asyncio.coroutine
def _check_newlog(bot):# threadName, delay, bot):
   count = 0
   while 1:
      yield from asyncio.sleep(9)
      count += 1
      print ("Thread-Test")

def _initialise(bot):
    plugins.register_user_command(["lastlogs"])
    print("Task is asyncio TasK: "+str(asyncio.iscoroutinefunction(_check_newlog(bot))))
    #plugins.start_asyncio_task(_check_newlog(bot))

```

**Comment by das7pad** [comment]
The check is not correct, run this instead.
```python
- print("Task is asyncio TasK: "+str(asyncio.iscoroutinefunction(_check_newlog(bot))))
+ print("Task is asyncio TasK: "+str(asyncio.iscoroutinefunction(_check_newlog)))
```

The documentation of `plugins.start_asyncio_task` is missing in the [codebase](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/__init__.py#L227) and [also in](https://github.com/hangoutsbot/hangoutsbot/wiki/Authoring-Bot-Extensions) [the wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Authoring-(2.4-and-above)). You can take a look at [the documentation](https://github.com/das7pad/hangoutsbot/blob/dev/hangupsbot/plugins/__init__.py#L312..L325) in my current version instead.
You forwarded a generator (which is basically `coroutine(*args)`) to `plugins.start_asyncio_task` where it expect the coroutine split from the arguments: `plugins.start_asyncio_task(coroutine, *args)`

For your plugin:
```python
-    #plugins.start_asyncio_task(_check_newlog(bot))
+    plugins.start_asyncio_task(_check_newlog, bot)
```

**Comment by jpakusch** [comment]
Okay, great! 
The Thread is now working perfectly.
But with one difference: i just did not give the "bot" argument. so i call the function with
```plugins.start_asyncio_task(_check_newlog)```
with giving the bot argument additionally, i got the error: "one argument expected but 2 were given".

Okay, but now to my Initial Question: 
How would you now send a message to a certain Chat (by Chat-ID) ?
The 3 Methods i explained in my initial Post did not work.

I really appreciate your help, thanks very much!

greetings, Jan

**Comment by OllieTerrance** [comment]
> with giving the bot argument additionally, i got the error: "one argument expected but 2 were given".

Yep, coroutine functions are [passed the `bot` argument internally](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/__init__.py#L230).

> How would you now send a message to a certain Chat (by Chat-ID) ?

[`bot.coro_send_message(conv, text)`](https://github.com/hangoutsbot/hangoutsbot/wiki/Message-Sending), where `conv` is either an ID or a conversation object obtained elsewhere, and `text` is a string or list of segments.

**Comment by jpakusch** [comment]
Perfect,
now everything works fine.
Thank you very much!
