### ISSUE TITLE
Forecast plugin commands not registered

### ISSUE THREAD

**Issue by zackh105** [hangoutsbot/hangoutsbot#904]
When attempting to use the forecast plugin, commands are not registered and receive a "Unknown Command" response 
Version 2.8.0

Steps to reproduce:
  1. Add key in config.json
  2. Load forecast (/bot pluginload plugins.forecast)
  3. Attempt using commands 'weather', 'forecast', and 'setweatherlocation' respond with "Unknown Command" (This is an admin account- setweatherlocation should work)

Other plugins loaded with the identical load syntax work correctly. The forecast.py file is in plugins, has not been touched.

**Comment by OllieTerrance** [comment]
Are you sure you have your API key in the right place?  The commands don't get registered if there's no key found, in which case you should see an ERROR line in the log:

```
WEATHER: config["forecast_api_key"] required
```

Otherwise, you should see an INFO line instead:

```
plugins: forecast - weather, forecast, *setweatherlocation
```
