### ISSUE TITLE
How to implement a spawn?

### ISSUE THREAD

**Issue by 707** [hangoutsbot/hangoutsbot#906]
I'm trying to implement a spawn that executes a python file with a command. Can someone help me out in configuring it? The python script is stored in the plugins folder. And this is the spawn configuration added to the config.json file.
```

{
....

"plugins": [
    "botaliases",
    "default",
    "mentions",
    "subscribe",
    "autoreply",
    "dnd",
    "starter",
    "remind",
    "fortune",
    "stock"
  ],

 "spawn": {
    "home": "/Users/abcd/hangupsbot/plugins",
    "commands": { "stock": {
            "command": ["python3 home/stock.py"]
        }
    }
  }
...
}
```

On running the bot, the log mentions that the stock plugin is excluded even though I have included in the plugins list. I'm new to python and would love some help. [Here](https://github.com/onaclovtech/hangoutsbot/blob/master/hangupsbot/plugins/stock.py) is the script for reference.

Also, a side question, is it possible to send multiple messages in an hour from a spawn script? Or is it just one message per script execution.

**Comment by renemayer-hb** [comment]
Hi,

i think you need to include the spawn plugin, stock is only a command.

you runs the stock command with: /bot stock

 

Von: Nadeem Shaik [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. Februar 2018 10:16
An: hangoutsbot/hangoutsbot <hangoutsbot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hangoutsbot/hangoutsbot] How to implement a spawn? (#906)

 

I'm trying to implement a spawn that executes a python file with a command. Can someone help me out in configuring it? The python script is stored in the plugins folder. And this is the spawn configuration added to the config.json file.

 
{
....
 
"plugins": [
    "botaliases",
    "default",
    "mentions",
    "subscribe",
    "autoreply",
    "dnd",
    "starter",
    "remind",
    "fortune",
    "stock"
  ],
 
 "spawn": {
    "home": "/Users/abcd/hangupsbot/plugins",
    "commands": { "stock": {
            "command": ["python3 home/stock.py"]
        }
    }
  }
...
}

On running the bot, the log mentions that the stock plugin is excluded even though I have included in the plugins list. I'm new to python and would love some help. Here <https://github.com/onaclovtech/hangoutsbot/blob/master/hangupsbot/plugins/stock.py>  is the script for reference

**Comment by 707** [comment]
Thanks. I would like another clarification, do you know where exactly the config.json file is present in macOS? I'm not able to find it for another project. 

`/<username>/.local/share/hangupsbot/ `is provided in the wiki but there is no such folder like that in macOS

**Comment by das7pad** [comment]
You can use the command [`/bot files`](https://github.com/hangoutsbot/hangoutsbot/blob/0a68b65745ee5212946ea1d05a674a602b2653d1/hangupsbot/plugins/starter.py#L26-L35) to get the path of your `memory.json` and `config.json`.

**Comment by 707** [comment]
Thanks for the help people, I found it.

Now I'm getting an error: _spawn PermissionError: [Errno 13] Permission denied when I try to run bot command
```
"spawn": {
        "home": "/nonstandard/home/directory",
        "commands": { "stock": {
            "command": ["/Users/abcd/h/abcd/bot/hangoutsbot/hangupsbot/plugins/stock.py"]
        }
    }
  },
```

Is there anything wrong with this?

**Comment by OllieTerrance** [comment]
You appear to be writing a plugin, not a spawn command -- the two are separate beasts.

Assuming you do want a plugin, the spawn config won't help you here (the script would be executed standalone, without a reference to `bot` etc.).  You just need to add `"stock"` to your list of plugins in config.json, or use `/bot pluginload plugins.stock` to load it on a running instance (but that won't persist across a restart).

**Comment by 707** [comment]
That makes so much sense, thanks a lot1
