### ISSUE TITLE
Can I make a plugin work in a specific way only for a particular conversation? 

### ISSUE THREAD

**Issue by 707** [hangoutsbot/hangoutsbot#910]
Something like a custom setting for each conversation ID where the plugin works differently for each. Is this possible? 

Eg: 
Chat 1 - /bot time -> will give the time in country A
Chat 2 - /bot time -> will give the time in country B

Both Chats use the same plugin. 
Is this possible?

**Comment by OllieTerrance** [comment]
If you're writing your own plugin, you should look at [`get_config_suboption()`](https://github.com/hangoutsbot/hangoutsbot/wiki/Accessing-and-Writing-config.json) to retrieve per-conversation settings but fall back to a global default.  You could then have something like this in your config:

```json
{
  "tz": 0,
  "conversations": {
    "Ugx...": {
      "tz": -8
    }
  }
}
```

...and call `bot.get_config_suboption(conv_id, "tz")` to fetch the right value.

**Comment by 707** [comment]
Thanks a lot! Do you also know a way to execute multiple coroutines for multiple conversations in a single plugin?

**Comment by OllieTerrance** [comment]
Depends what you want to do with the conversations.

If you just want to send a message to them, [`coro_send_message()`](https://github.com/hangoutsbot/hangoutsbot/wiki/Message-Sending) takes a conversation ID to direct the message at a given chat.  If you need info about a conversation, you should find it in permamem -- either fetch it by ID as `bot.conversations.catalog[conv_id]`, or loop through the results of `bot.conversations.get([filter])` to search by hangout title.

**Comment by 707** [comment]
This helped a bunch. Thanks again Ollie!
