### ISSUE TITLE
Send command to bot via API plugin do not works

### ISSUE THREAD

**Issue by htomasz** [hangoutsbot/hangoutsbot#914]
## Description
Bot should run /bot command
## Output of `/bot version`
Bot Version: 2.7.11
## Expected behaviour
When i send "/bot beer" bot should display beer emo
## Actual behaviour
but now he just say  "/bot beer"
## Steps to reproduce:
  1. Step one
  2. Step two
  3. ...
## Log output
python3 api-send.py https://127.0.0.1:31338 XXXXXX AABBCC "/bot beer"
11:34:16 INFO event: cid/cn: XXXXXX/TESTTEST
11:34:16 INFO event: c/g/un: YYYYYY/botname
11:34:16 INFO event: len/tx: 15//bot echo hello

```
Paste relevant log output here (redact any secrets - API keys, etc.)
```

**Comment by Terrance** [comment]
You appear to be trying to execute commands via the API plugin -- this won't work as the bot may not run commands "as itself" as a security measure.
