### ISSUE TITLE
Typo "Comand" in Telesync

### ISSUE THREAD

**Issue by nerdlinger** [hangoutsbot/hangoutsbot#916]
## Description
Typo in command output, when attempting to sync profiles in the Telesync Plugin
Error is in hangoutsbot/hangupsbot/plugins/telesync/\_\_init\_\_.py
Can be corrected by changing line 630 (in stable) and/or line 838 in v3.0
## Output of `/bot version`
Bot Version: 3.0.0-beta
Python Version: 3.6.3
* aiohttp 1.3.5
* appdirs 1.4.3
* emoji 0.4.5
* hangups 0.4.4
* telepot 12.5
## Expected behaviour
Output should be "Command must be run in private chat!"
## Actual behaviour
Output is "Comand must be run in private chat!"
## Steps to reproduce:
  1. Create Telegram Group Chat
  2. Add Telegram Bot instance to chat
  3. Run /syncprofile

**Comment by OllieTerrance** [comment]
Covered by #883.

**Comment by Terrance** [comment]
...which has now been released in v3.
