### ISSUE TITLE
How to change the location of the config.json, memory.json and cookies.json files?

### ISSUE THREAD

**Issue by PonasKovas** [hangoutsbot/hangoutsbot#919]
Is it possible to keep all the file it needs to run correctly in one folder? Which file imports the data from the config.json, cookies.json and memory.json?

**Comment by thannemann** [comment]
I believe you want the config and memory command line switches.




usage: hangupsbot [-h] [-d] [--log LOG] [--cookies COOKIES] [--memory MEMORY] [--config CONFIG] [--version]

optional arguments:
-h, --help         show this help message and exit
-d, --debug        log detailed debugging messages (default: False)
--log LOG          log file path (default:
                   ~/.local/share/hangupsbot/hangupsbot.log)
--cookies COOKIES  cookie storage path (default:
                   ~/.local/share/hangupsbot/cookies.json)
--memory MEMORY    memory storage path (default:
                   ~/.local/share/hangupsbot/memory.json)
--config CONFIG    config storage path (default:
                   ~/.local/share/hangupsbot/config.json)
--version          show program's version number and exit
