### ISSUE TITLE
Start easteregg in another chat?

### ISSUE THREAD

**Issue by PonasKovas** [hangoutsbot/hangoutsbot#922]
How can I start easteregg in another room so it's members don't see how I did that?

**Comment by OllieTerrance** [comment]
The easter egg plugin [as it stands](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/easteregg.py) doesn't do that.  You could modify it to accept a conversation ID, or just run the corresponding Hangouts slash command yourself.

(In case it's not clear: the easter eggs are stock Hangouts features, Hangoutsbot merely provides its own set of commands to trigger them.)

**Comment by PonasKovas** [comment]
Thank I modified it. I can show my result to you.
```
import random
import asyncio

import plugins


def _initialise(bot):
    plugins.register_admin_command(["easteregg"])


def easteregg(bot, event, easteregg, eggcount=1, period=0.5, *args):
    """starts hangouts easter egg combos.
    supply three parameters: easter egg trigger name, number of times, period (in seconds).
    supported easter egg trigger name: ponies , pitchforks , bikeshed , shydino
    """
    for i in range(int(eggcount)):
        yield from bot._client.sendeasteregg(args[0], easteregg)
        if int(eggcount) > 1:
            yield from asyncio.sleep(float(period) + random.uniform(-0.1, 0.1))
```
Usage: `/bot easteregg ponies 7200 0.5 UgzRc3F2eY--rEG6OfR4AaABAQ`
check the conv_id (UgzRc3F2eY--rEG6OfR4AaABAQ) with `/bot hangouts`
