### ISSUE TITLE
Integration with new Google Chat

### ISSUE THREAD

**Issue by MegFlan** [hangoutsbot/hangoutsbot#923]
I currently have a bot up and running smoothly for Google Hangouts - but the same bot doesn't work with the new chat.google.com platform. The bot receives messages from the chat.google.com platform, but it cannot send them. There are no errors, and the sent message appears in Hangouts but not in the Chat platform. (i.e. can receive and send through Hangouts platform, but can only receive through Chat platform - but can then reply through Hangouts). Any thoughts about how to fix this? Cheers.

**Comment by OllieTerrance** [comment]
See #918 -- Hangouts and Hangouts Chat are completely different systems.  There may be limited interop between the two, but Hangoutsbot is specifically designed only for the former.
