### ISSUE TITLE
How to reset bot to new account? 

### ISSUE THREAD

**Issue by 707** [hangoutsbot/hangoutsbot#924]
I have a bot that pushes messages through one google account. How do i reset it so that I could use the same bot to use another google account? i.e. redo the bot account setup process but with the same config. 

Thanks!

**Comment by sabinico** [comment]
You should remove the cookies.json file saved on **~/.local/hangoutsbot**

TIP: You can create a start script for the bot and pass the cookies / memory / config paths as parameters:

# /usr/local/bin/python3.5 /home/bot/hangoutsbot/hangupsbot/hangupsbot.py --debug  --log /home/bot/files/bot.log --cookies /home/bot/files/cookies.json --retries=1 --memory=/home/bot/files/memory.json --config /home/bot/files/config.json

**Comment by sabinico** [comment]
Mmmm Im not sure but I think there is not way to login the bot using Onelogin atm.

Maybe you can try to modify the login script to match the Onelogin google form.

**Comment by 707** [comment]
Thanks for the hint! I'll try this.

**Comment by 707** [comment]
Any idea where i could find the script that handles the login form part? Would be much appreciated!

**Comment by sabinico** [comment]
https://github.com/hangoutsbot/hangoutsbot/blob/d6b54691e71ac20759155b06cb79c4c57ba25dc4/hangupsbot/hangupsbot.py#L132

The login script comes from hangups not from hangoutsbot

Maybe try to login as bot on browser and copy the cookies manually to the cookies.json

BTW take a look on that issue too, maybe it help you:
https://github.com/hangoutsbot/hangoutsbot/issues/717

Greetings!

**Comment by OllieTerrance** [comment]
tdryer/hangups#350 has the previous discussion on external org auth, along with a manual login process.

**Comment by 707** [comment]
Thanks Sab! I'll look into this.
