### ISSUE TITLE
5/16/18 key error ds:7 

### ISSUE THREAD

**Issue by GodschildGaming** [hangoutsbot/hangoutsbot#925]
my bot randomly died so i went to restart it and boom it wont start and is throwing this error at me here is the log
## Log output

20:00:51 INFO root: memory = C:\Hangout Ai\Gin\memory.json, failsafe = 3, delay
= 1
20:00:51 INFO config: C:\Hangout Ai\Gin\memory.json read
20:00:51 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS conne
ction (1): accounts.google.com
20:00:52 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS conne
ction (1): www.google.com
20:00:53 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\hangups\client.py", line 227, in _initialize
_chat
    self._api_key = data_dict['ds:7'][0][2]
KeyError: 'ds:7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\a\hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "C:\Python\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Python\lib\site-packages\hangups\client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "C:\Python\lib\site-packages\hangups\client.py", line 241, in _initialize
_chat
    'value: {}'.format(e))
hangups.exceptions.HangupsError: Failed to get initialize chat value: 'ds:7'
Client unexpectedly disconnected:
Failed to get initialize chat value: 'ds:7'

**Comment by OllieTerrance** [comment]
This is an issue with hangups, probably you have an old version installed.  Is this a v2 (master) or v3 bot?  The former uses a highly outdated fork of hangups which is prone to protocol change failures.  If on the latter, make sure you're running a recent hangups by reinstalling the requirements with `--upgrade`.

**Comment by das7pad** [comment]
The Code snippet shown in the log is part of `hangups` in version pre `v0.3.0`.

`hangoutsbot` v3 does not work with this old `hangups` version, APIs have changed.
The key `ds:7` is still in their _latest_ version for `hangoutsbot` v2 https://github.com/hangoutsbot/hangups/blob/master/hangups/client.py#L227.

Running `$ pip update -r requirements.txt --upgrade` would just pull the old code from the https://github.com/hangoutsbot/hangups/ fork. 

I suggest taking a look at v3 or some other forks/projects that are maintained.

**Comment by PonasKovas** [comment]
My bot worked just fine, and this morning it just suddenly didn't start up saying the same. I have never had this problem before, and upgrading requirements doesn't seem to help.

**Comment by GodschildGaming** [comment]
@sculpn so you were able to get it working again with by updating to v3.0?

**Comment by PonasKovas** [comment]
@foldingarmchair Did you install the requirements? I also changed to v3.0 and it works fine now.

**Comment by JosephBlock** [comment]
Try running `pip3 install hangups --upgrade`

**Comment by foldingarmchair** [comment]
Turns out I ran an sudo -H pip3 install at some point and it may have ruined dependencies.   Created a new vm , reinstalled to v3.0 using link above.  I am now running v3.0.

Thanks for all the replies.

**Comment by GodschildGaming** [comment]
ok installing version 3 did help fix this issue here is the steps i took to resolve this issue

1) Make a new folder to download 2.8 from github
2) Open terminal/cmd in the folder and run `git clone https://github.com/hangoutsbot/hangoutsbot.git`
3) Open the folder that was just created in terminal/cmd
4) Run `git checkout v3.0`
5) Then run `pip3 install -r requirements.txt`

now in that new folder hangouts bot  should work  if ya had any extra plugins from your old version copy them from the old plugins folder to the new plugins folder

**Comment by ashay88** [comment]
This small change in `$(PYTHONPATH)\site-packages\hangups\client.py` got the current master branch(v2.8)  working for me. The response for some request had changed and this regex change properly captures this.
Change this function 
```
CHAT_INIT_REGEX = re.compile(
    r"(?:<script>AF_initDataCallback\((.*?)\);</script>)", re.DOTALL
)

```
to 
```
CHAT_INIT_REGEX = re.compile(
    r"(?:<script nonce=\"[a-zA-Z0-9_+/]*\">AF_initDataCallback\((.*?)\);</script>)", re.DOTALL
)
```

**Comment by erk3** [comment]
@ashay88 Thx you sir, fixed it for me.

**Comment by adam-ludgate** [comment]
@ashay88 thanks, fixed for me as well. 
This should be patched into the master branch for now, I'm sure this problem is happening to everyone who's not using the`v3.0` branch

**Comment by jamenlang** [comment]
To find the python path mentioned above, `whereis python` will show a list of directories, one of the versioned paths will be the python path, something like `/usr/local/lib/python3.4/` or `/usr/local/lib/python3.5/`
