### ISSUE TITLE
How do I create a plugin that sends a message to a specific conversation every day at 12 o'clock?

### ISSUE THREAD

**Issue by PonasKovas** [hangoutsbot/hangoutsbot#928]
Can anyone please give me a detailed guide or an example of a plugin that would send a message to a specific conversation every day at 12 o'clock?

**Comment by OllieTerrance** [comment]
Python's asyncio does not lend itself well to triggering events at a specific time.  You may need to look at [sinks](https://github.com/hangoutsbot/hangoutsbot/wiki/Sinks-(2.4-and-above)) in combination with a cron job that triggers it at the right time.
