### ISSUE TITLE
bot + admin same Gmail

### ISSUE THREAD

**Issue by jraspiprojects** [hangoutsbot/hangoutsbot#934]
Would this project work on the same google account for the admin and the bot itself?

**Comment by JosephBlock** [comment]
It will depend, but for the most part, the bot does not respond to messages sent by "itself". But if it's for others to use then it would probably work.

**Comment by OllieTerrance** [comment]
Don't make the bot an admin of itself, it's a potential security hole if one plugin's output is parsed as a live admin command for another plugin.  Plus the above, it will generally ignore itself for most processing, which may make you unable to control it in places anyway.

Just make a new Google account for your bot, it's easy enough to do and you only need to login once more after creation.

**Comment by OllieTerrance** [comment]
Perhaps you could try it yourself and let us know?

Ultimately it's a question of whether [hangups](https://github.com/tdryer/hangups) supports it, but if you're able to login with it using the regular Google sign-in page then it should be fine.  See also tdryer/hangups#350, which may be relevant for service accounts too.
