### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by adam-ludgate** [hangoutsbot/hangoutsbot#953]
## Description
Getting failures to start with `IndexError: list index out of range`
Bot was starting correctly recently. Has anyone else seen this issue?
## Output of `/bot version`
`__version__ = "2.7.10"`
## Expected behaviour
Bot starts correctly
## Actual behaviour
Bot fails to connect on startup
## Log output

```
Traceback (most recent call last):
  File "/home/pi/tools/hangoutsbot/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 114, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 233, in _initialize_chat
    self._email = data_dict['ds:36'][0][2]
IndexError: list index out of range
Client unexpectedly disconnected:
list index out of range
05:59:54 INFO root: Waiting 25 seconds...
06:00:19 INFO root: Trying to connect again (try 5 of 5)...
06:00:19 ERROR root: Maximum number of retries reached! Exiting...
06:00:19 ERROR root: Valid login required, exiting
```

**Comment by PrinterElf** [comment]
Any reason you can't update to v3?

**Comment by adam-ludgate** [comment]
Isn't the latest version 2.8?

**Comment by PrinterElf** [comment]
Technically in Master, you're correct, yes.
However I would recommend switching to the v3.0 branch as it's 415 commits ahead of Master atm, in the final stages of testing, and likely will resolve a lot of your issues.

**Comment by lindi200000** [comment]
You are on Python 3.4. Changed it to 3.5

**Comment by OllieTerrance** [comment]
hangoutsbot 2.x uses a really old forked version of hangups (a Python library that handles the underlying conneciton to Hangouts), which is non-trivial to patch against protocol changes.  You can checkout the v3.0 branch to upgrade to 3.x -- you may wish to take a backup of your config/memory files, though it should be safe just to restart the bot and it'll maintain its settings.

> You are on Python 3.4. Changed it to 3.5

3.4 is still supported, as long as it's 3.4.2+.

**Comment by adam-ludgate** [comment]
Thanks for the feedback guys. I installed Python 3.6 and pulled the v3.0 branch. It's working great now.
I had been looking at `master` branch the whole time so I assumed that there had not been any new contributions.

Now the only thing is that I had written some custom updates for the old hangupsbot to support embedded images in the keyword trigger responses. Will have to write that again, maybe submit a PR for it... unless someone has already done something like this.

**Comment by OllieTerrance** [comment]
> support embedded images in the keyword trigger responses

You can send an image instead of text in v3 autoreplies, by providing a URL as the response text.

https://github.com/hangoutsbot/hangoutsbot/blob/72c952dbff36806dd6bba8ebbe3f0a3c0352d385/hangupsbot/plugins/autoreply.py#L155-L166

**Comment by OllieTerrance** [comment]
> support embedded images in the keyword trigger responses

You can send an image instead of text in v3 autoreplies, by providing a URL as the response text.

**Comment by OllieTerrance** [comment]
We have an explicit guard in place to prevent googleusercontent.com links from being interpreted as images -- I'm unsure exactly how it applies, but it appears to be in order to prevent loops when parsing messages, as image attachments after some stage of the processing become strings containing the URL again.
