### ISSUE TITLE
What is the future of hangoutsbot via Hangouts

### ISSUE THREAD

**Issue by JojoPiARM** [hangoutsbot/hangoutsbot#957]
I learned on the website: https://9to5google.com/2018/12/02/google-hangouts-shutting-down/
It means the Hangouts will split into two parts: Hangouts Chat and Hantouts Meet. Will hangoutsbot work on other application (e.g. Hangouts Chat), when current Hangouts will be end? I hope this hangoutsbot will have supports for continue next years. I love this hangoutsbot. Whato do you think about it?

**Comment by Terrance** [comment]
See #918 and #923 -- Hangouts Chat is a completely separate network with its own bot framework, so hangoutsbot will unlikely be joining it without a significant rewrite.

**Comment by JojoPiARM** [comment]
Yes, I understand it. What options do we have now? Where can I start reading about connect to Telegram?
