### ISSUE TITLE
python3 hangupsbot/hangupsbot.py

### ISSUE THREAD

**Issue by itzjakm** [hangoutsbot/hangoutsbot#969]
when i try to do "python3 `hangupsbot/hangupsbot.py` i get this error
`  File "hangupsbot/hangupsbot.py", line 2, in <module>
    import appdirs, argparse, asyncio, gettext, logging, logging.config, os, shutil, signal, sys, time
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax`
Note: I don't know a lot about programming

**Comment by Terrance** [comment]
Looks like we're incorrectly requiring the `asyncio` backport, which uses syntax incompatible with newer Python versions.  You should be able to `pip uninstall asyncio` to remove the backport and use the system copy of the lib instead.
