### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by HumanityI** [hangoutsbot/hangoutsbot#970]
Em, I simply can't login
![Screenshot 2021-03-16 at 14 36 46](https://user-images.githubusercontent.com/71999350/111261253-8704f500-8665-11eb-95d4-b69e9f466f5d.png)

**Comment by Terrance** [comment]
There's an `Email:` prompt there that you haven't filled in.  If you've set up a system service to run your bot, you still need to run once interactively in order to provide credentials.

If that fails, you'll need to use manual login -- see #966.
